### ISSUE TITLE
Change client gateway URL in configuration

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1001]
A typo was fixed for the client services in production http://safe-client-mainnet.gnosis.io/ -> http://safe-client.mainnet.gnosis.io/ and  http://safe-client-rinkeby.gnosis.io/ -> http://safe-client.rinkeby.gnosis.io/  so please update the clients. Old addresses will be still valid for a couple of months

**Comment by liliya-soroka** [comment]
The full regression will be done to check the moving to the new URL in the release 2.4.0
But it should be retested as soon as the old URLs will be deprecated

**Comment by liliya-soroka** [comment]
Verified
app version - 2.5.0 -1421rc
