### ISSUE TITLE
Tracking of num_keys_imported user property

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1020]
num_keys_imported is an Integer user property that tracks the current number of imported keys.

For v1 of signing feature, it will be 0 or 1. Number is updated on adding/removing key.

- When key is added or removed, the value will change.

**Comment by liliya-soroka** [comment]
one issue to check - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1045
