### ISSUE TITLE
Change the text in the app slogan

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1021]
- On the launch screen, we currently display "The most trusted platform to **store** digital assets on Ethereum". 
- Please change this to "The most trusted platform to **manage** digital assets on Ethereum".

**Comment by liliya-soroka** [comment]
Reopened: the task is not implemented in the latest available build 1374
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a3e5d0b7-8cfb-4e1d-aa10-9cac8d90a03e)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/282a54b2-c64a-4a9d-b1cf-06739176e1d9)

**Comment by biafra23** [comment]
D'oh!

The slogan is also in an image called ic_slogan.xml

**Comment by jpalvarezl** [comment]
Hahaha amazing xD that was also my bad :D

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0-1389
