### ISSUE TITLE
Transaction list reloading logic when going back from transaction details

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1022]
- Always reload transaction list if transaction details were opened from the transaction in the 1st "screen" - visible portion of the list;
- Do not reload the screen when transactions were scrolled (even a little bit) and then transaction details opened and the user got back.

**Comment by biafra23** [comment]
This might be helpful: https://stackoverflow.com/a/38248034

**Comment by liliya-soroka** [comment]
Reopened:
Always reload transaction list if transaction details were opened from the transaction in the 1st "screen" - visible portion of the list;
New created transaction together with Queue section doesn't appear if the tx from the first page was opened
Steps:
1. Open tx list - first page with History section only 
2. Open tx details for the tx on the first page
3. create a new transaction that will be in awaiting confirmation state
4. go back from the tx details to the tx list
Current result: No new created tx with Queue section 

Env:
staging, rinkeby

Version 
2.5.0 -1421rc

**Comment by elgatovital** [comment]
From the epic:
> Always reload if transaction details were opened from the transaction in the 1st "screen" - visible portion of transaction;
> Do not reload the screen when transactions were scrolled and then transaction details opened and user got back.

This means tx list won't be reloaded if you scrolled the list down. If the first tx element is visible and you open some tx item to see details, tx list will be reloaded when you come back.

**Comment by liliya-soroka** [comment]
Verified 
app version 2.5.0 -1421rc
one additional issue for the edge case is created
