### ISSUE TITLE
[Android] Balances total list item

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#1035]
The client gateway will serve this structure under the `/v1/safes/{safe_address}/balances/{fiat}?{trusted}&{exclude_spam}`

```rust 
pub enum Balances {
    fiat_total: String, // total balance in the requested fiat
    Items: Vec<Balance>
}

pub struct Balance {
    pub token_info: TokenInfo,
    pub balance: String,
    pub fiat_balance: String,
    pub fiat_conversion: String,
}

pub struct TokenInfo {
    pub token_type: TokenType,
    pub address: String,
    pub decimals: u64,
    pub symbol: String,
    pub name: String,
    pub logo_uri: Option<String>,
}
```

`trusted` and `exclude_spam` have default values for the apps so they don't need to be changed. 

The UI should be like `Option 2` specified here: https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe/360undefined

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0-1421rc
