### ISSUE TITLE
[Android] “Please check whether the time is correctly set ” is displayed when the proxy is turned on

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1036]
**Describe the bug**

**To Reproduce**
1. Set up a connection to the proxy on a mobile device
2. Run "mitmproxy" command in the terminal on the pc ( the command doesn't send any responses - https://mitmproxy.org/#mitmproxy)
3. Start the app
4. Open any page that requires request: balance, collectables, tx list , safe settings, switch safe
Current result: “Please check whether the time is correctly set ” is displayed

**Expected behavior**
The proper message should be displayed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c7b96cbe-fc35-49b4-8d57-87bec91fabff)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 11
 - App Version 2.4.0- 1337

**Environment**
staging, rinkeby
**Additional context**

**Comment by rmeissner** [comment]
This happens because the SSL handshake fails, which in a normal non MITM world is most likely related to wrong device time, therefore the error is not really inapproriate ;)

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 - 1495
the error for the connection to the proxy with turned on pinning is changed to the "Could not establish a secure connection to the Safe services"
But now I am not sure that it's right message for the case from Richar's comment about the wrong time on the mobile device.
Is it possible to split these cases an show to different messages?
@elgatovital , @rmeissner .
My opinion, If it's not possible to split the cases we need to decide what the case may be more real for the user and show the error for the more realistic case 
cc @tschubotz

**Comment by tschubotz** [comment]
>  Is it possible to split these cases and show to different messages?

What are the 2 cases you are referring to? Splitting between failed ssl handshake (1) due to wrong time and (2) other reasons?

If that's easy to do, ok. But I currently don't see the need for this and why we should spend more time on this. 

Do we have any data on how often we get this error?

**Comment by liliya-soroka** [comment]
No, no any data. I don't think it's a very often case 

In such case I am going to close the issue
Verified
app version 2.5.0 - 1531
