### ISSUE TITLE
[Android]+ is used instead of - on the Action details page in the header for the action in the multisend tx

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1041]
**Describe the bug**
+ is used instead of - on the Action details page in the header for the action in the multisend tx

**To Reproduce**
1. Go to the safe 0x8675B754342754A30A2AeF474D114d8460bca19b on prod mainnet
2. Open cancelled tx with nonce 85
3. Open action details
Current result: There is +0.01Eth to the address in the header

**Expected behavior**
Make sure that the correct amount is used in the header ( - or +)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version:11
 - App Version 2.4.0 -1389

**Environment**
Prod mainnet
**Additional context**

**Comment by elgatovital** [comment]
Fixed in the release candidate, starting from 2.5.0-1460rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 -1460rc
