### ISSUE TITLE
[Android]Crash  AndroidKeyStorage.java line 61

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1042]
**Describe the bug**
The app is crashed for the Nexus 5X - https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/7e1ac6a40ec5eb1a109d4f2f9671e35c?time=last-seven-days&sessionEventKey=5F9FD98F0170000135868FAB917DC526_1468911219262101145

https://issuetracker.google.com/issues/37095309

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android Version: 6.0.1
 - App Version 2.4.0(1384)

**Environment**
prod mainnet

**Additional context**

**Comment by biafra23** [comment]
Similar problem: https://stackoverflow.com/questions/35955604/android-keystore-failed-to-generate-self-signed-certificate-invalid-date-str

Seems to be a rtl locale problem.

**Comment by biafra23** [comment]
These might be the steps to reproduce (Need Android M device to verify):
- Switch phone to RTL (Change language to Persian or Hebrew make sure, you can go back!) via developer options -> Force RTL layout direction
- Delete all app data (or remove the app)
- Start app
- Add safe
- Go to tx list
- Observe crash

**Comment by biafra23** [comment]
Related? https://issuetracker.google.com/issues/37095309

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0-1475
