### ISSUE TITLE
[Android]Invalid address is displayed instead of No internet connection 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1050]
**Describe the bug**
Invalid address is displayed when the valid safe address is scanned or valid ENS name is entered when internet connection is off

**To Reproduce**
**Precondition 
1. Uninstall the app
2. clean app install**
Note: I am able to reproduce the issue always after the clean install and time to time without clean install. Mey be you have an idea why it may happen from time to time 

Steps
1. Go to the Load new safe
2. Turn internet connection off
3a. Scan valid QR code
Current result: Invalid safe address message is displayed

3b. Go to the enter ens
4. enter valid or invalid ens name
Current result: android_getaddrinfo: EAI_NODATA(No address associated with hostname)

**Expected behavior**
No internet connection message should be displayed instead of wrong safe address messages

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 11
 - App Version 2.5.0 - 1421rc , 2.5.0-1460rc

**Environment**
prod mainnet

**Additional context**

**Comment by elgatovital** [comment]
unable to reproduce

**Comment by tschubotz** [comment]
I'm also unable to reproduce this on 2.5.0-1421rc. I get the "no internet connection" toast and no crash. I'm on pixel 3a, Android 11.

**Comment by liliya-soroka** [comment]
Reopened:
the description is updated.
For me it's 100% reproducible after the clean app install and is reproducible time to time when there are a few safes in the app already ( don't see the dependencies in such case)
Tested on the 2.5.0 -1460rc

**Comment by tschubotz** [comment]
@liliya-soroka Just in case it is relevant, could you please share the QRcode/Safe address you are scanning + the invalid ENS name you are using the reproduce this?

**Comment by liliya-soroka** [comment]
Verified for the QR code scanning - the issue is fixed.
For the ENS name there is still a wrong error is displayed, if the internet connection had been turned off before the Load safe flow was started
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/844ad0d5-8a0d-4a01-91e2-891fe2f18c35)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/30922a3a-ce2e-480c-ad74-418d9b36acec)
app version : 2.5.0 -1534
staging, rinkeby

I suggest to close the current issue and recheck the case after new error handling is implemented, as ENS error handling will be changed. Don't think that we have to spend more time now to fix the issue

@tschubotz
