### ISSUE TITLE
[Android]Error on the safe setting->advanced page when no internet connection

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1051]
**Describe the bug**
Error on the safe setting->advanced page when no internet connection

**To Reproduce**
1. Go to safe settings
2. turn the internet connection off
3. Open advanced settings

**Expected behavior**
The advanced settings should be loaded without the problems if the safe settings was already loaded

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/55a35fa0-9ccf-411f-bdec-7784a216f089)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 11
 - App Version 2.5.0 - 1421rc

**Environment**
prod mainnet
**Additional context**

**Comment by DmitryBespalov** [comment]
Question about refreshing the data in this screen - needed or not? Previously implemented with pull to refresh.

**Comment by tschubotz** [comment]
I think pull to refresh is fine after no internet connection. what do you think?

**Comment by tschubotz** [comment]
I would actually say "expected behavior" should be here to display the "no internet connection" toast.

**Comment by biafra23** [comment]
The current (build 1534) error message is "Invalid safe address" instead of "No internet connection"

**Comment by liliya-soroka** [comment]
Verified
app version 2.6.0 - 1545rc
