### ISSUE TITLE
Combine dto & models: tx list

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1054]
io.gnosis.data.backend.dto.GateTransaction
io.gnosis.data.models.Transaction

Transaction related models should be placed to io.gnosis.data.models.transaction
Explicitly annotate json attributes

Overlapping ticket: https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/814

**Comment by DmitryBespalov** [comment]
duplicates #814
