### ISSUE TITLE
Collect errors used in the app 

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1058]
Please add them in the doc: https://docs.google.com/spreadsheets/d/1U_cM0Tg3WecJ8XTcoP2VK1ZiCXytAIlm0Y0kdorp4J4/edit#gid=913641804

- Networking errors
- App errors

**Comment by elgatovital** [comment]
@DmitryBespalov android error messages are collected here: https://docs.google.com/spreadsheets/d/1H1ziX5GpsCFK2tnUWthAaza-n2uUgy-G0NyNIxkWr8Q/edit?usp=sharing

**Comment by elgatovital** [comment]
errors are collected, spec document is here https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#, task done

**Comment by liliya-soroka** [comment]
Closed. No QA required
