### ISSUE TITLE
[Android]Crash: BaseViewBindingFragment.java line 15 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1067]
**Describe the bug**
The app is crashed if the tx list is in the process of the scrolling and the another tab( settings or assets is clicked )
https://console.firebase.google.com/u/1/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/a9b74ced91055fd3553839da3c744f10?time=last-seven-days&sessionEventKey=5FAC00200002000136159CDC1D2DA1ED_1472331579758533230

The issue was only on the QA test device in the 2.5.0 version (11.11.2020)

**To Reproduce**
1. Add safe with a long tx list 
2. Swap up to scroll down quickly
3. Click the assets or settings while the tx list is moving during scrolling

**Expected behavior**
The app should not be crashed

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 11
 - App Version 2.5.0 - 1421rc

**Environment**
Prod mainnet
**Additional context**

**Comment by elgatovital** [comment]
Fixed in the release candidate, starting from 2.5.0-1460rc

**Comment by tschubotz** [comment]
I'm also unable to reproduce this on 2.5.0-1421rc. I get the "no internet connection" toast and no crash. I'm on pixel 3a, Android 11.

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 -1460rc
prod mainnet
