### ISSUE TITLE
owner_* screen views are missing the "screen_" prefix

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#1071]
**Describe the bug**
We decided to prefix all screen view events for tracking with `screen_`. This is because due to SwiftUI on iOS we could not use the native screen tracking functionality of Firebase analytics.
This was documented here: https://github.com/gnosis/safe/wiki/Tracking#screen-view-tracking

The new screen tracking events for the mobile signing feature (`owner_enter_seed`, `owner_select_account`) are missing this prefix and are instead tracked directly.

**To Reproduce**
https://console.cloud.google.com/bigquery

```sql
SELECT device.operating_system, event_name, count(*) as num_events
FROM `safe-firebase-mainnet.analytics_243403902.events_20201112` 
where event_name like 'owner_%'
group by 1, 2
```

**Expected behavior**

All screen view tracking events have the `screen_` prefix. Particularly `owner_enter_seed` should be tracked as `screen_owner_enter_seed` and `owner_select_account` as `screen_owner_select_account`

I marked this as major not because of the impact for users but since this is not nice for tracking analyses.

**Comment by biafra23** [comment]
Also change:
    TRANSACTIONS_DETAILS_ACTION("transaction_details_action"),
    TRANSACTIONS_DETAILS_ACTION_LIST("transaction_details_action_list"),

**Comment by liliya-soroka** [comment]
@tschubotz , maybe it makes sense to add a note about "screen_" to the  https://github.com/gnosis/safe/wiki/Overview-screen-tracking doc, as the doc has been used as a source of trues for the Epics - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe/348

**Comment by tschubotz** [comment]
> @tschubotz , maybe it makes sense to add a note about "screen_" to the https://github.com/gnosis/safe/wiki/Overview-screen-tracking doc, as the doc has been used as a source of trues for the Epics - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe/348

Good point, just added it.

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 - 1495
