### ISSUE TITLE
[Android' Advanced app settings: the URL is truncated 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1084]
**Describe the bug**
The endpoints urls are truncated , so it not possible to see them full and to enter manually without copy/past 

**To Reproduce**
1. Go to the app settings
2. Open advanced

**Expected behavior**
The urls should be shown fully in a few lines

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/daeaa456-4fe2-4f86-9994-82885cb3b242)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.5.0 -1495

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
I tend towards using multiples lines and accepting the ugliness since the purpose is to verify the URL.
I see that point that it can be done via copying, but that's a bit more effort.

Happy either way though, I would follow what @posthnikova thinks about this.

**Comment by posthnikova** [comment]
We had a disussion that exposing full url could cause vulnerabilities, is it still the case? https://gnosisinc.slack.com/archives/C63LQTGNB/p1589539426291900. That's why they are short in designs. 
If not, I would display two lines.

**Comment by tschubotz** [comment]
> We had a disussion that exposing full url could cause vulnerabilities, is it still the case? https://gnosisinc.slack.com/archives/C63LQTGNB/p1589539426291900. That's why they are short in designs.

Ah that was only related to the key part of the Infura URL. That one we leave out anyway. i.e. the RPC endpoint url is actually something like https://rinkeby.infura.io/v3/123mykey123 and we just remove the 123key123 part. 
So that's independent from the ellipsizing .



>  If not, I would display two lines.

👍

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 -1595
