### ISSUE TITLE
Update Client Gateway URLs

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1092]
Update your safe-client urls:
- https://safe-client-mainnet.staging.gnosisdev.com/ -> https://safe-client.mainnet.staging.gnosisdev.com/
- https://safe-client-rinkeby.staging.gnosisdev.com/ -> https://safe-client.rinkeby.staging.gnosisdev.com/
Old urls will still work for a month. Remember to change them on production if you didn't:
- https://safe-client-mainnet.gnosis.io/ -> https://safe-client.mainnet.gnosis.io/
- https://safe-client-rinkeby.gnosis.io/ -> https://safe-client.rinkeby.gnosis.io/ (edited)

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 - 1595
