### ISSUE TITLE
Allow enabling/disabling of screenshot permission [Android only]

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1102]
tbd

**Comment by biafra23** [comment]
@tschubotz I would like to remove the special treatment for Debug builds. Meaning: Also a Debug build needs to set this switch to allow, to be able to do screenshots.

**Comment by tschubotz** [comment]
> @tschubotz I would like to remove the special treatment for Debug builds. Meaning: Also a Debug build needs to set this switch to allow, to be able to do screenshots.

That works for me. @liliya-soroka is this ok for you as well?

**Comment by liliya-soroka** [comment]
The test cases are updated:
https://gno.testrail.io/index.php?/cases/view/9833
https://gno.testrail.io/index.php?/cases/view/9832

Verified
app version 2.5.0-1595
