### ISSUE TITLE
Uniform tx list: new layout

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1111]
layout: https://projects.invisionapp.com/share/W4ZBLJ2SHMB#/screens/436755202

- [x] Add separate tabs for queued and history tx's
- [x] Each tab has it's own pull to refresh
- [x] Open queued vs history tab: the same way as the settings and assets tabs are working
  - [x] First time the transaction tab is opened, the queue tab opens
  - [x] Switch safe does not alter the selection of the tabs
  - [x] Switch between bottom tabs resets the tab to the “queued”

loading data is not part of this task.

### Notes
Handle navigation correctly because in the prototype you're not in the fragment that is part of the navigation and that crashes the app when opening transaction details.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 -1686
