### ISSUE TITLE
Unified tx list: Load data

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1112]
- [x] Load queued and next tx's using client gw endpoint for queued tx's
- [x] Load history tx's using client gw endpoint for history tx's
- [x] Support pagination
- [x] Remove queued & history header insertion (insertSeparators in tx list view model)
- [x] Add new tx item types 
  - [x] separator header with text label (for next tx and for queued tx's list, for history tx's grouping)
  - [x] item type for conflict header 
    - [x] nonce
- [x] tx object's should be extended with conflictType field (values e.g. None, WithNext, WithoutNext)

Endpoints:
- https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/history/
- https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/queued/

**Comment by biafra23** [comment]
@liliya-soroka 
Notes for QA. It doesn't make sense to QA this part. I strongly recommend only testing this, when all tickets related to Unified TX list are done.

**Comment by liliya-soroka** [comment]
Loading issue on the transaction tab and queue tab
Reopened:
2.7.0 -1729
https://drive.google.com/file/d/1CGuoUgOCA-wA17c5vWJlBb8S46ZmYJhd/view?usp=sharing

**Comment by liliya-soroka** [comment]
Verified
The separate issue for the data loading in case of imported owner key was created - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1160
app version 2.7.0 - 1751
