### ISSUE TITLE
Unified tx list: queued tab

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1113]
- [x] Load data when opening tab (using client gw endpoint for queued tx data)
- [x] Support pagination
- [x] Show empty placeholder when no queued & next tx's are there
- [x] Use established error handling logic (display snackbar with error codes)
https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#
- [x] Load on pull to refresh
- [x] Add new cell types / view holders
  - [x] conflict header
  - [x] conflict tx with next
  - [x] conflict tx without next
  - [x] list header with text (separator) 

Adjusting time format for list items is handled here
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1115

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/55c8d41c-163f-4835-997b-7b76654890ac)

**Comment by liliya-soroka** [comment]
One critical issue - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1160
the task is verified ( formating and loading issue with imported owner key is known)
app version 2.7.0 - 1751
