### ISSUE TITLE
Unified tx list: history tab

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1114]
- [ ] Load data when opening tab (using client gw endpoint for history tx data)
- [x] Support pagination
- [x] Show empty placeholder when no history tx's are there
- [x] Use established error handling logic (display snackbar with error codes)
https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#
- [x] Load on pull to refresh
- [x] Use cell types for header for group separators 
- [x] Format & display date using device locale for headers
- [x] Modify tx cell to display time instead of date & time

**Comment by liliya-soroka** [comment]
the task is verified 
app version 2.7.0 - 1751
