### ISSUE TITLE
Don't rely on reflection for property names for JSON parsing

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#1124]
Currently we rely on reflection to determine property names of json responses. This is error prone as refactorings (e.g. field name changes) or usage of proguard would break this.

- Annotate all classes that are used by moshi with `Json` and set a name
  - e.g. all classes in https://github.com/gnosis/safe-android/tree/master/data/src/main/java/io/gnosis/data/models/transaction
- Don't use reflection to read field names
  - e.g. https://github.com/gnosis/safe-android/blob/master/data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt#L10

**Comment by liliya-soroka** [comment]
closed , the full regression will be done before the 2.8.0 release
