### ISSUE TITLE
Refactoring pager adapter for assets, tx's, and settings

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1136]
Pagers could use the same base class (e.g. PagerAdapterWithDefaultState or something with a better name) and pass all the enum types, a fragment factory, and the default state fragment as parameters.

Find an elegant way to deal with code duplication in
- AssetsPagerAdapter
- TxPagerAdapter
- SettingsPagerAdapter

without decreasing clarity and readability.

**Comment by DmitryBespalov** [comment]
@elgatovital please close if not needed

**Comment by elgatovital** [comment]
not needed
