### ISSUE TITLE
AppSettings -> User Default Fiat: for balances

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#1150]
## The feature

Fiat currency should be a part of the `App settings`.  A user can select the reference currency to have their balances displayed in the `Assets` tab.

NOTE: for the purposes of currency codes, the backend provides the `ISO 4217 ` currency code, which it's the standard expected by `Currency.getInstance(code: String)` in java.

## Specs
- User should have a clickable setting under `App Settings` in the `Settings` tab
- If there is already a currency selected, the currency code should be displayed in the settings item as shown in the mocks
- The default currency code is `USD`
- The selection screen for currencies, only allows a single currency to be selected at a time.
- The currency codes and currency names are listed separated by a hyphen
- Navigating back to `App Settings` from the currency selection screen, reflects the changes in the user settings
- `Balances` should be updated displaying the information after the change
- For balances, display the currency **symbol** when possible, otherwise default to the ISO 4217 code.
- `Total` follows the same principle as above ☝️ 

## Backend

Supported currencies by the gateway endpoint: `https://safe-client-rinkeby.staging.gnosisdev.com/v1/balances/supported-fiat-codes` (only available in staging, as of the writing of this ticket)

## Tracking

Currency selection screen ID : `screen_settings_app_edit_fiat`

## Assupmptions

- Currency codes are ISO 4217 compliant
- The app consumes the `balances` endpoint of the gateway

## UI screens

App settings: https://zpl.io/2jn91AW
Fiat selection:  https://zpl.io/VKZzjwq

## Error description

Please refer to the `Safe Multisig Error` document and see in the screen tables the entry for `App Fiat Setting`

**Comment by liliya-soroka** [comment]
Need to create test cases and include into full regression

**Comment by liliya-soroka** [comment]
error handling testing is required

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0(1871)
