### ISSUE TITLE
Transaction action details and multi send action details

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1153]
1) Display known address in the transactions list
![Screenshot 2020-12-21 at 18.16.49.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/684f8a12-237d-4c28-a1d4-449693c1d4c3)

2) Display known address in the transaction details
![Screenshot 2020-12-21 at 18.18.37.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/7adb74d8-2ea0-4870-a27b-16d2590222f6)

**NOTE**: on the screenshot above, the only part that is relevant is the "to" icon and name in the 1st section. The "approve" in the screen title is a mistake / not part of this issue.

**Comment by DmitryBespalov** [comment]
The screenshot is misleading - it shows the action details, but as far as I undestand we decided to leave this feature out of the action details?

**Comment by sche** [comment]
will be other ticket
