### ISSUE TITLE
[Android] Known Addresses V2: Safe Settings screens

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1156]
Known addresses are displayed for:
- Safe owner address (not from backend)
Imported owner key (on web it comes from address book, on mobile imported owner key has a default name ‘Imported owner key’, and a custom name once “Multiple keys” feature is implemented)
- Safe version (from backend but not as AddressInfo)
- Fallback handler (from backend)
- Enabled modules (from backend)

## Design 
[Safe Settings Android (Zeplin)](https://zpl.io/bAe0e7n)
[Advanced Safe Settings Android (Zeplin)](https://zpl.io/bzKvKq7) 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/6c899727-436c-4fc8-a8a7-7ffeb4536b27) ![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/3b79723b-2bb4-4392-bbf9-a11869cd0c28)

## Backend
[`SafeInfo` endpoint in the gateway including`AddressInfo`](https://github.com/gnosis/safe-client-gateway/issues/242)

**Comment by biafra23** [comment]
@tschubotz Is it ok, if we skip the `Safe owner address` in this version? I think the same as for confirmations applies. We will not have names in the backend for these. We can certainly show local owner names when we have multiple owners.

**Comment by liliya-soroka** [comment]
Reopened:
1. Known address is missed for "Safe version" on the safe settings page 
Steps:
1. staging, mainnet , safe=alice.eth
2. Check Safe creation ( you will see the Mastercopy 1.0.0 name) 
3. Go to the safe settings
Current result: 1.0.0 hardcode is displayed instead of known address

**Comment by elgatovital** [comment]
@liliya-soroka I don't understand what's wrong here. We show version and not name at this place.

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 - 2315rc
