### ISSUE TITLE
[Android]Local language is used for date in Queue and History 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1158]
**Describe the bug**
Local language is used for date in Queue and History 

**To Reproduce**
1. Set up device language diff from English
2. Go to the app
3. Open Queue or History 
4. check info about date 

**Expected behavior**
The formation for the date should be used according to device settings, but the language should be English only

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6e8d1dfb-9753-4773-9c39-6514d4a267c5)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10.1
 - App Version 2.8.0 -1764

**Environment**
staging, rinkeby
**Additional context**

**Comment by biafra23** [comment]
@liliya-soroka What do you mena by:
>  The formation for the date should be used according to device settings, but the language should be English only

A locale has a language and a region part. Should we always use the language "en" for english but the region from the current locale?

For example in Germany we ave 24h clocks. So the german region would use 13:44 instead of 1:44pm. Is that what we want?

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (1862)
