### ISSUE TITLE
[Android] Delay in safe settings loading if the owner key was imported

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1162]
**Describe the bug**
Delay in safe settings loading if the owner key was imported

**To Reproduce**
1. Go to Transactions without imported owner key
2. Import owner key
3. Go to the transactions
4. Go to the safe settings
Current result: null information is displayed as safe info for a few sec before the data is loaded 
**Expected behavior**
The safe settings should be loaded without null data stage 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/29e6f8fb-b805-479e-ac8f-c27ab1f976ab)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10.1
 - App Version 2.7.0 - 1751

**Environment**
staging, rinkeby
**Additional context**

**Comment by biafra23** [comment]
@liliya-soroka 

Cannot reproduce. Is this still happenning for you?

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (1862)
