### ISSUE TITLE
Offline mode: check if offline status is set correctly

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1163]
"Device is not connected to the internet [...] Error 101" appeared, even though a user was connected to the internet
App had to be killed and restarted again to work.

 happened if the user disables wifi (4g still available). Once the app is killed,  it works again (over 4g)
possible scenario: the user has wifi at home, leaves, and loses wifi connection. App connectivity status is incorrectly set to offline.

Check if connectivity listener gets updates regarding wifi and cellular availability.

- Device: Pixel 3 XL
- Android OS version: Android 11
- Safe app version: 2.7.0-1664rc

**Comment by liliya-soroka** [comment]
It requires the check using android 11.
Not reproducible on the lower android version

**Comment by liliya-soroka** [comment]
@tschubotz or @rmeissner , could you help me to check it, please? I don't have real device with android 11.
I tried to check it with simulator and seems that it's fixed, but it will be better to verify it on a real device

**Comment by tschubotz** [comment]
It seems to work for my on Pixel 3a with Android 11
App version 2.8.0-1882rc

Here's what I did
- Wifi on
- open app
- turn wifi off
- pull to refresh on assets
- No error

**Comment by tschubotz** [comment]
I still get that error after leaving the phone locked for a while, i.e.

- open safe
- all good
- lock phone
- wait ~5min
- unlock
-> no internet error

**Comment by liliya-soroka** [comment]
@tschubotz , could you re-check if the issue exists for you in the version 2.8.0 -1920, please?

**Comment by tschubotz** [comment]
> @tschubotz , could you re-check if the issue exists for you in the version 2.8.0 -1920, please?

I'm on 2.8.0-1915 and I cannot reproduce this issue anymore.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 -1915
