### ISSUE TITLE
[Android] Known addresses in transaction details screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1165]
In the "header" of the token transfer, or contract interaction - we display the known address 

### Name resolution logic
1. If there exists local safe in the app, then use the **safe name and identicon and ellipsized address**
2. Else if backend returns `addressInfo`, display the **logo and name from the info, and ellipsized address**
3. Else display **identicon and ellipsized address**

**Design**: [Zeplin: Contract interaction ](https://zpl.io/bANBNKo)

- ETH, ERC20, ERC721 transfer cases
- All cases of settings change: [SET_FALLBACK_HANDLER, ADD_OWNER, REMOVE_OWNER, SWAP_OWNER, CHANGE_THRESHOLD, CHANGE_IMPLEMENTATION, ENABLE_MODULE, DISABLE_MODULE]

**Comment by biafra23** [comment]
Are Action details part pf this ticket? 
https://zpl.io/2pw4wYy

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/add5a0b9-acb0-42ed-b8b6-b637dc432dce)

**Comment by liliya-soroka** [comment]
Verified
app version 2.10.0 -2058rc
