### ISSUE TITLE
[Android] Signing V2: Discoverability: Safe loaded

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1192]
## Implementation
- On the safe loaded screen we show the following **new** screen 
  - if the following conditions are met:
    - For app update: No owner key currently installed && for the first safe added
    - For new installs: No owner key was ever installed && for the first safe added
  - <**Safe Name**> is read only. Would you like to import  [an] owner key for this safe to confirm transactions?
  - Buttons: 
    - Import owner key -> Onboarding
    - Skip (Go where ever we went before implementing this feature)
- When adding an owner key, we need to store that an owner key has been added separately

## Tracking 
(see: https://github.com/gnosis/safe/wiki/Tracking)
- `user_onboarding_owner_skip` Triggered when clicking the Skip during onboarding, after adding a Safe when asking users to import their owner key.
- `user_onboarding_owner_import` Triggered when clicking the Import during onboarding, after adding a Safe when asking users to import their owner key.

## Design
Safe loaded: https://zpl.io/a7XLlq8

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/9d637494-867f-46a2-91f0-fe326446ca9d)!

**Comment by DmitryBespalov** [comment]
@biafra23 Maybe it's better to split this task into 2 separate tasks?

**Comment by biafra23** [comment]
> @biafra23 Maybe it's better to split this task into 2 separate tasks?
Done

**Comment by liliya-soroka** [comment]
Reopened:
1. Nothing happens if the icon for link to etherscan is clicked near the address ( major issue)
2. The address should be possible to copy to clipboard ( if no time to implement it before the 2.9.0 release I can move it to the separate task )

app version 2.9.0 - 1967rc

**Comment by elgatovital** [comment]
I'll fix everything in scope of this ticket. But we need to clarify our definition of majority :) In my eyes, it's minor as the feature is still fully usable.

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 -1991rc
