### ISSUE TITLE
[Android] Signing V2: Sign transaction

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1193]
## Inform user that execution is not possible on mobile

- Add information for transactions that are ready for execution

https://zpl.io/2vwp6P7

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/00afcd2f-588f-477c-97f2-e2bcd2c60638)

**Comment by liliya-soroka** [comment]
a test case is updated - https://gno.testrail.io/index.php?/cases/view/6329

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 -1920
