### ISSUE TITLE
No way to cancel a transaction

### ISSUE THREAD

**Issue by vporton** [gnosis/safe-android#1199]
**Describe the bug**
There is no way to cancel both:

- a transaction "Awaiting your confirmation"
- a transaction "Awaiting execution"

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - Android Version: 10
 - App Version 2.7.0

**Additional context**
I require two signatures.

**Comment by rmeissner** [comment]
Currently the mobile apps don't have a explicit way to cancel transactions. You can create a cancel transaction (a tx that does nothing besides invalidating the nonce) via the web interface (via the reject button). 

We do plan to iterate on this and track this on our epic repository: https://github.com/gnosis/safe/issues/356

**Comment by vporton** [comment]
> Currently the mobile apps don't have a explicit way to cancel transactions. You can create a cancel transaction (a tx that does nothing besides invalidating the nonce) via the web interface (via the reject button).

I was inexact in words: I don't mean to cancel a blockchain transaction, but just to remove the buttons that start the transaction, so that it would not be "Awaiting your confirmation" or "Awaiting execution". This feature is indeed missing.

**Comment by vporton** [comment]
Reopen, please.

**Comment by rmeissner** [comment]
We are aware that this feature is missing, but we do track this somewhere else (that is why I linked the issue were we track this). As we will implement this on Android and iOS. On this repo we track issues derived from epic that are tracked on the other repo (https://github.com/gnosis/safe). 

Also you submitted this as a bug (which indeed should be tracked here), but a missing feature is not a bug for us.
