### ISSUE TITLE
[Android] Settings UI Changes

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1201]
- [x] Rename 'Contract version' → 'Safe version' in the Safe settings    
- [x] Explain what a fallback handler is. (Link to https://help.gnosis-safe.io/en/articles/4738352-what-is-a-fallback-handler-and-how-does-it-relate-to-the-gnosis-safe)
- [x] Android Zeplin [Web](https://zpl.io/2p6wGNl) | [App](zpl://screen?pid=5e9efc30726e106958cc43de&sid=5ea968e3c4cec8bf7b255fb3)
- [x] Make small headers more prominent (section headers).
- [x] Android Zeplin [Web](https://zpl.io/2yAKvop) | [App](zpl://screen?pid=5e9efc30726e106958cc43de&sid=5ea968e23ce9bf2491eddccf)

**Comment by liliya-soroka** [comment]
Verified
2.8.0 -2022
