### ISSUE TITLE
[Android] Signing V2: Discoverability: Banner

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1205]
## Banner
- Display banner above assets 
   - **if** the following conditions are met:
     - For app update: No owner key currently installed && banner has never been dismissed && have a safe loaded
     - For new installs: No owner key was ever installed && banner has never been dismissed && have a safe loaded
  - **Import owner key**  We added signing support to the app! Now you can import your owner key and sign transactions on the go.
  - Buttons: 
    - Import owner key -> Onboarding
    - Cross in the upper left corner to dismiss banner
- Store whether the banner has been dismissed

## Tracking 
(see: https://github.com/gnosis/safe/wiki/Tracking)
- `user_banner_owner_skip` Triggered when clicking the x on the banner to ask users to import their owner key.
- `user_banner_owner_import` Triggered when clicking the Import on the banner to ask users to import their owner key.

## Design
Banner: https://zpl.io/b6XOZ8R

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/76c9c64a-4a37-4a46-b3d9-8137a8760e1d)

**Updates**: 
When the user starts the import process but does not complete it, the banner should not be shown again (Dirk, 25.1.2021)

**Comment by elgatovital** [comment]
@biafra23 does banner scroll with the list?

**Comment by liliya-soroka** [comment]
Banner test cases are added - https://gno.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_id=1583&group_order=asc

**Comment by liliya-soroka** [comment]
Reopened :
The banner is dismissed if the use follows "Import owner key" link but an owner key is not added
Steps:
1. Install the app
2. Load safe
3. Follow "Import owner key" link
4. Cancel owner key importing
5. Come back to the balance page
Current result: No banner
Expected result: 
Only X button or adding owner key should dismiss the banner

App version 2.8.0 - 1920

**Comment by elgatovital** [comment]
@liliya-soroka What is the source for this requirement? Clicking import link is same as dismissing the banner, except you start the import owner flow. @tschubotz, @posthnikova  what do you think?

**Comment by liliya-soroka** [comment]
https://docs.google.com/document/d/1DqUNRCFpJQWS-HMM4gWzDN-ihNIA8-WoFT8ZfjPHJpw/edit#heading=h.eq8eoqliqxlt 
9. Allow to dismiss banner? How many times to show banner after it’s dismissed?
There is a ‘Close’ button. The banner is shown to users who already have a Safe and never imported an owner key and never dismissed the banner. Only show once. 
After an app update we can only detect whether an owner is imported at the moment. We don’t detect whether a key was imported and removed in the past. So if there is no owner imported at the moment of update the user will see the banner even when they have removed an owner in the past.
------
So, as I understand :
1. the owner key should be imported to dismiss the banner. Or the banner can be closed if X button is clicked
2. If the owner key is deleted the banner should appear. 
It's nice if it's possible to implement without showing banner again if the key was removed

**Comment by tschubotz** [comment]
> @liliya-soroka What is the source for this requirement? Clicking import link is same as dismissing the banner, except you start the import owner flow. @tschubotz, @posthnikova what do you think?

My understanding of "dismissed" was that this only refers to the "close" button. The reason being that we either want the user to actually import a key or specifically dismiss the banner.

I would leave this up to you, @MouazAlzahabi and @posthnikova to decide if this makes sense or you disagree and consider clicking "import" without actually importing a key also as dismissal.

**Comment by posthnikova** [comment]
I would count this as dismissal because they read the banner and onboarding, they know that this feature exists.

**Comment by liliya-soroka** [comment]
Verified
app version  2.8.0 - 1972
