### ISSUE TITLE
Show app review dialog on app start

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1206]
- [x] trigger in-app review dialog on 3rd app start (for the first time)
don't count app starts triggered by a push notification

API doesn't indicate whether the user left a review or not.

- [x] trigger in-app review dialog on every app start after it was triggered for the first time and let API handle whether it will be shown or not.

**Comment by liliya-soroka** [comment]
Current result:
The Rate app dialogue appears on each 3rd app launch if the user selects "rate later"
Not sure that It's expected behaviour. The user may be annoyed by displaying "Rate app" so frequently
@elgatovital , @tschubotz 
app version 2.8.1

**Comment by tschubotz** [comment]
>  The Rate app dialogue appears on each 3rd app launch if the user selects "rate later"

I think this is too often. The user doesn't have a way to say "don't remind me" right?

In the kick off meeting we said that we would just ask 1 once on the 2nd start after adding a Safe. Why is this now differently? https://docs.google.com/document/d/1vjDlJpTGJld0mQRUwjkmY2_SS7yMPRqtADaCEeXM9QY/edit#

**Comment by liliya-soroka** [comment]
@elgatovital , @DmitryBespalov

**Comment by DmitryBespalov** [comment]
it's easy to change on iOS. I don't remember why this was transformed into every 3rd launch - I think because the OS handles it and it won't be shown on every 3rd launch in production - that's the current understanding.

If it will be shown, then it will be super annoying without us able to fix it quickly without additional hot fix release.

**Comment by DmitryBespalov** [comment]
But I think it won't be shown every 3rd time - it is so only in testing.

Even then, it is probably too much after using it - do you feel the same?

**Comment by tschubotz** [comment]
> If it will be shown, then it will be super annoying without us able to fix it quickly without additional hot fix release.

yea, that's my concern also. Hence I would go with just triggering this once tbh.

**Comment by DmitryBespalov** [comment]
sure let's do that

**Comment by DmitryBespalov** [comment]
Change of plans: we double-checked and in production it will NOT be opened every 3rd time even if it opens in testing - it is always opening in test builds when we request this pop-up (and we do it every 3rd time).

Liliya commented then that is ok.

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 -2035
