### ISSUE TITLE
Add rate the app item to app settings

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1207]
- [x] Add `Rate the app` menu item to app settings
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/0ee58513-8697-412b-98f8-69859ab26fda)

- [ ] Navigate to playstore, when clicked

**Comment by liliya-soroka** [comment]
The app settings menu is added, the navigation should be tested in RC on prod mainnet
app version 2.8.1

**Comment by liliya-soroka** [comment]
The app settings menu is added, the navigation should be tested in RC on prod mainnet
app version 2.8.1

**Comment by liliya-soroka** [comment]
The app settings menu is added, the navigation should be tested in RC on prod mainnet
app version 2.8.1

**Comment by liliya-soroka** [comment]
verified
app version 2.8.1
