### ISSUE TITLE
[Android] Long record in total on balance page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1213]
**Describe the bug**
Long value is split into two lines 

**To Reproduce**
1. Go to 0xBc79855178842FDBA0c353494895DEEf509E26bB on prod mainnet
2. Set up UDR as fiat in the app settings
3. Open balance page and check total
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b70e7963-6b17-410f-9a82-028d3fa6768f)

**Expected behavior**
Is it a suitable view of the total amount?

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.8.0 -1882rc

**Environment**
prod mainnet
**Additional context**

**Comment by posthnikova** [comment]
I would probably allow less space for the amount on the right, otherwise no changes, we don't truncate total amount.

![image](https://user-images.githubusercontent.com/45787536/105164785-dae7d780-5b15-11eb-86bf-8f652dda9cd0.png)

**Comment by rmeissner** [comment]
Should we abbreviate the numbers? See https://github.com/gnosis/safe/wiki/How-to-format-amounts#fiat-numbers

**Comment by posthnikova** [comment]
Numbers are truncated 'in cases where horizontal screen real estate is limited and the complete amount is not super important'. 
I think the 'complete amount' means the amount with all digits after the decimal separator, they are not important so we cut them off. Digits before the separator are important.

**Comment by rmeissner** [comment]
We should never truncate number, right? If you truncate a number it might become useless as you don't know what is missing. But the wiki never talks about truncating, it says to appreviate large numbers. 

Personally I would even be fine with "won't fix" as these are super edge cases

**Comment by liliya-soroka** [comment]
verified
app version 2.9.0 -1991rc
