### ISSUE TITLE
Add CLA to repository

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1218]
As we value 3rd party contributions (and more have been coming in), please coordinate to add the cla assistent to all of our repos. You can find an example in the safe-react repo: https://github.com/gnosis/safe-react/blob/development/.github/workflows/cla.yml Also make sure not to merge contributions of external devs before this is in place please :wink:

## Where to add
All our Android-related repositories including library repositories

**Comment by liliya-soroka** [comment]
closed as no QA required
