### ISSUE TITLE
[Android] Signing V2: Add "read only" label to safes

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1219]
### Expected behavior
Show `read only` label in app bar next to loaded safe name if the imported owner key is not an owner for this safe or no owner key has been imported

## Design

[Android (Zeplin)](https://zpl.io/anxRkdl)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/6cd1d492-9d24-4c7b-9709-cfc2e2464f6f)

**Comment by DmitryBespalov** [comment]
@tschubotz on iOS currently the "Read-only" label is shown until we get backend response and can confirm that signing keys are owners. Then the label hides.

What happens is that for a small moment (1 sec or less) the Read-only is shown and then hidden, so there're blinking. 

Should we have done it differently? I.e. don't show it by default and only show read-only when we receive the backend response.

**Comment by tschubotz** [comment]
> What happens is that for a small moment (1 sec or less) the Read-only is shown and then hidden, so there're blinking.

Does this happen only once or e.g. everyime the app is opened?

**Comment by DmitryBespalov** [comment]
it would happen often

**Comment by elgatovital** [comment]
@tschubotz I suggest to revert this logic. Do not show anything and show read only after backend response is received and verified. Better not to show anything than to show false information

**Comment by tschubotz** [comment]
> Better not to show anything than to show false information

Ya, seems better than the opposite 😬

**Comment by elgatovital** [comment]
@DmitryBespalov do you need a ticket for this adjustment?

**Comment by DmitryBespalov** [comment]
@elgatovital yes please

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 - 2501
