### ISSUE TITLE
Empty nonce info is shown for module transactions in advanced details

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#1222]
**Describe the bug**
In the advanced transaction details 

**To Reproduce**
1. Add Safe `0x126ab4d9e87b5cba98Ddeb75Df703E83500b6B7f`
2. Go to transactions
3. Select `Contract Interaction` from 24.01.2021 22:32 (UTC) (the tx right after nonce 14)
4. Select 'Advanced`

**Expected behavior**
- I would expect to not see a nonce field
- I would expect to see the module address that triggered the tx (optional as not specified in the designs)

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - Android Version: Android 11
 - App Version: 2.7.0-1909-internal

**Environment**
- Rinkeby Staging

**Additional context**

**Comment by elgatovital** [comment]
https://safe-client.rinkeby.staging.gnosisdev.com/v1/transactions/module_0x126ab4d9e87b5cba98Ddeb75Df703E83500b6B7f_0x771cbc6ab9e62c70a3cdcbf4e65042bf451b78ffc0e22764d08f8b1ae4023ec5_0xe46fd602e379063a

**Comment by liliya-soroka** [comment]
0x9913B9180C20C6b0F21B6480c84422F6ebc4B808 - one more safe to check on staging, rinkeby. The custom tx between the txs with nonces 710 and 709

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0-2178
