### ISSUE TITLE
[Android]Crash: BaseViewBindingDialogFragment.java line 15

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1224]
**Describe the bug**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/95b2d26f563d00e87ed0dd6f27c23ba8?time=last-seven-days&sessionEventKey=600A666E01F400014007FFE7E32A8474_1498904440277528236

**To Reproduce**
searching for steps

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Xiamo Mi 10
 - Android Version: 11
 - App Version 2.7.0

**Environment**
prod mainnet
**Additional context**

**Comment by tschubotz** [comment]
> @tschubotz Can't reproduce. This happened once (22.1.2021) in version 2.7.0. Can we ignore this for now and revisit it, when it happens again?

Works for me!
