### ISSUE TITLE
Tx details: Add name label to address in confirmed step if it's an owner on device

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1238]
- [ ] Check if signer is an owner
- If yes: show `Imported owner key` name
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/1a393ba4-d66c-4f61-8925-83ea0b9e2366)

**Comment by biafra23** [comment]
This was postponed to the time we implement more than one owner key, right?

**Comment by MouazAlzahabi** [comment]
closed for duplication
