### ISSUE TITLE
[Android]Small UI issue on fallbackhandler link

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1250]
**Describe the bug**
the line thickness for the open link icon is wrong for reading about Fallbackhandler 

**To Reproduce**
1. Go to 'safe settings ->advanced
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7df7e3ae-8f0d-4f07-b2a4-2f3f6cc0a499)

**Expected behavior**
The icon should have the same line thickness as the icon near Fallbackhandler above
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ea968e3c4cec8bf7b255fb3

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.8.0 - 2022

**Environment**
staging, rinkeby
**Additional context**

**Comment by elgatovital** [comment]
why? this icon is smaller, so it will naturally have thinner lines. @posthnikova is it intended, that we use different version of the link icon here?

**Comment by posthnikova** [comment]
This isn't scaled 24px icon, this is a separate 16px icon https://prnt.sc/yq2jcl, you can get it here https://zpl.io/aBGJgJO

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0-2178
