### ISSUE TITLE
[Android] Remove duplication between DTO and ViewData layer for TransactionDetails

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1255]
We should discuss whether we remove `TransactionDetailsViewData` and use only `TransactionDetails` model. We could pass model and map of SolidityAddress to AddressInfoData to updateUi instead of almost identical copy of TransactionDetails model and avoid code duplication. Our TransactionDetailsViewData could be simplified to
```
data class TransactionDetailsViewData(val txDetails: TransactionDetails, knownAddressData: Map<Solidity.Address, AddressInfoData>)
```

**Comment by DmitryBespalov** [comment]
Not needed right now because it is useful
