### ISSUE TITLE
[Android] Enter Key Name screen

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1260]
- Comes after the choosing a key
- Disable import if the name is empty
- Import the key with the name after pressing "Import"
- Register for notifications after the importing

[Zeplin Link](https://zpl.io/br9qAwe)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/48c165c8-1834-4ae0-b63c-1ed8164483ba)

## Tracking
- Screen: `screen_owner_enter_name` (Don't forget the `screen_` prefix :) )

**Comment by liliya-soroka** [comment]
Reopened:
The issues:
1. The app is crashed after the name is entered and the import owner key flow is finished - https://console.firebase.google.com/u/0/project/safe-firebase-staging/crashlytics/app/android:io.gnosis.safe.internal/issues/3ebb25b6d260e701c816b144130036e7?time=last-seven-days&sessionEventKey=606C230901560001168E59EE2420AF81_1526414198689183858

app version 2.12.0 -2382

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 -2417rc
