### ISSUE TITLE
[Android] Edit Owner Key

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1263]
- Name cannot be empty - in that case disable the Save button
- Rename on save
- Delete key on Remove confirmation - and return back to the list of keys. The list of keys should be updated with the name or w/o deleted key when coming back to that list.

[Zeplin Link](https://zpl.io/2G8Dwy3)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/da3129f2-0d1b-44bd-b7d1-106039d4d4af)

# Tracking

- Screen id: `owner_edit_name`

**Comment by biafra23** [comment]
@tschubotz Please add tracking id

**Comment by tschubotz** [comment]
✅

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 -2382
