### ISSUE TITLE
[Android] Choose Owner Key

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1265]
- Can open after the "Confirm" button is pressed in the Transaction Details screen.
- If multiple keys are **eligible** to confirm a transaction, then the user can choose the key to sign with. 

- Key is **eligible** to sign the transaction if 
  - it has NOT signed it before AND
  - It is an owner of the safe (it is in the missing signers list) AND
- I.e. user can add more signatures than the threshold
- If only one key is eligible to confirm a transaction, then the user is still presented with the choice of the keys with only one option to select.
- If none of the keys is **eligible** to confirm a transaction, then it should not be possible to do it in the app

## When to show the screen - Confirmation

Header: **Select owner key**
Text: **You are about to confirm this transaction. This happens off-chain. Please select which owner key to use.**

1. Confirm button tapped
2. "Select owner key" screen shows
3. User taps on a key
3. If passcode is set
  4.1. Enter passcode screen shows
  4.2. On correct passcode entry the transaction gets confirmed.
4. If no passcode, then the transaction gets confirmed right away.

## When to show the screen - Rejection

Header: **Select owner key**
Text: ** You are about to create an on-chain rejection transaction. Please select which owner key to use.**

1. Reject button tapped
2. Rejection Info screen shows
3. "Reject transaction" button tapped
4. "Select owner key" shows
5. User taps on a key
6. If passcode is set
  6.1 Enter Passcode screen shows
  6.2 On correct passcode entry the transaction gets rejected
7. If no passcode, then the transaction gets rejected right away.

[Zeplin Link](https://zpl.io/a3L8jRY)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/acf03e25-7534-4515-9d3a-35c7f3a81bd0)

# Tracking

- Screen id: `screen_owner_choose` (https://github.com/gnosis/safe/wiki/Overview-screen-tracking)

**Comment by liliya-soroka** [comment]
An issue with the confirm and reject buttons status - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1386

app version 2.14.0 - 2417rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 - 2434rc
