### ISSUE TITLE
[Andoid] Parse rejection transaction

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-android#1267]
We need to add new type of transaction called "rejection" and parse it from the response of queued/history transactions, the rejection transaction is custom transaction with new flag isCancellation = true in TxInfo. 
The following [link](https://github.com/gnosis/safe-client-gateway/pull/261/files) is for reference

**Comment by liliya-soroka** [comment]
Verified
The cancelled txs are defined correctly in Queue /History 
app version 2.9.0 - 2099
