### ISSUE TITLE
[Android] Display rejection transaction in transactions list

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-android#1268]
We need to display rejection transaction in transaction list as shown in the flowing: 
- [ ] [Queued transactions](https://zpl.io/bJMyE4J)
- [ ] [History transactions](https://zpl.io/br9w16D)

Note: There is new color added in the style guide.

**Comment by liliya-soroka** [comment]
Verified
app version :  2.11.0 - 2142rc
