### ISSUE TITLE
[Android] Display rejection transaction details

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-android#1269]
We need to display the details of rejection transaction as [designed](https://zpl.io/aX6BY8x).

### **Note**
- Rejection transaction can't be rejected, so we need to remove rejection button 

 ### **Help links**
- [Why do I need to pay for rejecting a transaction?](https://help.gnosis-safe.io/en/articles/4738501-why-do-i-need-to-pay-for-cancelling-a-transaction)

**Comment by liliya-soroka** [comment]
Moved back to Ready for QA as waiting for back-end to test:
Note
Rejection transaction can't be rejected, so we need to remove rejection button

**Comment by liliya-soroka** [comment]
Verified
rejection button was removed for the rejection tx
app version 2.11.0 -2124rc
