### ISSUE TITLE
[Android] Submit rejection transaction

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-android#1270]
We want to create rejection transaction and submit it. 

In order to submit any transaction to back end, a new [endpoint](https://github.com/gnosis/safe-client-gateway/wiki/transactions_proposal) already created. 

In order to submit a rejection transaction we have to use the previous endpoint with the flowing parameters: 
- **To:** safe address
- **Nonce:** the nonce of tx to be canceled.
- **Signature:** the hash of current tx signed by owner key
- **Safe tx gas:** must be zero
- **Sender:** Owner public address
- **All other params:** zero values

### **Notes**
- We can use same error codes and create signature method  used for submit confirmation

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 -2142rc
