### ISSUE TITLE
[Android] Enable reject transaction in transaction details

### ISSUE THREAD

**Issue by MouazAlzahabi** [gnosis/safe-android#1272]
We need to enable reject transaction in transaction details. 

In order to do so, we want to add "Reject" button as show in the [design](https://zpl.io/amjpDNe).

Click on reject button will navigate to [Confirm rejection screen](https://github.com/gnosis/safe-android/issues/1271)

[Backend should return](https://github.com/gnosis/safe-client-gateway/issues/258) if this transaction was already rejected, in that case the button is disabled.

**Comment by liliya-soroka** [comment]
Verified
everything except " Backend should return if this transaction was already rejected, in that case, the button is disabled."
Back-end is not ready.
It was agreed that Reject will be displayed in the 2.11.0 release till the back-end is implemented
app version 2.11.0 -2124rc
