### ISSUE TITLE
[Android] Passcode settings

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1274]
- [x] Add Passcode item to app settings
- [x] On click navigate to Passcode settings screen
- [x] Security details screen content
   - [x] Before passcode was set up / passcode is disabled show following items:
   - [x] Enable passcode
    - [x]  On click start setup flow if there was no passcode before
     - [x] Update screen ui and set passcode to enabled (no passcode confirmation is needed)
   - [x] After passcode was set up / passcode is enabled show following items:
       - [x] Change passcode
           - [ ] On click start change passcode flow
       - [x] Global disable passcode
         - [x] On click show passcode confirmation screen
         - [x] After successful confirmation set passcode to disabled 
         - [x] Show error message if entered passcode is not correct???
            - E.g. shake passcode input field
         - [x] Return to security details & update ui 

## Design
- [Security Settings screen (Zeplin)](https://zpl.io/2En3Gxv) (Passcode enabled) 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/b366acf4-878c-4f26-adb7-041f8c71af18)

- [Security Settings Screen (Zeplin)](https://zpl.io/VO63Enk) (Passcode disabled)
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/e63fe610-8ecd-4b51-9640-b298ed834c63)

**Comment by liliya-soroka** [comment]
Reopened:

The digital keyboard should be used during the passcode set up/change/enter instead of the usual keyboard

app version 2.13.0 -2282

**Comment by biafra23** [comment]
>     The digital keyboard should be used during the passcode set up/change/enter instead of the usual keyboard

1. What do you mean by digital keyboard? Where is this requirement from? What is a digital keyboard? All screens should show a numeric keyboard. According to the designs: https://zpl.io/VDP3Qo3
2. The change passcode part has been moved to a separate ticket: #1340

**Comment by liliya-soroka** [comment]
@biafra23 , yes I mean numeric keyboard, but now we have usual keyboard-
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6c500dd0-3876-4f0d-a73e-f6e06ae070c4)

**Comment by biafra23** [comment]
@liliya-soroka What phone are you using (that shows the wrong keyboard)?

Do you have another phone or emulator to reproduce this?

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 -2381rc
The issue with keyboard is moved to the new ticket
