### ISSUE TITLE
[Android] Reset passcode

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1276]
- [x] Show forgot confirm passcode screen in navigation stack
- [x] On click show reset passcode screen with one button and disclaimer
    - [ ] On button click remove all owner keys and reset secure passcode
    - [ ] Return to the screen where reset was started and show snackbar with passcode turned off message

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/34acf79e-eced-4964-bc48-ecc11becdf1d)

screen: https://zpl.io/VqdM456

**Comment by liliya-soroka** [comment]
Reopened:

Steps:
1. Set up password
2. Import owner key
3. Go to the Change password option
4. Click forgot password->confirm
Current result: "Could not delete all owner keys" error message is displayed but the imported owner key was deleted. Passcode is not disabled
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7cc5a7db-596d-4a6e-9ba1-b7dfe147da1b)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f35d8987-3e8d-45f1-85cc-86739e474879)
Expected result: The key should be deleted without the error and the password should be disabled 


app version 2.13.0 - 2315rc

**Comment by liliya-soroka** [comment]
Verified but the https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1349 exists and should be fixed

app version 2.13.0 - 2337rc
