### ISSUE TITLE
[Android] Passcode protected transaction confirmation

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1277]
- [x] When confirming transaction ask user to enter passcode first
    - Pop-over vs whole screen?
- [x] Show enter passcode screen
- [x] After correct input proceed with tx confirmation flow
- [x] Stay on confirm passcode screen in case of incorrect input
- [ ] User can cancel the flow and return to the tx details screen

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1346

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 -2381rc
