### ISSUE TITLE
[Android] Show passcode reminder banner

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1278]
- [x] Show “Set up passcode” banner in assets coins screen
- [x] User is reminded to set up a passcode if:
    - user has imported signing key
    - passcode was not set
    - banner was not closed / skipped
- [x] Do not show again if explicitly dismissed by the user or if banner action is triggered.
- [x] On “set up” action start set up passcode flow

**Comment by liliya-soroka** [comment]
Reopened:
-----------------
- [ ] The banner was still available after the password adding in the app settings
1. Go to the app settings and add password when the banner is displayed on the assets page
Current result: The password is added but the banner is not hidden
Expected result:
User is reminded to set up a passcode if:
passcode was not set

---------------

- [ ] Import owner key banner is not displayed
1. Clean app install
2. add the first safe and skip "import owner key"
3. Go to the assets
Current result: No "Import owner key" banner
Expected result: Import owner key banner should be displayed if the key is not imported and banner was not skipped

-----------------

- [ ] On “set up” action start set up passcode flow
Current result: The flow is not started if the "Create password now" link is clicked
-----

app version 2.13.0 -2282

**Comment by liliya-soroka** [comment]
Critical issue - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1367 - crash

app version 2.13.0 -2375rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 - 2381rc
