### ISSUE TITLE
[Android]2 rejection tx are created if the tx is rejected on web and on mobile app

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1295]
**Describe the bug**
2 rejection tx are created if the tx is rejected on web and on mobile app

**To Reproduce**
1. Create tx in the safe with a few required confirmation and 3and more owners
2. One of the owners cancels tx on web
3. Go to the mobile app and reject the same original tx as another owner
Current result: 2 rejection tx is created on UI

**Expected behavior**
Always only one rejection tx should be created

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d67cec71-34bf-490c-87da-b35745d56dcf)

**Smartphone (please complete the following information):**
 - Device: Huawei p30
 - Android Version: 10
 - App Version 2.11.0 -2142rc
Safe - 0x1230B3d59858296A31053C1b8562Ecf89A2f888b

**Environment**
staging, rinkeby
**Additional context**

**Comment by biafra23** [comment]
If I am not mistaken, then @rmeissner concluded, that this should not be fixed by the mobile apps.

**Comment by liliya-soroka** [comment]
closed as it's not mobile app issue.
The rejection tx is created incorrectly on web app
