### ISSUE TITLE
[Android] Known Addresses V2: Creation transaction screen

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1296]
Known addresses are displayed for:
- Creator address
- Mastercopy used
- Factory used

## Design
https://zpl.io/bzKvKQE 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/9760c34b-3496-4a6d-aea5-ae37162e66fa)

## Backend
[Add `KnownAddress` for all addresses in the `CreationTransaction`](https://github.com/gnosis/safe-client-gateway/issues/245)

## Spec
[Known Addresses V2](https://docs.google.com/document/d/1if8Sowyj1VhiVcRQojwmzMuDdo48dyndRBFrzIEa6zk/edit#)

**Comment by liliya-soroka** [comment]
Questions:
1. What should be shown in the case non-known address?
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/eaf4b334-22a6-4202-8046-59bed55bac1e)

2. Will be the owner name taken from the imported owner key name?

**Comment by liliya-soroka** [comment]
Verified.
The case when the owner key is imported and saved with the name will be re-tested during multiple owner key verification
app version 2.12.0 -2235
