### ISSUE TITLE
[Android] Known Addresses V2: Transactions list

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1297]
Known addresses are displayed for:
- Safe Apps transactions
- Safe App name overrules “Known address” response, but local address book entries (owner keys names or safe names) overrule Safe App names.
- Add `actionCount` 

## Design
https://zpl.io/aN6r7OZ 

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/1f262607-c706-464b-a144-04e4a89b2f2d)

Safe App information already available on backend and comes inside `transaction` object:

Example Request (Rinkeby Production): https://safe-client.rinkeby.gnosis.io/v1/safes/0x61e35A476E10E4744ef3C051942bbD56620fc2ae/transactions/history
Or Rinkeby staging: https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/transactions/queued?timezone_offset=3600000

```
"safeAppInfo": {
        "name": "Compound",
        "url": "https://safe-apps.staging.gnosisdev.com/compound",
        "logoUrl": "https://safe-apps.staging.gnosisdev.com/compound/Compound.png"
    }
```

**Comment by biafra23** [comment]
@biafra23 What about dark mode?

**Comment by biafra23** [comment]
`actionCount` tells the app how many actions are there.

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 -2191rc
