### ISSUE TITLE
[Android] Known Addresses V2: Transaction details

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1298]
Known addresses are displayed for:
- Safe Apps transactions

## Design
https://zpl.io/VqdpPzl 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/89a93ba2-172e-4d7d-a957-2b12c3ec8e62)

## Backend

Safe App information already available on backend and comes in object (top level):

Example request (Rinkeby production): https://safe-client.rinkeby.gnosis.io/v1/transactions/multisig_0x61e35A476E10E4744ef3C051942bbD56620fc2ae_0xd5e0df7dee0a0393342bbe0d3f64991b5351b399fe69869801f1487e55443f43
or Rinkeby staging: https://safe-client.rinkeby.staging.gnosisdev.com/v1/transactions/multisig_0x1C8b9B78e3085866521FE206fa4c1a67F49f153A_0x06a9526c75f12ab2ebf04d985f785fc6cf857e888474d7202c6f4762dbd38627

```
"safeAppInfo": {
        "name": "Compound",
        "url": "https://safe-apps.staging.gnosisdev.com/compound",
        "logoUrl": "https://safe-apps.staging.gnosisdev.com/compound/Compound.png"
    }
```

**Comment by liliya-soroka** [comment]
Verified, but the https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1006 ios issue should be agreed with the android team.
The separate issue will be created if changes on tx list will be required for logo

app version 2.12.0 -2191rc
