### ISSUE TITLE
[Android] Data Model / Functionality for the Multiple Owner Keys

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1299]
- [x] There is no hard limit on the number of keys to be imported (as much as the device allows)

See specification: https://docs.google.com/document/d/13GirjSwieQaqUPz-8HXzJP_rfgmobSp7E4TpbnLlb0M/edit#bookmark=id.nazzjeun92wz

- [x] If user already imported a key in a previous app version, the key’s name will be “Key 0x1234...2345” where the “0x…” part is the ellipsized address of the key

**Comment by liliya-soroka** [comment]
Reopened:

- [ ] If user already imported a key in a previous app version, the key’s name will be “Key 0x1234...2345” where the “0x…” part is the ellipsized address of the key -  not implemented 
Current result :" Imported owner key " is used as a name of the owner key imported in the previous version with single owner key

app version 2.12.0 -2382

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 -2417rc
