### ISSUE TITLE
[Android] Advanced option on original tx details is hidden under the reject button 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1302]
**Describe the bug**
Advanced option on original tx details is hidden under the reject button . The page is not scrolled fully

**To Reproduce**
1. Go to 'safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open Tx in Needs execution state without rejected tx
3. Scroll the details page down
Current result: Advanced options are not seen and the page is not scrolled to the bottom to show all details

**Expected behavior**
Allow the full page scrolling to displayed advanced options

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/888db6cd-eb13-4254-a2b8-30df75581967)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.11.0 - 2124rc

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
Marking this as major since I think it's important that users can access all context info to tx before signing.

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 -2178
