### ISSUE TITLE
[Android]No logo for the safe app with SVG logo or without logo at all

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1331]
**Bug description**
No logo for the safe app with SVG logo or without logo at all
**Steps To Reproduce**
1. Create tx using WalletConnect/Sablier safe app on web
2. Open txs list and check created tx
**Current result** TThe recipient indeticon is used as walletconnect logo

**Expected Result**
<> should be used in all cases when the safe app logo can not be identified.

**Device & App version**
 - Device/OS: Huawei P30/10
 - App version: 2.12.0 -2191rc
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:

Steps:
1. prod mainnet - add safe 0x84443F61efc60D10DA9F9a2398980CD5748394BB
2. check the tx with nonce 2454
Current result: <> is used instead of known address indeticon on transaction list . It's Uniswap V2
Expected result: If it's known address and not safe app tx the known address logo or indeticon( if no logo) should be used

app version 2.13.0 2375rc

**Comment by liliya-soroka** [comment]
The priority is changed to minor from major

**Comment by liliya-soroka** [comment]
Reopened: the logo is missed for some cases:

1st case
1. prod mainnet - add safe 0x84443F61efc60D10DA9F9a2398980CD5748394BB
2. check the tx with nonce 2454
Current result: <> is used instead of known address indeticon on transaction list . It's Uniswap V2
Expected result: If it's known address and not safe app tx the known address logo or indeticon( if no logo) should be used
app version 2.13.0 2377rc

2nd case:
1. prod mainnet - add safe 0x8675B754342754A30A2AeF474D114d8460bca19b
2. check the tx with nonce 162
Current result: 1inch logo is lost
Expected result: If it's known address and not safe app tx the known address logo or indeticon( if no logo) should be used
app version 2.13.0 2377rc

**Comment by elgatovital** [comment]
GET `https://gnosis-safe-token-logos.s3.amazonaws.com/0x9016aA99b98128ba990097eA3F3D60b5e40775e4.png` returns HTTP 403, Access Denied
This means app correctly handles case when icon cannot be loaded

2nd case is handled correctly
```json
  "type": "TRANSACTION",
      "transaction": {
        "id": "multisig_0x8675B754342754A30A2AeF474D114d8460bca19b_0x7e440ad515686d48206b9d6daca2d0c337810f2181a6ba4a3ab79f3e277d2ce9",
        "timestamp": 1616702744000,
        "txStatus": "SUCCESS",
        "txInfo": {
          "type": "Custom",
          "to": "0x8D29bE29923b68abfDD21e541b9374737B49cdAD",
          "dataSize": "356",
          "value": "0",
          "methodName": "multiSend",
          "actionCount": 2,
          "toInfo": {
            "name": "Gnosis Safe: Multi Send 1.1.1",
            "logoUri": "https://safe-transaction-assets.staging.gnosisdev.com/contracts/logos/0x8D29bE29923b68abfDD21e541b9374737B49cdAD.png"
          },
          "isCancellation": false
        },
        "executionInfo": {
          "nonce": 191,
          "confirmationsRequired": 2,
          "confirmationsSubmitted": 2
        }
      },
      "conflictType": "None"
    }
```
toInfo is displayed as it should

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0  - 2417
