### ISSUE TITLE
Change Passcode

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1340]

**Comment by liliya-soroka** [comment]
Reopened:

- [ ] small issue with the text but it influence on the understanding what is going on now
Steps:
1.Click Change password
2. Enter valid current password
Current result: "Create **a 6-digits passcode** " screen is opened
Expected result: https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/6033acf22c9bac1290b66999 
"Create a new 6-digits passcode" screen should be opened 
app version 2.13.0 -2315rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 - 2381rc
