### ISSUE TITLE
[Android] Confirm button doesn't disappear after the tx is confirmed on tx details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1346]
**Describe the bug**
Confirm button doesn't disappear after the tx is confirmed on tx details page 
Note: it was already implemented on the back-end and ios, so It's expected that no confirm button if the tx was just confirmed

**To Reproduce**
1. Import owner key
2. Create tx that required confirmation from the imported owner
3. Go to the Queue 
4. Open transaction details for the tx that requires confirmation from the imported owner
5. Click Confirm button
Current result:  Tx details is updated with the info about the imported owner confirmation on tx details , confirm message appears but the Confirm button is still available

**Expected behavior**
The  confirm button should disappear from the tx details page as soon as the tx is confirmed by the imported owner

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9be3f893-3359-4636-872a-a0a6ed5d5bb7)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.13.0 - 2315rc

**Environment**
staging, rinkeby
**Additional context**

**Comment by biafra23** [comment]
Should it really disappear or be disabled?

**Comment by liliya-soroka** [comment]
In the case listed above : the buttons should be disabled

**Comment by liliya-soroka** [comment]
Reopened:
safe = lilltestsafe.eth , staging, rinkeby ( the same on prod mainnet)
1. Import owner ( PR - ca30cbabffad80de6a0049be5eae6197b7c4fef98d5304436cd738e4e209dc73) and set up passcode
2. Go to the Queue
3. Open original tx in Needs execution status
Current result: "Confirm" button is displayed for the tx in "Needs execution" status
Expected result: Txs in the Needs execution status should not have any Reject or Confirm button

app version 2.13.0 - 2377rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 -2381rc , but another additional case with Confirm button exists and reported separately
