### ISSUE TITLE
[Android]Confirm button is displayed for already confirmed tx if the cancellation tx is not confirmed by the imported owner

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1371]
**Describe the bug**
Confirm button is displayed for already confirmed tx if the cancellation tx is not confirmed by the imported owner.
So it's displayed even when the tx is in "needs execution" status. After Confirmation is clicked again the successfully confirmed message appears but the button doesn't disappear

**To Reproduce**
Precondition:
Safe with 2 required confirmation
1. Import one of the owner
2. Another owner creates tx on web
3. Imported owner confirmed original tx 
Current result: The tx status is changed to Needs execution and No buttons on UI

4. Go to the web as the tx creator and rejects transaction
5. Open original tx on mobile
Current result: Confirm button is displayed in both original and cancellation tx

**Expected behavior**
No confirm button in original or cancellation tx if it's already confirmed by the imported owner

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b6795339-7ef8-406a-a50f-0e0faed7cc2d)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.13.0 - 2381rc

**Environment**
prod rinkeby
**Additional context**

**Comment by biafra23** [comment]
@tschubotz @liliya-soroka 
> Expected behaviour:
> No confirm button in original or cancellation tx if it's already confirmed by the imported owner

Is that really the expected behaviour? An owner should not be able to change their mind to rejecting after they confirmed?

**Comment by biafra23** [comment]
I think in this case the rejection tx should still be confirmable. But the original tx should indeed have no button.

**Comment by tschubotz** [comment]
I think because of 

> 3. Imported owner confirmed original tx

The imported owner did already confirm the original tx before. That's why Liliya was expecting no confirm button in the original tx.



> An owner should not be able to change their mind to rejecting after they confirmed?

Agree, an owner should be able to change their mind, i.e. be able to create a cancellation tx after previously confirm the original tx.

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 -2479
