### ISSUE TITLE
[Android]Usual keyboard is used instead of numerical on some android devices

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1372]
**Describe the bug**
Usual keyboard is used instead of numerical on some android devices

**To Reproduce**
1. Go to the app settings
2.Set up or change passcode
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3a1e9793-5ddc-4db2-b23a-519f17506b09)

**Expected behavior**
Numerical keyboard should be used instead of usual 

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version:10
 - App Version 2.13.- -2381rc

**Environment**
prod, mainnet, rinkeby
**Additional context**

**Comment by lukasschor** [comment]
Is it actually possible to enter non-numerical values?

You mention `on some android devices`, does this affect only a few devices or is it a broader issue?

**Comment by biafra23** [comment]
Mintt S (Android 7) -> Numeric
Nexus 5X (Android 8.1.0) -> Numeric
Pixel 3a (Android 11) -> Numeric
Fairphone 4 (Android 10/LineageOS) -> Numeric

**Comment by liliya-soroka** [comment]
@lukasschor  and @biafra23 , seems that in the most cases on different devices the correct keyboard is used.

**Comment by elgatovital** [comment]
@liliya-soroka can we close this issue?

**Comment by elgatovital** [comment]
works on all devices
