### ISSUE TITLE
[Android] Forced update dialog

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1379]
### Zeplin UI

We should use native [dialogs](https://developer.android.com/guide/playcore/in-app-updates).

If not possible to change wording, then use these custom dialogs:

- https://zpl.io/2ZRGmgq
- https://zpl.io/bWMwmRK
- https://zpl.io/brqJ0r1

### Firebase config variables

- `newestVersion` - newest app version. Default is null.
- `deprecatedSoon` - app versions to be deprecated soon. Comma-separated list of ranges or version numbers (mixing is possible). Each range consists of lower and upper version (inclusive). Values in range separated by minus sign “-”. Default is empty/null
  - `x1.y1.z1-x2.y2.z2,x3.y3.z3-x4.y4.z4,x5.y5.z5`
    - This encodes 2 ranges and 1 explicit version:
    - From `x1.y1.z1 `to `x2.y2.z2`
    - From `x3.y3.z3` to `x4.y4.z4`
    - Just `x5.y5.z5`
- `deprecated` - app versions that are deprecated. Comma-separate list of ranges or version numbers (see above). Default is empty / null.

### The logic for showing the alert

- **IF** app version is in the deprecated list, **THEN** show forced update
- **ELSE IF** app version is in deprecated soon list, **THEN** show the dismissable update alert
- **ELSE IF** the app version is lower (sem version semantics lower) than newest version, **THEN** show the dismissable update alert once for this app version.

### Strategy for loading the remote config parameters 

- Fetch new values in the background
- Activate on app start so that the values are applied
- On app start react on currently stored (or default) values.
- We use Firebase’s default options for updating the remote configuration (once per 12 hours)

 ### Change The Release Process Documentation

- We will have the variables documented in a new sheet in the following doc
  - Note: try to merge the ranges to make them simpler.
- When making a new release candidate, the PO should decide the status and document it in the related doc. (if to deprecate or deprecate old versions soon)
- The release person should update the parameters on the firebase console first on staging (Mainnet/Rinkey) in accordance to the documented parameters, it’s preferable to ask for review from other team members, then notify QA about the release candidate.
- The QA should test that the app is acting in accordance with the defined parameter values.
- After making sure that the app is available to be downloaded, the release person copies the same parameters from staging to release project.

**Comment by liliya-soroka** [comment]
The open question is the format :
do we need to split and use a different configuration for subversion of the same release version?( for example 2.16.0 -2512rc and 2.16.0 - 2513rc )
https://gnosisinc.slack.com/archives/C01DB3E66Q3/p1620830502077000

except it the task is verified
app version 2.16.0 -2612rc
