### ISSUE TITLE
[Android] Missing tracking for multiple owner key

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1387]
**Describe the bug**
The tracking of the number of imported keys on remove and import is missed and user_key_deleted is missed

**To Reproduce**
1. set up everything for check tracking in debugView
2. Run app
3. Add safe and add a few owners ( without calling the app from background or app restart)
4. Delete owners ( without calling the app from background or app restart)
**Current result** No tracking of number of imported keys on imported, removed and no tracking on On successful removal -> user_key_deleted (new)
The number of imported keys is updated only on app start

**Expected behavior**
Requirments for tracking:
Tracking:
Screen appears -> screen_owner_list (new)
On successful import -> user_key_imported (existing event)
On successful removal -> user_key_deleted (new)
App start, imported, removed -> update User Property num_keys_imported (existing)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - Android Version: [e.g. Android 9]
 - App Version [e.g. 1.0.1]

**Environment**

**Additional context**

**Comment by tschubotz** [comment]
Marking as major since tracking shouldn't block the release in this case, but we should fix this soon.

**Comment by biafra23** [comment]
What about logging when the user deletes all keys because they forgot the passphrase? At the moment each key is deleted separately. So we could track all those deletions. 
Should we?

**Comment by tschubotz** [comment]
> What about logging when the user deletes all keys because they forgot the passcode? At the moment each key is deleted separately. So we could track all those deletions.
> Should we?

I think this case should be a different tracking event actually. something like `user_forgot_passcode` or similar

**Comment by liliya-soroka** [comment]
Reopened:
TRhe user property num_keys_imported is not updated without app restart (calling from background). The property should be updated on the importing or deleting owner key 
app version 2.14.0 - 2482

**Comment by biafra23** [comment]
@liliya-soroka The property is updated on delete but Firebase refuses to send it immediately. 

There is nothing we can do on the client side.

**Comment by liliya-soroka** [comment]
the issue is closed.
app version 2.14.0 -2501
