### ISSUE TITLE
[Android] Empty owner list is displayed if the forgot passcode is pressed during confirmation 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1388]
**Describe the bug**
Empty owner list is displayed if the forgot passcode is pressed during confirmation. No need in empty list , the user should be navigated back to the tx details as non owner

**To Reproduce**
Precondition:
1. add safe
2. import owners
3. set up a passcode
4. create tx that will require a confirmation from the imported owner

Steps
1. Go to the tx details for the tx that requires confirmation
2. Click on 'Confirm'
3. Select owner
4. Click "Forgot passcode" on the enter passcode screen
**Current result** the empty owner key list is displayed

**Expected behavior**
The user should be navigated back to the Tx details as non-owner, no need in displaying owner key and request additional step from the user to go back

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ce92ae99-67d1-4416-8d69-08f9878a7b8e)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.14.0 -2417rc

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
marking as minor since it's more of an inconvenience at this point.

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 - 2479
