### ISSUE TITLE
App is available from the push notification for both deprecated and deprecated soon options

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1421]
List of the forced to update issues(try both deprecate and deprecatesoon):

- [ ] No "lock" screen on the app open from push notification
From Epic: Users see dialog on every app start (including when being opened via push)

**Smartphone (please complete the following information):**
 - Device: Huawei p30
 - Android Version: 10
 - App Version 2.15.0 

**Environment**
staging, rinkeby 
**Additional context**

**Comment by elgatovital** [comment]
@liliya-soroka 
remote config was set to wrong values
deprecated 2.14.100-2.14.0 (interval does not include 2.15.0)
deprecatedSoon 2.14.0 (also not including 2.15.0)

**Comment by liliya-soroka** [comment]
verified
app version 2.15.0 -2592
