### ISSUE TITLE
[Android]Deprecatedsoon screen blocks QR scanning for load safe flow

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1425]
[Android]Deprecatedsoon screen blocks QR scanning for load safe flow

**To Reproduce**
1. use deprecated soon app version
2. run app_>skip update
Current result: the user is redirected to the "Deprecatedsoon" screen from the QR scanning screen

**Expected behavior**
It should be possible to add safe using QR code in deprecated soon version 

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.15.0 - 2592

**Environment**
staging, rinkeby 
**Additional context**

**Comment by biafra23** [comment]
@liliya-soroka I cannot reproduce this with the latest internal version (2.16.0-2612rc-internal) . Or a build from master.

Can you still reproduce this?

If so, what did you enter in the firebase console for deprecatedSoon and what version of the app did you use?

I can reproduce it with 2.15.0-2592-internal.

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2612rc
