### ISSUE TITLE
Integrate biometric prompt

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1429]
- [x] Integrate biometric api
- [x] Show biometric prompt if biometric authentication is available on device
- [x] Display biometric icon on enter passcode screen if biometric option is available
- [x] Display biometric setting item in passcode settings if biometric option is available
- [x] React to system changes regarding biometric data

    Touch ID/Face ID button will request the system biometry login instead of entering passcode.
    Touch ID / Face ID button must be hidden if the "Login with biometrics" switch is OFF.
    The button is only for requesting TouchID/FaceID, it doesn't change or navigate to the settings.

Ask to enable biometry after the passcode is set

    Fingerprint icon
    Cancel button
    Text “Would you like to enable biometry for passcode?”

Remember user’s choice - that will set the position of the “Login with biometry” setting.

...
[spec link](
https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#bookmark=id.y00zl3xybmf1)

Note: we don't have test device for Face ID testing

**Comment by liliya-soroka** [comment]
For testing : https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1353 - retest each point from the ticket

**Comment by biafra23** [comment]
Here is a screenshot of the biometric prompt. Every string that ends in (customizable) can be changed. 
The fields are called:
- Title
- Subtitle
- Description
- NegativeButton

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/35d38a80-88c1-4749-a5f7-32168542de4b)

**Comment by biafra23** [comment]
Example for app access:

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/9170be71-7086-4320-ae15-b70dc37afec6)

**Comment by biafra23** [comment]
Example for signature authorization:
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/40e14512-5eda-4946-869b-cc81c7d7fcc7)

**Comment by liliya-soroka** [comment]
Returned back:
Description: Can not activate biometric optiuon after updating the app to the rc version

1. Install the previous app version
2. add safe-> import owners-> set up passcode
3. update to the lates version ( rc version)
4. Go to the passcode settings
5. turn on "Biometric" option 
Current result: The error about owner key deleting is displayed instead of biometric option activation 
https://drive.google.com/file/d/1PjFDtqXrv6AszNpCjWrLbWVTGCv_d0y_/view?usp=sharing

app version 2.17. 0-2670rc
android 10
Huawei P30
staging, rinkeby

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1490 - crash

**Comment by liliya-soroka** [comment]
Verified
Two separate issues are created for the prompt
app version 2.17.0 -2758rc
