### ISSUE TITLE
[Android] Known addresses v3

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1430]
[spec](https://docs.google.com/document/d/1JADxSxlA3JdFcR31CuGuGe8C_tBPgPKjXXoF_OUUlrc/edit)

- No changes to the current data decoded data structure
- Only new "addressInfoIndex" dictionary is added to txData structure
- Client will replace the addresses with the info found in the index
- Standard logic to display local owner keys or safe name is used.
- The screens affected: 
  - MultiSend Action List
  - MultiSend Transaction Action Details
  - Transaction Action Details

Please consult @sche about the way to implement it in case we can reuse iOS implemented experience.

**Comment by liliya-soroka** [comment]
Reopened:
Standard logic to display local owner keys or safe name is used.
The safe name/ owner key name  is not used on the action details and actions list

app version 2.17.0 - 2801

**Comment by elgatovital** [comment]
extracted to https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1525

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2816rc
