### ISSUE TITLE
[Android]Crash: ECDomainParameters.java line 25

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1431]
**Describe the bug**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/275431a5-747e-4441-a5d2-fcd0f18c0930)
Crash - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/5513ff0beec2d8974ab58d2b033abe9e?time=last-seven-days&sessionEventKey=609A40F3012500012427708092846F9D_1539393190441211088
and the same :
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/c3cc206d1e1aacb42b9f3116aebbe769?time=last-thirty-days&sessionEventKey=6097D26B005F000164BA9141F8345A77_1538709035143595528
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3424db34-3a0f-4ae6-978a-c7d5e69af7fc)
**To Reproduce**
1. ????
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/59a30dd7-8998-49ca-b0ce-1bcf9b444943)
**Expected behavior**
No crash 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: different
 - Android Version: 11
 - App Version 2.15.0 (2531)

**Environment**
prod mainnet
**Additional context**

**Comment by biafra23** [comment]
Timeboxed as it didn't happen in the last version. Only in 2.15.0

**Comment by biafra23** [comment]
I am running this endless loop for a while:
```
            while (true) {
                val mnemonic = bip39.generateMnemonic(languageId = R.id.english)
                derivator.initialize(mnemonic)
                val key = derivator.keyForIndex(0)
                Timber.i("---> mnemonic: $mnemonic")
                val address = derivator.addressesForPage(0, 1)[0]
                credentialsRepository.saveOwner(address, key, "no name")
                val owner  = credentialsRepository.owner(address)!!
                val decryptedKey = credentialsRepository.decryptKey(owner.privateKey!!)
                try {
                    CheckedKeyPair.fromPrivate(key)
                    CheckedKeyPair.fromPrivate(decryptedKey)
                } catch (e: java.lang.IllegalArgumentException) {
                    e.printStackTrace()
                    throw e
                }
                credentialsRepository.removeOwner(owner)
            }
```

This should surface the error at some point. CheckedKeyPair() uses ECPrivateKeyParameters(priv, SECP256K1) which threw the exeption above.

**Comment by liliya-soroka** [comment]
14.06
Still actual for 2.16.0
Seems that somebody can not start app today(35 crashes):
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/58349c12-8f)69-418d-8f29-f4b758c71599

**Comment by liliya-soroka** [comment]
Still actual in 2.16.0 and look like one or two users can not start the app today (14.06.2021)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f37ae6ad-d699-434a-bb77-83cb857b6915)

**Comment by liliya-soroka** [comment]
still happens in 2.17.0 - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/5513ff0beec2d8974ab58d2b033abe9e?time=last-seven-days&sessionEventKey=60C815BB02D000010FA12B2A7DE46684_1552293521333419314

**Comment by biafra23** [comment]
The fix only prevents new broken keys from being imported. We also need a fix that prevents crashes when a broken key is already imported.

**Comment by biafra23** [comment]
This PR should prevent crashes during startup. #1518

**Comment by liliya-soroka** [comment]
closed.
in 2.18.0 -2819rc
