### ISSUE TITLE
[Android] OwnerEnterNameFragment.java line 64

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1432]
**Describe the bug**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/4e54f73c60e6f4a6d3285ba4ef0b450c?time=last-thirty-days&sessionEventKey=608BAA9200A800011AD1BE4C0089BEF0_1535294839279361589

**To Reproduce**
1. ????
**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 2 different
 - Android Version: 9
 - App Version 2.14.0 (2460)

**Environment**
prod mainnet
**Additional context**

**Comment by elgatovital** [comment]
Not reproducible and since version 2.14.0 no crashes. I would close it and monitor if this issue occurs in the future

**Comment by liliya-soroka** [comment]
agreed, it will be reopened in case of appearing 
app version 2.16.0 -2631rc
