### ISSUE TITLE
[Android]Crash: StartActivity.java line 91

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1433]
**Describe the bug**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/771ea6f124b9f04b905296b2a66930f3?time=last-thirty-days&sessionEventKey=609A28E5028900013084519FCE92F765_1539366759583977314

**To Reproduce**
1.?????

**Expected behavior**
No crashes

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - Android Version: 9
 - App Version 2.15.0 (2531)

**Environment**
prod mainnet
**Additional context**

**Comment by biafra23** [comment]
The id in question `action_transactionsFragment_to_transactionDetailsFragment` doesn't exist in assetsFragment anymore. This crash cannot happen anymore.

**Comment by liliya-soroka** [comment]
Closed.
The issue will be reopened if the crash appears again in t he latest version
No crash in 2.16.0
