### ISSUE TITLE
Create How to Add Key screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1446]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:39:32 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1176'>gnosis/safe-ios/issues/1176</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

**Texts**

*   **Title**
    *   Add Owner Key 
*   Create New Owner Key
    *   Create a new key that you can use as owner of your Gnosis Safe
*   Import Existing Owner Key
    *   Import an existing owner key or a seed phrase

**Zeplin**

https://zpl.io/ag3M5KA 

**Tracking**

*   Just screen tracking: screen_owner_options

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2683
