### ISSUE TITLE
Create Owner Key Intro screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1447]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:39:53 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1177'>gnosis/safe-ios/issues/1177</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

**Elements:**

*   **Title: **Create Owner Key
*   **How does it work?**
    *   To use this app as an owner in the Gnosis Safe, you can create a key and add it as an owner of your Safe. When you tap Next, the app will create a new private key from a new unique seed phrase.
*   **How secure is that?**
    *   _(iOS)_ The owner key and the seed phrase are stored in the device's secure store - iOS Keychain.
    *   _(Android)_ The owner key and the seed phrase are securely stored.
    *   How is the private key stored on mobile?
        *   Link to [https://help.gnosis-safe.io/en/articles/4866738-how-are-private-keys-stored-on-gnosis-safe-mobile](https://help.gnosis-safe.io/en/articles/4866738-how-are-private-keys-stored-on-gnosis-safe-mobile) 
*   **How to export?**
    *   To export your owner key or seed phrase, navigate to the key details.
*   **Next **button
    *   When Next is pressed, the app creates a unique seed phrase and derives the key at index 0, and uses that to show the key address in the next screen.
    *   When the user goes back to this screen and presses “Next” again then the user must be able to see the same key again.

**Zeplin**

*   Links

**Tracking**

*   Screen id: screen_owner_generate_info

**Comment by liliya-soroka** [comment]
Reopened:
Can not test "
Next button
When Next is pressed, the app creates a unique seed phrase and derives the key at index 0, and uses that to show the key address in the next screen.
When the user goes back to this screen and presses “Next” again then the user must be able to see the same key again. "
as nothing happens on the Next link click on "Create new key intro" page

app version 2.16.0 -2683
Huawei P30 /10

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2695
