### ISSUE TITLE
Changes to Enter Key Name screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1448]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:04 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1178'>gnosis/safe-ios/issues/1178</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

*   **Back** button
    *   Goes back to the previous screen. When this screen is opened again, the same key address is displayed. To generate a new key, the user has to close this flow and start again.
*   **Save **button
    *   Disabled if the name is empty or whitespaces
    *   Enables when name is entered
    *   We need to also save that the private key was generated from that seed phrase in order to allow exporting of both later.
    *   **When pressed,** 
        *   will save the seed phrase securely and the private key
        *   Updates tracking user properties and triggers tracking events
        *   Closes the flow and opens the key details
        *   Shows snackbar
            *   The key successfully created. Add it to a Safe on desktop and then restart the mobile app.
    *   

**Zeplin**

*   Links

**Tracking**

*   Existing screen id: screen_owner_enter_name
*   Update user property: [num_keys_generated](https://github.com/gnosis/safe/wiki/Tracking#num_keys_generated)
*   Trigger: [user_key_generated](https://github.com/gnosis/safe/wiki/Tracking#user_key_generated)

**Comment by liliya-soroka** [comment]
Reopened because of the point:

When pressed,
- [ ] Closes the flow and opens the key details ( opened discussion in the https://docs.google.com/document/d/18NfOP4xuYnMJ3coWN2ngVwtfF7jn9ca7OfqG79p2L3Q/edit#heading=h.rtmjil967r5r )
- [ ] Shows snackbar:
" The key successfully created. Add it to a Safe on desktop and then restart the mobile app."

App version : 2.16.0 -2695

**Comment by elgatovital** [comment]
`Closes the flow and opens the key details`  will be implemented within own task (if needed)

**Comment by liliya-soroka** [comment]
separate issue is create for key details opening to fix it later

app version 2.16.0 -2734
