### ISSUE TITLE
Changes to Owner Keys screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1449]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:17 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1179'>gnosis/safe-ios/issues/1179</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

**Elements**

*   **Plus (+)** button
    *   Opens the **How To Add Key **screen
*   Tap on the key row
    *   Opens **Owner Key Details** screen
    *   Disable the current functionality of copy key address on tapping on the key

**Zeplin**

https://zpl.io/aR4BrBe

*   Links

**Tracking**

*   Existing screen id: screen_owner_list

**Comment by liliya-soroka** [comment]
Blocked in 2.16.0 -2683
Nothing is happening on the owner key click

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0  -2695
