### ISSUE TITLE
Owner Key Details screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1450]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:28 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1180'>gnosis/safe-ios/issues/1180</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

**Elements**

*   Title
    *   Owner Key
*   Identicon - of the key address
*   Key Name
*   **Edit Key Name** button
    *   Opens **Edit Key Name** screen
*   QR Code of the address
    *   Contents of the QR code is checksummed address string with 0x prefix
*   **Export **button
    *   If passcode option “Require for exporting keys” is set, request passcode first
    *   Opens **Export **screen
*   **Remove Owner Key **button
    *   Starts **Remove Key** flow (existing)

**Zeplin**

https://zpl.io/VQNg4ek

*   Links

**Tracking**

*   Screen id: screen_owner_details
*   When removing: trigger [user_key_deleted](https://github.com/gnosis/safe/wiki/Tracking#user_key_deleted)
    *   Update user prop [num_keys_imported](https://github.com/gnosis/safe/wiki/Tracking#num_keys_imported) or [num_keys_generated](https://github.com/gnosis/safe/wiki/Tracking#num_keys_generated), respectively

**Comment by liliya-soroka** [comment]
Verified ( except Export option - It will be tested in Export task)

app version 2.16.0 - 2695
