### ISSUE TITLE
Export Key screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1451]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:40 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1181'>gnosis/safe-ios/issues/1181</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

*   Title
    *   Export 
*   Segmented buttons
    *   **Seed Phrase**
        *   Shows the seed phrase with numbered words
        *   NO QR-code
    *   **Private Key**
        *   Shows the private key as a hexadecimal string
        *   QR code: content is the private key string
*   **Share **button
    *   Opens system “Share” sheet to share either seed phrase or a private key (whatever is currently selected
*   **Back** button
    *   Closes the flow and goes back to previous screen (key details)

**Zeplin**

https://zpl.io/VDgYQMg
https://zpl.io/2j3BdmA

*   Links

**Tracking**

*   Screen id when seed is active: screen_owner_export_seed
*   Screen id when private key is active: screen_owner_export_key

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 (450)

tracking will be checked separately for all tasks related to the "generate key" feature

**Comment by liliya-soroka** [comment]
Reopened:
Nothing happens on Export option click 

app version 2.16.0 -2695
Huawei P30/10

**Comment by elgatovital** [comment]
it wasn't even in qa yet :)

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2734
