### ISSUE TITLE
Changes to Edit Key Name screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1452]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:49 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1182'>gnosis/safe-ios/issues/1182</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

**Title:** Edit Key Name

Delete the “Remove owner key” button from this screen

**Zeplin**

*   Links

**Tracking**

*   Existing screen id: screen_owner_edit_name

**Comment by liliya-soroka** [comment]
Can not be tested in 2.16.0 - 2683 , as nothing happens on the owner key click on "owner keys" list
When will it be available for testing ?
@elgatovital

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2695
