### ISSUE TITLE
Changes to Passcode Settings screen

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1453]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-05-20 11:40:59 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1183'>gnosis/safe-ios/issues/1183</a>
**Original assignees:** 
**Status on 2021-05-20:** open
<hr>

*   Add new toggle “Require for exporting keys”
    *   When enabled, the passcode is asked to open **Export** screen from **Key Details**
    *   When disabled, the passcode is NOT asked to open **Export** screen from **Key Details**

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 - 2741rc
