### ISSUE TITLE
[Android] Enter touch id for the app screen blocks the device 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1462]
**Describe the bug**
Enter touch id for the app screen blocks the device. The user can not answer on called, cencel the screen, send the app to background and etc. The device is locked by the our biometric screen till the either valid fingerprint is used or the wrong is entered a few times

**To Reproduce**
1. Set up biometric option on
2. send the app to background
3. call the app from background
4.try to swipe the app to go to the another app without unlocking it 
5. call on messenger installed on the device
Current result: the user can not answer because the device is locked by the Enter biometric data gnosis multisig app screen 

**Expected behavior**
It should be possible to send app to background without unlocking it when the biometric option is used.It should not lock the user's device

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 -2674rc

**Environment**
rinkeby, staging 
**Additional context**

**Comment by biafra23** [comment]
This behavior seems to be device dependent. I have no problem on any of my devices to put the app into background when the fingerprint prompt is shown. What device are you using?

What about tapping on "Use passcode"? That should be the option to not use the fingerprint.

**Comment by liliya-soroka** [comment]
Verified in another apps, the same screen that locks the device is used
