### ISSUE TITLE
[Android] The "request on app start" is on by default on migration from the eldest versions without "request on app start"

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1465]
**Describe the bug**
The "request on app start" is on by default on migration from the eldest versions without "request on app start"

**To Reproduce**
1. Install the app version without "request on app start" option 2.15.0 and elder
2. set up passcode and add safes
2. Update to 2.16.0 or 2.17.0
Current result: the "request on app start" is on by default

**Expected behavior**
"request on app start" should by off by default when the option just appears in the app after updating to the latest version with set up passcode

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version  2.17.0

**Environment**

**Additional context**

**Comment by biafra23** [comment]
I can certainly change that. But didn't we decide to have request password on app start to be enabled after the update?

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 -2680rc
