### ISSUE TITLE
[Android] No prompt to activate biometric option after the passcode set up 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1466]
**Describe the bug**
No prompt to activate biometric option after the passcode set up after the clean app installation, so the user is not informed that there is such option in the app
The user is not informed that the biometric option is available after the passcode set up.
Note: by default the biometric option is off after passcode set up
**To Reproduce**
1. Uninstall the app 
2. Clean app instllation
3. Accept T&C-> allow tracking 
4. Set up passcode
Current result: the user is not asked about the biometric option enabling , as we have on ios 

**Expected behavior**
The user should be offered to enable biometric after the passcode set up - ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4dcecbf6-0fc6-46d2-8e8d-ce270e03c7b5) 
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1429

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 - 2560rc

**Environment**
prod , mainnet
**Additional context**

**Comment by biafra23** [comment]
Text for dialog to activate biometry whenever passcode has been activated:

Activate Biometry?

Would you like to enable login and signing with Biometrics?

Cancel | Enable

**Comment by liliya-soroka** [comment]
@biafra23 , is it possible to use the prompt if the fingerprint or face id is not set up on device?

**Comment by biafra23** [comment]
> @biafra23 , is it possible to use the prompt if the fingerprint or face id is not set up on device?

I can direct them to the enrollment. But when it is done they are not on the passcode settings screen. Because they never were there.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2840rc
