### ISSUE TITLE
[Android]not registered on mainnet Unstoppable domain is recognised in prod mainnet app

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1468]
**Describe the bug**
not registered on mainnet Unstoppable domain is recognised in prod mainnet app

**To Reproduce**
1. Run prod mainnet app
2. add safe using unstoppable domain
3. use name udtestdev-creek.crypto
Current result: The safe is recognised and can be added, but the domain is registered only on Rinkeby

**Expected behavior**
Only names allowed for mainnet should be recognised in prod mainnet app

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 -2680rc

**Environment**
prod , mainnet
**Additional context**

**Comment by tschubotz** [comment]
Marking as major since this could lead to someone using an address which doesn't exist on this network.

**Comment by liliya-soroka** [comment]
@biafra23 , the crash - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/0783ae2216fc04ab60d93ad1af7d3f6d?time=last-seven-days&sessionEventKey=60CB2958005400017C0B9F4D596575D4_1553160415159641327 may be related to it

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2816rc
