### ISSUE TITLE
[Android]The app is unlocked without passcode on second call from background if the biometric option is disabled by the system for some time

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1469]
**Describe the bug**
[Android]The app is unlocked without a passcode on the second call from the background if the biometric option is disabled by the system for some time
The system blocks the fingering option if the wrong fingerprint was used about 5 times

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up passcode with fingerprint in the app
2. Start the app
3. Use wrong fingerprint many times till this option is blocked by the system
4. Don't enter the passcode and send the app to the background
5. call the app from the background and don't enter the passcode
6. send the app to the background
7. call app from background 
Current result: The app is unlocked without a passcode or fingerprint. The app should be send to background while the fingerprint is locked by the system

**Expected behavior**
It should not be possible to use app without entering correct passcode or fingerprint if passcode is on

https://drive.google.com/file/d/1QqgZ3X4Q7o0pAvZwUKEnrM0NMwHoQQEM/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0-2680rc

**Environment**

**Additional context**

**Comment by biafra23** [comment]
Cannot reproduce this with my Pixel 3a (Android 12 beta) will try more phones.

**Comment by liliya-soroka** [comment]
Verified on Huawei P30
app version 2.16.0 -2734
