### ISSUE TITLE
Biometric dialog can be closed without keyboard opening

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#1470]
**Describe the bug**
When closing the biometric input dialog without pressing "use passcode" the keyboard is not opened and it is not possible to input the passcode

**To Reproduce**
1. Setup biometric unlock and set that it is used on app start
2. Open the app and close biometric input 
  * Press back
  * Press outside dialog

**Expected behavior**
The keyboard should be open when the biometric input is not visible anymore. And there should be an obvious way to open the keyboard if not (e.g. pressing the 6 passcode dots).

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - Android Version: 11
 - App Version: 2.16.0-2683

**Environment**
- Mainnet Production

**Additional context**
- The keyboard can be opened on the lock screen by pressing back which is unexpected, as I would expect that the app closes.

**Comment by biafra23** [comment]
@rmeissner Actually in this case the back button is the button to close the keyboard. I am not sure, we can prevent that. If it is on screen the triangle is directed downwards.  I will try to find a way to not close the keyboard on back.

**Comment by biafra23** [comment]
This SO question seems to have three different answers to intercept the close-soft-keyboard button: https://stackoverflow.com/questions/3940127/intercept-back-button-from-soft-keyboard

**Comment by liliya-soroka** [comment]
Verified
the link is added to open keyboard
app version 2.17.0 -2741rc
