### ISSUE TITLE
[Android] It's possible to remove owner key/safe from the app without passcode as dialog is displayed above passcode screen

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1475]
**Describe the bug**
If the user stops safe or key removing on the confirm dialog before the app was sent to background it's possible to confirm removing without passcode entering . As confirm dialog is displayed above the enter passcode screen

**To Reproduce**
1. Set up passcode on app start
2. Go to the safe settings or key details
3. Click remove safe/key ( don't confirm it and don't close confirm dialog)
4. send app to the background
5. call the app from the background
Current result: Confirm delete safe/key dialog is displayed above enter passcode screen and the safe/key is deleted if it's confirmed

**Expected behavior**
confirm dialog should be after the enter passcode screen 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/854e1875-5e40-4f20-beb3-f4877a9d2f7a)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.16.0 -2690

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
I would say it's major since funds aren't at risk, however definitely an inconvenient bug -> `minor`

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -3057
