### ISSUE TITLE
[Android] Generate key flow pages' titles are contains words started from the upper case

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1479]
**Describe the bug**
"Generate key" flow pages' titles contain words started from the upper case
But on android, all titles should contain only the first word started from the upper case.

**To Reproduce**
1. Go to app settings ->Owner keys
2. Click Add and check each page during "generate key" flow
Current result: Each word in the title are started from the upper-case

**Expected behavior**
Only the first word should start from the upper case

**Screenshots**

- [ ] ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f129bb8e-afeb-4242-af23-36bf615300ea)

- [ ] ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/107590aa-c467-4fff-9e67-e2467006eff9)

- [ ] ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/00ecc934-277b-46d5-9a9b-6fad8d71dc00)

- [ ] ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/80c51533-3a56-4830-b887-0feab260c0ad)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version:10
 - App Version 2.16.0 -2695

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
I mean this is not really mission critical, but sounds like a really easy thing to fix?
