### ISSUE TITLE
[Android] "Import" is used as the name for saving generated key on "Enter key name"

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1480]
**Describe the bug**
"Import" is used as the name for saving generated key on "Enter key name"

**To Reproduce**
1. Start generate key flow
2. Go to the "Enter key name" page
Current result: Import is used as name for the option to save generated key 

**Expected behavior**
rename "Import " to save only for the "Enter key name" for generate key 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8577c644-dff5-4358-91e4-26dbab73213c)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.16.0 -2695

**Environment**
staging, rinkeby
**Additional context**

**Comment by tschubotz** [comment]
marking a major since this is confusing and it's about keys, which people are probably more concerned about.

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 -2758rc
