### ISSUE TITLE
[Android] The passcode is disabled automatically if the all "use for " toggles are unselected except "request on export"

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1488]
**Describe the bug**
 The passcode is disabled automatically if the all "use for " toggles are unselected except "request on export". It's not possible to leave only "request on export" passcode
**To Reproduce**
1. Go to 'the passcode settings
2. set up passcode
3. unselect "request on app start" , "request on confirmation"
Current result: The passcode is disabled 
**Expected behavior**
Only if the all "use on" toggles are off the passcode should be disabled

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.16.0 -2734

**Environment**
staging, rinleby 
**Additional context**

**Comment by tschubotz** [comment]
This sounds like quite unexpected behavior -> major

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 - 2758rc
