### ISSUE TITLE
[Android]  First added safe does not receive notifications when the second safe with the same imported owner is added

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1489]
Bug description
 First added safe is not received notification if the second safe with the same imported owner is added

From Uxio:
@safe-android @safe-ios Are you sending always all the Safes you want to get notifications from when you send the creation request?

Steps To Reproduce

Add safe = 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
Import owner ( contact Liliya for PK)
create tx and receive notification for the safe in step 1 ( make sure that the push notifications are received
Add safe = 0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD
Send the tx from the first safe to the second safe /or send ERC20 to the first safe
Current result: Only notifications for the second safe are received
The user has not received notifications for the first safe

Expected Result
The user should receive notification for both safe even if the same owner is used in both safes

Device & App version

Device/OS: iPhone 11/14.3
App version: 2.16.0
Environment
prod rinkeby
Additional info
(Optional)

**Comment by liliya-soroka** [comment]
the same issue was on ios ( client side ) - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1203

**Comment by tschubotz** [comment]
marking this as major also since this use cases seems quite likely and pushes are one of the nice features currently on the mobile app compared to web.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2816rc
