### ISSUE TITLE
[Android] The app is crashing if cancel Biometric-enabling is selected in prompt after calling the app from background

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1490]
**Describe the bug**
The app is crashed if cancel Biometric enabling is selected in prompt after calling the app from background

**To Reproduce**
Precondition:
the fingerprint is set up on device
the passcode is disabled in app

1. Go to app settings
2. enable passcode
3. set up passcode
4. send app to the background when the Biometric activation prompt is displayed
5. call the app from background and click "Cancel"
Current result: the app is crashed - https://console.firebase.google.com/u/0/project/safe-firebase-staging/crashlytics/app/android:io.gnosis.safe.internal/issues/afab68100d7f7399b3ff369aa6b4d10a?time=last-seven-days&sessionEventKey=60BE315B00640001524DD44C47C3419F_1549514436943634791

**Expected behavior**
The app should not be crashed

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 - 2741rc

**Environment**
staging, rinkeby 
**Additional context**

**Comment by tschubotz** [comment]
marking as minor since this sounds like an edge case, however since it's a bug, certainly worth to fix.

**Comment by biafra23** [comment]
@tschubotz Would it be ok to dismiss the dialog (an not activate biometrics) when the app goes to background?

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 ( 3047)
