### ISSUE TITLE
Show contracts v1.3.0 as "up to date" in Safe Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1492]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-06-07 10:08:50 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1223'>gnosis/safe-ios/issues/1223</a>
**Original assignees:** 
**Status on 2021-06-08:** open
<hr>

- Show the contract version "1.3.0 up to date"
- Note: 1.1.1 and 1.2.0 versions should still be shown as "up to date".
- The minimum supported contract version is present in the server response for the safe info.
- All supported versions: from 1.0.0 to 1.3.0 inclusive
- Disallow adding safe outside this version range

**Comment by elgatovital** [comment]
where do we get GnosisSafeL2 addresses from?

**Comment by biafra23** [comment]
See: https://github.com/gnosis/safe-client-gateway/blob/interstellar/src/routes/about.rs#L35

For the endpoint and format for master copies per chain
