### ISSUE TITLE
Implement the transaction hash algorithm for the contracts v1.3.0

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1493]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-06-07 10:17:06 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1225'>gnosis/safe-ios/issues/1225</a>
**Original assignees:** 
**Status on 2021-06-08:** open
<hr>

This task is only about implementing the new v1.3.0 algorithm, it is not about integrating it into the transaction signing.

*   Changes to the transaction hash computation [ #170](https://github.com/gnosis/safe-contracts/issues/170)
*   **chainId** is added to DOMAIN_SEPARATOR_TYPEHASH
    *   [https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L38](https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L38) 
    *   [https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L350](https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L350)

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -3057
