### ISSUE TITLE
Change naming from Safe Multisig to Gnosis Safe

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1495]
**Issue  by:** <a href='https://github.com/DmitryBespalov'>DmitryBespalov</a>
**Original date:** 2021-06-07 10:25:57 UTC
**Originally opened as:** <a href='https://github.com/gnosis/safe-ios/issues/1228'>gnosis/safe-ios/issues/1228</a>
**Original assignees:** 
**Status on 2021-06-08:** open
<hr>

- App Store page
  - App Name
  - App Description
- Splash screen logo
- No safes loaded screens
- Enter safe address screen
- Enter safe name screen
- Safe loaded success screen
- Email feedback body template
- App name on the device home screen
- Face ID usage description

**Comment by elgatovital** [comment]
![gnosis_safe.svg](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/9c0ded67-8268-4a5d-8c5e-4e8c239ea6e7)

**Comment by elgatovital** [comment]
![gnosis_safe.svg](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/54ded7ca-3741-46fc-aaaf-4b37f0b5133d)

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 -2801
