### ISSUE TITLE
[Android]The user is asked to enter passcode on tx confirmation even when "request on confirmation" is off

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1497]
**Describe the bug**
The user is asked to enter passcode on tx confirmation even when "request on confirmation" is off

**To Reproduce**
1. Go to passcode settings
2. set up passcode and unselect "request on confirmation"
3. go to the transactions and try to confirm tx in the Queue
Current result: Tje user is asked to enter passcode even if the "request on confirmation" toggle is switched off

**Expected behavior**
The user should not be asked to enter passcode if the "request on confirmation" is off

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 - 2741rc

**Environment**
prod , rinkeby
**Additional context**

**Comment by tschubotz** [comment]
not a blocker but for sure not as intended -> rating this as `major` so we fix it soon.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2816rc
