### ISSUE TITLE
[Android]Crash : ConnectivityInfoProvider.java line 52

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1507]
**Describe the bug**
ConnectivityInfoProvider.java line 52 - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/dd0d2f06d4b8af16dffb5581fbeb59de?time=last-ninety-days&sessionEventKey=60C267A70361000149C5AB73F0B4A7F6_1550694033570865294

Caused by java.lang.SecurityException
Package android does not belong to 10466
io.gnosis.safe.helpers.ConnectivityInfoProvider.register

**To Reproduce**
???

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 FE
 - Android Version: 11
 - App Version 2.16.0 (2632) ( only for now)

**Environment**
prod , mainnet 
**Additional context**

**Comment by DmitryBespalov** [comment]
Closing until more people are affected
