### ISSUE TITLE
[Android]Show keyboard link doesn't work if "enter passcode" is called from the passcode settings page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1508]
**Describe the bug**
Show keyboard link doesn't work if "enter passcode" is colled from the passcode settings page. Tru change any passcode settings option 

**To Reproduce**
1. Go to the passcode settings page with set up passcode
2. switch off any toggle or click change passcode
3. dismiss keyboard
4. click "Show keyboard" link on enter passcode screen
Current result: Nothing happens

**Expected behavior**
The keyboard should appear

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 -2764rc

**Environment**
prod , mainnet
**Additional context**

**Comment by tschubotz** [comment]
marking as major since there is not way to enter the passcode in this case anymore.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2816rc
