### ISSUE TITLE
[Android] App crashed on Export unlock with biometric 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1519]
**Describe the bug**
App crashed on Export unlock with biometric 

**To Reproduce**
1. Install 2.17.0 
2. skip passcode set up
3. Add safe without imported key
4. Update app to the 2.17.0 ( 2787)
5. import owner key and set up passcode with biometric 
6> go to the owner key details page and click "Export"
Current result: The app is closed

**Expected behavior**
The export details should be opened

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.17.0 (2787)

**Environment**
prod, rinkeby
**Additional context**

**Comment by biafra23** [comment]
I can reproduce the crash

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 -2799
