### ISSUE TITLE
[Android] Use local owner & safe names on multisend action screens

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#1525]
The screens affected:
    MultiSend Action List
    MultiSend Transaction Action Details
    Transaction Action Details

Use standard logic to display local owner keys or safe name.

**Comment by liliya-soroka** [comment]
Reopened:
owner name is not used on actions list page
safe = liltestsafe.eth
rinkeby
tx with nonce=611
owner = 0xF2CeA96575d6b10f51d9aF3b10e3e4E5738aa6bd

app version 2.18.0 - 2816rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2833rc
