### ISSUE TITLE
[Android] Fetch networks info and store it

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1530]
The list of supported networks is fetched on the app start.

We do not implement pagination here. We assume that we fetch all networks in one call.

- [ ] Update network information in a database **only** for safes that we have.
- [ ] If we have a safe but safe's network was not returned in the list of supported networks, we rely on cached data in this iteration
- [ ] Use https://safe-client.staging.gnosisdev.com/v1/chains for staging

**QA items**
- not verifiable

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-android/1532  - the netwrok collor will be available for testing when "Fetch networks info and store it" task is ready

**Comment by liliya-soroka** [comment]
The colour and mane are verified
closed 
The task will be tested fully during the functional testing for Multinetwork support
