### ISSUE TITLE
[Android] Make migration for mainnet existing safes

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1531]
- Old mainnet safes are linked to Mainnet network
- The database should already have one Mainnet network entry

**QA**
- The app should not break on version update (check the use case with when no internet on first opening of the app after updated)
- The old safes should stay there

**Comment by liliya-soroka** [comment]
Reopened:
the staging mainnet app doesn't work. The error is displayed on loading safe balance /transactions/safe settings
Ribbon doesn't contain the network name 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/76134b1d-c766-4176-9ea1-4a4a7d436838)

**Comment by liliya-soroka** [comment]
Reopened:
1. Install the latest released app version  (2.18.0  release)
2. add many safes and import owner key 
3. update app to the latest multinetwork version
4. start the app
Current result: All safes are removed , owner is left in the app

app version 2.18.0 - 2966

**Comment by liliya-soroka** [comment]
Reopened:
Description: only one safe is migrated

1. Install the latest released app version (2.18.0 release)
2. add many safes and import owner key
3. update app to the latest multinetwork version
4. start the app
Current result: Only last added safe was imported

app version 2.18.0 - 2977

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 - 2983
