### ISSUE TITLE
[Android] Add ribbon below the safe info header on all pages

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1532]
- Assets, Transactions, Settings pages

- Add network indicator for Safe info / Share safe screen

- Don't show ribbon when no safes loaded

**QA**
All pages where the safe header presents (safe name + address + safe switcher button) should have a ribbon with network name.
- [x] Assets tab
- [x] Transactions tab
- [x] Settings tab

Network name and network colour are correct

**Comment by liliya-soroka** [comment]
@elgatovital , is transaction details the part of this task ?

Current result: No network ribbon on transaction details 
app version 2.18.0 -2831

**Comment by liliya-soroka** [comment]
Reopened:
the same colour is used for Rinkeby and mainnet 

app version 2.18.0 -2831
