### ISSUE TITLE
[Android] Add ribbon to transaction details and all nested details screens

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1533]
Transaction details screen should have a ribbon
- [x] opened from tx list
- [x] opened from a push notification

*Nested tx details screens*
- [x] multisend actions list 
- [x] action details
- [x] advanced tx details
- [x] multisend decoded transactions

The ribbon should not be scrollable. It should be stick to the header.

**QA**
See above. Please assure that we did not forget any other tx details internal page.

**Comment by biafra23** [comment]
Ribbon is missing on  `advanced tx details`

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2932
