### ISSUE TITLE
[Android] Adjust app/safe settings

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1535]
- [x] Remove network from app settings

- [x] Adjust advanced safe settings
-- Remove ENS resolver address and endpoints section (will be included in v2 on a different screen)

**QA**
Check that mentioned above info is removed

**Comment by liliya-soroka** [comment]
Verified
app bersion 2.18.0 -2831

**Comment by liliya-soroka** [comment]
Verified
the listed above are done 
app version 2852
