### ISSUE TITLE
[Android] Switch safes

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1536]
Zeplin link: https://zpl.io/29GL55A 

- [ ] Ordering logic:
- selected safe always on top
- other safes are ordered by:
-- network ordering from the backend
-- safe added date desc

**QA**
check look and feel and ordering logic mentioned

**Comment by liliya-soroka** [comment]
crash on safe switching openiong for staging mainnet app was reported separately 

The task has limitation for testing right now, as the app may contain only one network now. It's not possible to test the networks order and the list view with a few networks
It will be tested later during functional testing for the full multinetwork feature

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 - 2880
