### ISSUE TITLE
[Android] Select network when loading safe

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1537]
The networks list logic is similar to transactions list logic:
- [x] proper errors handling
- [x] loading indicator
- [x] pull to refresh
- [x] empty list placeholder
- [ ] pagination

Header should be scrollable with the list.
We do not use cached networks data here (or from our database)

- [ ] We update cached data in the database only for the network we select and at the moment when we actually add the safe. There should not be networks without safes.

**QA**
Question: is it possible to check pagination? - probably some custom networks list will be needed (mitmproxy)

**Comment by liliya-soroka** [comment]
to test it fully , I need rinkeby and mainnet in one app at the same time

**Comment by liliya-soroka** [comment]
Verified
the pagination will be checked separately

app version 2.18.0 -2966
