### ISSUE TITLE
[Android] Add safe screens (enter address/name/ENS/UD)

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1538]
We display ribbon for:
- [x] Enter address screen
- [x] Enter ENS name screen
- [x] Enter UD name screen
- [ ] We show ENS/UD option based on network info
- [x] For QR code scanner we DO NOT display a ribbon
- [x] We store safe with related network info after finishing adding it

**QA**
all the mentioned above

**Comment by biafra23** [comment]
Regarding UD. I would only enable it for Rinkeby and Mainnet for now. 
I talked to JohnnyJumper from UD on Discord and he assumes only the follwoing networks are supported ATM:
From: com.unstoppabledomains.config.network.model.Network 
    MAINNET(1, "mainnet"),
    ROPSTEN(3, "ropsten"),
    RINKEBY(4, "rinkeby"),
    GOERLI(5, "goerli"),
    KOVAN(42, "kovan");

**Comment by biafra23** [comment]
>  We show ENS/UD option based on network info

That will not be possible for now. See:

https://github.com/gnosis/safe-config-service/issues/119
And
https://github.com/gnosis/safe-config-service/issues/119

**Comment by fmrsabino** [comment]
> > We show ENS/UD option based on network info
> 
> That will not be possible for now. See:
> 
> [gnosis/safe-config-service#119](https://github.com/gnosis/safe-config-service/issues/119)
> And
> [gnosis/safe-config-service#119](https://github.com/gnosis/safe-config-service/issues/119)

Would something like:

```javascript
{
  "ens": {
    "android": {
      "chainName": <string>
    }
  } 
}
```

work? I don't think tying the chain name that we already provide (which is not standard) to the framework is robust enough. To make it work with the current Android framework, we can return the chain name as it is expected by it.

**Comment by biafra23** [comment]
@fmrsabino We can select the network by chainId. No need to send the name. https://github.com/unstoppabledomains/resolution-java/blob/master/src/main/java/com/unstoppabledomains/config/network/model/Network.java#L18

**Comment by fmrsabino** [comment]
So only `chainId` is required for ENS on Android correct? Can you comment on the Android requirements under https://github.com/gnosis/safe-config-service/issues/119 ?

Thanks!

**Comment by biafra23** [comment]
@elgatovital I'd like to move ` We show ENS/UD option based on network info` to a separate task.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2905
