### ISSUE TITLE
[Android] Reject tx doesn't appear if the tx is rejected without passcode confirmation 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1545]
**Describe the bug**
Reject tx doesn't appear if the tx is rejected without passcode confirmation 

**To Reproduce**
Precondition:
safe with 3 of N policy
import one of the owners to the mobile app

1. create tx as no-imported owner
2. go to the mobile app and activate passcode+biometric with  "request on confirmation" off
3. reject the tx as an imported owner
Current result: The user is located on the reject info screen with disabled "reject tx" button

4. go back to the transactions list
Current result: No reject transaction

**Expected behavior**
It should be possible to reject the transaction as imported owner with disabled request on confirmation option 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1d8642a9-17e8-44cd-81c6-1d9814468d7f)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 2.18.0 -2833rc

**Environment**
prod, rinkeby 
**Additional context**

**Comment by biafra23** [comment]
I can reproduce it. Should be easy to fix.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2840rc
