### ISSUE TITLE
Add dynamic ENS support

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1557]
During Add safe flow
- Use ENS resolver address when selected chain resolver address is known

**Comment by MouazAlzahabi** [comment]
[Backend ticket](https://github.com/gnosis/safe-config-service/issues/119#issuecomment-872103898)

**Comment by biafra23** [comment]
Backend pull request: https://github.com/gnosis/safe-config-service/pull/143

**Comment by liliya-soroka** [comment]
Reopened:
Add safe using ENS works on mainnet( alice.eth) but doesn't work on Rinkeby ( liltestsafe.eth) 

app: staging mainnet app
app version : 2.18.0-2966

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -2983
