### ISSUE TITLE
Migrate chainId from Int to BigInteger in legacy code and libraries

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1575]
Find all occurrences where chainId is and Int and migrate them to BigInteger.

For example:  pm.gnosis.models.Transaction in https://github.com/gnosis/svalinn-kotlin/blob/master/models/src/main/java/pm/gnosis/models/Transaction.kt#L13

Related to #1576

**Comment by DmitryBespalov** [comment]
done already
