### ISSUE TITLE
[Android] Adjust tracking for multiple networks

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1582]
### Add `chain_id` param to `screen_` events

https://github.com/gnosis/safe/wiki/Tracking#screen-view-tracking

- `none` if the chain id is not known yet
- Chain identifier (e.g. `"1"` for mainnet) if it is already known:
  - By default take it from the currently selected safe chain
  - In the flow of adding a new safe specify it as the `future safe` chain id:
    - `screen_safe_add_address`
    - `screen_safe_add_ens`
    - `screen_safe_add_ud`
    - `screen_camera`
    - `screen_safe_add_name`

### Add `user_safe_added` and `user_safe_removed` events

- https://github.com/gnosis/safe/wiki/Tracking#user_safe_added
- https://github.com/gnosis/safe/wiki/Tracking#user_safe_removed

### Add `chain_id` param for the following events

- `user_transaction_confirmed`
- `user_transaction_rejected`

**Comment by liliya-soroka** [comment]
Verified
a new issue with missed tracking was created - https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-android/1620

app version 3.0.0 - 3057rc
