### ISSUE TITLE
[Android] Adjust rpcUrl parcing

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#1591]
https://github.com/gnosis/safe-config-service/issues/171

```javascript
GET /api/v1/chains/<chain-id>
{
  ...
  "rpcUri": {
    "authentication": <API_KEY_PATH | NO_AUTHENTICATION>
    "value": <url> 
  }
}
```

We try to use rpcUri as is (without appending project id or another secret key) for unknown types

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 - 3047
