### ISSUE TITLE
Splash screen UI is broken on dark mode

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#1609]
**Describe the bug**
Splash screen UI is broken on dark mode

**To Reproduce**
1. Set phone to dark mode
2. Start up app
-> Safe logo is broken

**Expected behavior**
Nice Gnosis Safe logo is visible

**Screenshots**
![signal-2021-08-03-105145](https://user-images.githubusercontent.com/1380529/128140791-b1fa19b0-817c-47c6-ae29-d14b0e6ccc40.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: Android 11
 - App Version: 2.19.0-3047rc-internal

**Environment**

any

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -3057
