### ISSUE TITLE
Cannot load tx details for module txs

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#1618]
**Describe the bug**
Cannot load tx details for module txs

**To Reproduce**

1. Add the Safe at `0xaE3c91c89153DEaC332Ab7BBd167164978638c30`
2. Open tx history
3. Open the tx that sent out 0.001 WBTC just after above the tx with nonce 271
-> An error occured

**Expected behavior**
tx details load

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: Android 11
 - App Version: 2.18.0-3057-internal

**Environment**
staging, rinkeby

**Additional context**

the tx is a module tx

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0 - 3072
