### ISSUE TITLE
[Android] Eth icon is used instead of native currency logo on the tx details

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1623]
**Describe the bug**
Eth icon is used instead of native currency logo on the tx details

**To Reproduce**
1. add safe = 0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf on the xDai network on prod
2. go to the history and open incoming +5xdai tx
Current result: xDai has Eth icon on the tx details

**Expected behavior**
The native currency logo should be used - nhttps://safe-client.gnosis.io/v1/chains/100/

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/17274b00-cab7-49e5-8e18-97160f6f4804)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/26497637-aed5-41e8-938e-45633077a907)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - Android Version: [e.g. Android 9]
 - App Version [e.g. 1.0.1]

**Environment**

**Additional context**

**Comment by elgatovital** [comment]
request: 
https://safe-client.gnosis.io/v1/chains/100/transactions/ethereum_0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf_0xf2b6b319786670e3084e866e8b26f90a3df74a10975374d30408a4c9a471eca0_0x50cde0408433f069
```json
{
  "executedAt": 1602852525000,
  "txStatus": "SUCCESS",
  "txInfo": {
    "type": "Transfer",
    "sender": {
      "value": "0x8ed44000983B5789798B43AF9d8d9C1e1e2093D0"
    },
    "recipient": {
      "value": "0x82FC6069FB9290F98c6ae02b6cfb7B6aB0ab97bf"
    },
    "direction": "INCOMING",
    "transferInfo": {
      "type": "NATIVE_COIN",
      "value": "5000000000000000000"
    }
  },
  "txData": null,
  "detailedExecutionInfo": null,
  "txHash": "0xf2b6b319786670e3084e866e8b26f90a3df74a10975374d30408a4c9a471eca0"
}
```

`logoUri` is missing in transferInfo

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0  - 3083
