### ISSUE TITLE
[Android] Owner name is not displayed in header of safe settings txs

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1625]
**Describe the bug**
Owner name is not displayed in header of safe settings txs

**To Reproduce**
1. add safe and import key
2. add imported key as a owner of the safe
3. check "addowner"tx or remove owner tx
Current result: The name of added in the app owner is not displayed in the header of the safe settings tx

**Expected behavior**
The imported/generated owner name should be displayed in the header of "add/remove/swap" settings txs

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6bc26838-cec1-45da-9e45-e2013ee6ea82)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/86cb3bf7-1779-467f-9226-9c6641018947)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/52ff7400-3a25-4a84-8134-041105156a6e)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - Android Version: [e.g. Android 9]
 - App Version [e.g. 1.0.1]

**Environment**

**Additional context**

**Comment by elgatovital** [comment]
duplicate #1406
