### ISSUE TITLE
[Android] Ledger nano X is not found on Huawei P30

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1694]
**Describe the bug**
Ledger nano X is not found on Huawei P30

**To Reproduce**
1. Go to owners
2. Click add new owner-> Connect Ledger nano x
3. all required steps are done: bluethoot is on on both devices, Eth app is running
4. Confirm location request when the app is in use

Current result: Ledger nano is not found by the app, but if Bluetooth settings is opened on mobile devise Ledger nano X is displayed in the fount but not paired devices

**Expected behavior** The Ledger Nano X should be found on the Huawei devices

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 3.1.0 -3285

**Environment**
staging
**Additional context**

**Comment by liliya-soroka** [comment]
on Huawei P20  to find the device I need to refresh the page a few times and to connect the app should be restarted a few times: for some reason, the found device record is not clickable

**Comment by biafra23** [comment]
This is no Huawei P30 specific problem at all. The reason we cannot fin the ledger (or any BLE device) is that location services need to be enabled to receive BLE scan results in certain android versions. 

We need to check whether location services are enabled and tell the user to switch them on, if they are not.

**Comment by biafra23** [comment]
Maybe we can use the following to get around the need for the location permission and maybe also the location service to be running on Android 12 and future versions:  
https://developer.android.com/about/versions/12/features/bluetooth-permissions#not-derive-physical-location

**Comment by liliya-soroka** [comment]
Verified
the info about the location was added to the error text 

app version 3.1.0 -3310rc
