### ISSUE TITLE
[Android] Cancel tx signing in the app if it was cancelled on Ledger 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1696]
**Describe the bug**
Cancel tx signing in the app if it was cancelled on Ledger 

**To Reproduce**
1. Ledger nano x is added as an owner and connected to the app
2. Select Ledger Nano X for tx confirmation in the app
3. but cancel sign message on Ledger nano X 

Current result: The process is not cancelled in the mobile app

**Expected behavior**
Cancel the process in the mobile app if it was cancelled on the ledger

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 10
 - Android Version: 11
 - App Version 3.1.0 -3285

**Environment**
staging
**Additional context**

**Comment by elgatovital** [comment]
the sign overlay is closed if canceled on ledger - same behavior as in ios as I was told. I it expected to cancel the whole flow and go back to tx details?

**Comment by liliya-soroka** [comment]
Verified
app version  3.2.0 -3396rc
