### ISSUE TITLE
Passcode necessary when unlocking with fingerprint after putting app to background

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#1730]
### Expected behavior
1. Activate passcode amd biometrics for app opening
2. Send app to background
3. Recall app from back ground
4. send it to background again
5. Recall app from back ground
6. unlock with fingerprint

 -> App should be unlocked
 
### Actual behavior
-> App still asks for pincode

### Steps to reproduce the behavior

See above

### Additional information

- Device: Pixel 3a
- Android OS version: 12
- Safe app version: 3.2.0-3391rc

**Comment by DmitryBespalov** [comment]
@elgatovital if it goes into 3.2.0 release, could you please add the issue in ZenHub to the "Android 3.2.0" release? 🙏

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 -3396rc
