### ISSUE TITLE
PIN ignored when app is opened from push

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#1735]
**Describe the bug**
When the app is not in the recents and is opened from a push, then the pin is not requested.

**To Reproduce**
1. Add `0x208F8672491e86021c2e7a5cc55238a85Ff43482` on `rinkeby`
2. Remove app from recents (it is also possible to "force stop" it in the settings)
3. Send any asset to `0x208F8672491e86021c2e7a5cc55238a85Ff43482`
4. Click push notification

**Expected behavior**
App should request PIN before showing any information

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - Android Version: Android 11
 - App Version: 3.2.0-3391rc

**Environment
Production

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 -3396rc
