### ISSUE TITLE
[Android] Signing doesn't work if the passcode was disabled

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#1743]
**Describe the bug**
Signing doesn't work if the passcode was disabled

**To Reproduce**
0. Remove all previous app data
1. Add safe , import owners keys and enable passcode
2. Disable passcode
3. Confirm or reject tx
Current result: the tx is confirmed or rejected

4. Try to confirm or reject the next txn
Current result: Nothing happens

5. restart the app
6. try to confirm tx again
Current result: Nothing happens

**Expected behavior**
Passcode disabling should not lock tx confirmation/rejection

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 3.2.0 -3369rc

**Environment**
prod, rinkeby
**Additional context**

**Comment by biafra23** [comment]
Looks like the key is still encrypted after the passcode has been removed. 
What we need to do is: 
When the passcode is disabled for signing (or export?) the key needs to be decrypted. So it can be used without the passcode.

**Comment by biafra23** [comment]
I could reproduce the above behaviour. 

When I re-enable the passcode I can again sign txs.

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 -3399rc
