### ISSUE TITLE
[Android] Add icons to menu items in app settings

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1749]
Related to [safe #522](https://github.com/gnosis/safe/issues/522

### Summary
As a part of the goal is to make Intercom buiit-in chat easily discoverable implementing icons to emphasise setting's functionality can help to achieve this goal.

### Requirements
Add a unique icon to the following menu items:

- Owner keys

- Address book

- Passcode

- Fiat currency

- Appearance

- Chat with us

- Get support

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/a870b7c4-fa43-49d9-a167-16118b8441fa)

New icons were added to the library: icon-chain, icon-appearance, icon-experimental, icon-key, icon-desktop

### Design
[Figma](https://www.figma.com/file/JrFUulz4n8Gb8Ayy3UEGhU/Intercom-implementation?node-id=0%3A277)

**Comment by elgatovital** [comment]
- Chat with us will be enabled in a later task after Intercom integration

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0-3423rc
