### ISSUE TITLE
[Android] Intercom: Configure inbox

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1750]
Figure out if it is possible to configure a separate inbox for Mobile messages. It is better to indicate that a user is coming from Mobile for better support.

- [ ] Configure inbox
- [ ] Present for the team how to word with mobile requests
- [ ] Present for `serve.eth` how to deal with Mobile requests

**Comment by DmitryBespalov** [comment]
Nothing to do, closing

**Comment by elgatovital** [comment]
no work item
