### ISSUE TITLE
[Intercom] Handle incoming messages

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1752]
- [x] Subscribe to Intercom notifications
- [x] Display a ‘badge’ for unread messages
* Settings tab
* Settings → Chat with us
- [x] Hide `badge` when Intercom is opened
- [x] Disable default chat overlay

- [x] Only open Intercom window after passcode is unlocked
- [x] Make sure that the Intercom can be opened after minimizing and opening the app again

### Links
[Message indicator](https://www.figma.com/file/JrFUulz4n8Gb8Ayy3UEGhU/Intercom-implementation?node-id=10%3A456)

**Comment by liliya-soroka** [comment]
@elgatovital , 
on staging "chat with us" doesn't work
on prod push is not enabled
blocked for testing for now
in 3.4.0 -3423rc

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3428rc
