### ISSUE TITLE
[Intercom] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1753]
Implement tracking. Add tracking events to the [tracking document](https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=0).

- [x] Track entering the chat with `user_settings_open_intercom`

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 -3423rc
