### ISSUE TITLE
[Intercom] Push Notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1754]
Implement push notifications for incoming Intercom messages when the App is closed or in the background.

- [x] Display incoming messages
- [x] Opening the push message should open App and show Intercom chat screen in a popover
- [x] Create separate notification group for Intercom

**Comment by biafra23** [comment]
Here is a list of situations we faced problems with Intercom on iOS:
- Opening from background
  - Via Push notification
  - From Home screen
  - App lock activated
  - App lock deactivated
- Opening after killing the app
  - Via Push notification
  - From Home screen
  - App lock activated
  - App lock deactivated

**Comment by elgatovital** [comment]
I would keep the default Intercom notification icon for now

**Comment by DmitryBespalov** [comment]
ok, then I'll move it to another issue as a new requirement for later.

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0-3428rc
