### ISSUE TITLE
[Intercom] find a way to display 'safe' icon for Intercom notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#1759]
- [ ] Reuse notification icon as for other notifications

Notes:
>  Because Intercom android sdk has closed api there is no direct way to adjust naming/structure of those channels.
> Same goes for the format of push notification itself

See more in the description of PR https://github.com/gnosis/safe-android/issues/1754

**Comment by elgatovital** [comment]
it can be done by adding an image named intercom_push_icon.png
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/15b397cd-985d-42ab-be57-fa054b94c8f5)
In my opinion default icon is totally fine though and I propose to close this ticket as this effort is not worth the resulting value.

**Comment by DmitryBespalov** [comment]
closing as won't fix because the icons are good enough.
