### ISSUE TITLE
UX: Export key without the password

### ISSUE THREAD

**Issue by ligi** [gnosis/safe-android#218]
First of all - congratulations to the release. Just had the chance to try it out yesterday - and really like what I saw and was able to make a transaction without any problem! Big up @rmeissner , @fmrsabino and the rest - good job!!
Now I have a small UX problem: I forgot the password I was using yesterday. and there is no option to dump the key so I could access the account again when I remember the password again (I think this will happen as soon as I see the password constraint list again)
The password constraints where also a bit disappointing to me - I really do not like these things and have to reference XKCD here 

![image](https://user-images.githubusercontent.com/111600/43600419-d2a441b4-968a-11e8-994f-9e88b4697817.png)

anyway - this is complaining on a high comfort level - just thought I dump this here so you have a data-point for potential changes.

**Comment by rmeissner** [comment]
Very long time without a response from our side :P 

We will probably change the criteria for the password, but we will not make it possible to export the private key, since our current philosophy is to not expose the private key used by the app in any case.
