### ISSUE TITLE
RxAndroid: explore impact/improvements with the new async messaging API

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-android#225]
RxAndroid 2.1.0 opens up a new API with async messaging. It'd be great to check the impact it has in the app.

**Comment by rmeissner** [comment]
more info at: https://medium.com/@sweers/rxandroids-new-async-api-4ab5b3ad3e93

**Comment by rmeissner** [comment]
@elgatovital We could check this out and if it is an easy change we could enable it

**Comment by elgatovital** [comment]
App was profiled during simple transaction execution. 
async = false
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/3b99bc01-e9e4-471e-a33e-966442d58d4a)

async = true
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/c4cb2945-fc1a-4707-918c-dc858e99f2c3)
