### ISSUE TITLE
Error when executing multiple transactions

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#245]
**Describe the bug**
When I use https://rinkeby.slow.trade, I have to sign multiple txs. I get an error the first time I try to do tx no 2 and 3

**To Reproduce**
1. I have a Safe installed an a Chrome extension connected
2. Go to https://rinkeby.slow.trade
3. Trade something
4. Confirm tx1
5. Trigger tx no2 (the one where you approve)
6. I get the push on the phone
7. I tap "Confirm"
8. I use fingerprint to submit
💥 An error occurred. (Also on retrying multiple times)
9. I close the tx.
10. I resend the push from the extension
11. Now I can submit successfully.

**Expected behavior**
No erroir

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Gnosis MotoG
 - Android Version: 7.1.1
 - App Version: 0.6.3-8-g7e...internal

- Chrome extension version: 0.4.0 (internal/red)

**Additional context**
-

**Comment by tschubotz** [comment]
@germartinez Could be that the Chrome extension doesn't increase the nonce properly in that case. Could that be?

**Comment by tschubotz** [comment]
Even after the release today, the error persists. Also, the dApps think that the transaction was cancelled. See this screencast: https://drive.google.com/file/d/1mXF6XN_Zyf1U5Dlj77JB9A8Wu8NWVaew/view?usp=sharing

**Comment by fmrsabino** [comment]
After discussing with @rmeissner and @denisgranha and doing some additional testing this seems to be an issue with the Browser Extension.

To reproduce the issue you should do the transactions in a way that they might be pending in some nodes and not yet detected on some other nodes. Then you might get the same nonce for 2 different transactions done in succession which is incorrect and the transaction would then fail.

The issue can be avoided for now if we wait for the block to be mined.

One of the suggested approaches is to add a cache for the nonce in the chrome extension and use it.
@germartinez

**Comment by rmeissner** [comment]
I would not wait until the transaction is mined. I talked about the topic of the nonce also with @tschubotz concerning a different topic and I think it would make sense if the `estimate` endpoint of the relay-service returns the nonce of the contract

**Comment by Uxio0** [comment]
Yes, I think it makes sense. It's also really easy to implement

**Comment by denisgranha** [comment]
Yeah seems like an elegant option

**Comment by Uxio0** [comment]
@fmrsabino @rmeissner  It's already implemented in the relay

**Comment by germartinez** [comment]
@Uxio0 Which enviroment?

**Comment by Uxio0** [comment]
DEV
