### ISSUE TITLE
Use adaptive app icons

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#246]
**Is your feature request related to a problem? Please describe.**
We currently have a circle icon for our app. On Samsung phones, more square-ish icons are used. The Gnosis Safe icon looks ugly on them.

**Describe the solution you'd like**
Properly add support for them so the icon is filled up with white.

**Describe alternatives you've considered**
Don't use Samsung phones ;)

**Additional context**
![screenshot_20180724-094741_samsung experience home](https://user-images.githubusercontent.com/1380529/46740461-2b1f3080-cca3-11e8-8651-b2ea8206cb2a.jpg)

**Comment by rmeissner** [comment]
More info how to do this: https://medium.com/google-design/designing-adaptive-icons-515af294c783

**Comment by elgatovital** [comment]
should we wait for a new icon to be finalised?
