### ISSUE TITLE
Error message when typing security phrase

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-android#266]
Prerequisites
-Having Gnosis Safe Wallet extension downloaded for Chrome.
-Having Gnosis Safe Wallet App downloaded for Android.

Steps to reproduce:
1- Accesing the App for Android
2- In Options, choose "Replace browser extension" 
3- Scan QR code shown in browser extension
4- Try to type recovery phrase
5- Observe

Expected result:
The app and the extension are correctly syncronized

Actual result:
An error message is displayed while and after typing recovery phrase

![img_20181022_110456175_hdr](https://user-images.githubusercontent.com/44403034/47363358-f8b30180-d6ac-11e8-8b8f-45b0a502b5cd.jpg)

Smartphone:
 - Device: moto g6 play
 - Android Version: 8.0.0
 - App Version: 0.7.1

Additional context:
-Chrome extention version: 0.5.0

**Comment by rmeissner** [comment]
@tschubotz os this the same error as you reported (#262)?

@MicaelaPesado For future issues it would be nice if you could add the Android version, the app version, the chrome extension version and the device you used. (see https://github.com/gnosis/safe-android/issues/new?template=bug_report.md)

**Comment by fmrsabino** [comment]
This issue seems to have been already solved in current versions so I will close it.
