### ISSUE TITLE
Address can't be restored

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-android#276]
When you enter the app, the recovery function fails. 

Pre-Conditions:
Have a Safe wallet address made

Steps to reproduce:
1. Enter the Safe Wallet Mobile App
2. Tap on "Recover a Safe"
3. Write your existent address
4. Observe

Expected result:
You can access the application normally

Actual result:
An "Invalid Safe address" message is shown 

Smartphone:
Device: moto g6 play
Android Version: 8.0.0 - 6.0.1
App version: 0.7.2- rinkeby

![img_20181101_112558696](https://user-images.githubusercontent.com/44405181/47857944-a9b24e00-ddc9-11e8-8d7d-a0f29869f047.jpg)

**Comment by MicaelaPesado** [comment]
@rmeissner It also happens at the new app version 1.0.1.

**Comment by fmrsabino** [comment]
This issue seems to have been already solved in current versions so I will close it.
