### ISSUE TITLE
Can't recover a Safe from QR code

### ISSUE THREAD

**Issue by lvazq** [gnosis/safe-android#277]
When you recover a Safe with QR code this doesn't recognize the address .

Pre-Conditions:
Have a Safe wallet address made

Steps to reproduce:

Enter the Safe Wallet Mobile App
Tap on "Recover a Safe"
Scan your QR code of the Gnosis Safe Web
Observe

Expected result:
You can access the application normally

Actual result:
An "Invalid Safe address" message is shown

Smartphone:
Device: LG Nexus 5X
Android Version: 8.1.0 - 6.0.1
App version: 0.7.2- rinkeby

https://drive.google.com/open?id=1PMt4HQ0vb7wOTmSZrYwCItj9UMcf_yTH

**Comment by fmrsabino** [comment]
This issue seems to have been already solved in current versions so I will close it.
