### ISSUE TITLE
Error entering the recovery phrase

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-android#278]
Filling the recoverey phrase with the correct order of words shows "Unknown Error" when submitting.

Steps to reproduce:
1. Go to the app on the device
2. Press the "create new safe" button
3. On "set-up your browser extension" stage, tap on skip
4. Tap on "Get my Recovery Phrase"
5. Tap on "I have a copy"
6. Select the words at the button of the screen and put them in the textbox in the correct order (the order that was given in the previous screen)

Expected result:
You can access your Safe properly by submitting the phrase.

Actual result: 
An "Unknown error" message is shown.

Smartphone:
Device: moto g6 play / moto g3 
Android Version: 8.0.0 / 6.0.1
App version: 0.7.2- rinkeby

![screenshot recovery phrase](https://user-images.githubusercontent.com/44405181/48009375-63772a80-e0fa-11e8-9768-7ad56feb55bd.png)

**Comment by damiandragobetzky** [comment]
Hello!

If you uninstall and reinstall the app, it works normally.

**Comment by rmeissner** [comment]
@damiandragobetzky Thank you for your update.

The Rinkeby app is our testing environment and therefore it happens that we do breaking changes to the application db. In this case errors like the one you reported will happen. We try to add a warning in the release notes for updates that introduce breaking changes in our testnet version. 

For our soon to be released mainnet version we will make sure that this will not happen between releases.
