### ISSUE TITLE
Recover Safe screen when not having enough funds doesn't refresh

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#291]
**Describe the bug**
The screen when recovering a Safe when not having enough funds doesn't refresh automatically and there is no button to do so manually

**To Reproduce**
- Start recover Safe flow
- Enter address & mnemonic
- Transfer required ETH
-> App doesn't detect that automatically
- I had to put the app to background and bring back to the front

**Expected behavior**
It should happen automatically or there should be a button to do so manually.

**Screenshots**
![img_4265](https://user-images.githubusercontent.com/1380529/48256890-3afc7280-e411-11e8-855c-c00d332cbdb9.JPG)

**Smartphone (please complete the following information):**
- Device: Moto GS5
- Android Version: 7.1.1
- App Version: 0.8.1-1-g3e736b7

**Additional context**
-

**Comment by rmeissner** [comment]
Will be fixed with changes in https://github.com/gnosis/safe/issues/89
