### ISSUE TITLE
Unlock screen: message about wrong password is hard to see on top of keyboard

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#292]
**Describe the bug**
When I enter a wrong password, the message is hard to see on top the keyboard

**To Reproduce**
1. Open unlock screen
2. Enter wrong password and continue

**Expected behavior**
A clear message why I can't continue

**Screenshots**
![screenshot_20181112-115648](https://user-images.githubusercontent.com/2284385/48343408-95483e00-e672-11e8-8ccd-ee44b47992c7.jpg)

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by rmeissner** [comment]
@tschubotz should we change this? If so, could we get designs? :)
