### ISSUE TITLE
Transaction confirmation screen: rounded up values misrepresent the actual transaction value

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-android#297]
**Describe the bug**
Transaction amount shown to the user is rounded up (visually) up to 5 decimals. This means that when the input is something like `0.00000000001` then the confirmation screen would show `0.00001` event though the underlying value is orders of magnitude lower .

**To Reproduce**
1. Start a transaction and input a small value (with more than 5 decimals).
2. Click on 'Continue' to go to the confirmation screen
3. See that the value is rounded to 5 decimals misrepresenting the real value

**Expected behavior**
The exact value should be shown (or better rounding should be used).

**Screenshots**
![screenshot_20181114-180323](https://user-images.githubusercontent.com/3332770/48580397-61457500-e91f-11e8-8627-d4db2c19cb61.png)
![screenshot_20181114-180337](https://user-images.githubusercontent.com/3332770/48580408-6c000a00-e91f-11e8-970d-00054ad84cc2.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - Android Version: Android 9
 - App Version: 0.8.0

**Comment by rmeissner** [comment]
@fmrsabino this only applies to ether or also to other tokens?

**Comment by fmrsabino** [comment]
Only applies to ether.
