### ISSUE TITLE
Change tagline for app start screen

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-android#304]
**Describe the bug**
Start screen currently has the old tagline. 
The new one is "Enter the decentralized web." 

Also, will we remove "Personal Edition"? 

I've uploaded new screen to Zeplin: zpl.io/aXzvwJg

**Comment by fmrsabino** [comment]
Translations also need to be updated.

Korean: `탈중앙화 웹을 시작합니다`

**Comment by tschubotz** [comment]
@biocom I know Sasha and you have been playing around with a bigger font for that start screen. Did you decide on that one yet? If so, could you please link the screen in Zeplin here? :)

Concerning the translations, once they are updates in Lokalise, we can take care of the translations.

**Comment by rmeissner** [comment]
This will be covered by rebranding changes
