### ISSUE TITLE
Crash when sending Rinkeby Eth (version 0.8.0-6-gb68522d-internal)

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-android#305]
**Describe the bug**
Inconsistent crash, happens when sending eth (.1 or less) to new iOS app. App closes when tapping "continue" (after entering amount and scanning or pasting address)

**To Reproduce**
Inconsistent crash, so far can't figure out how to reproduce. 

**Expected behavior**
After tapping "continue" confirmation screen should have come up with overview to submit/confirm transaction. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G5S Plus
 - Android Version: Android 8.1.0
 - App Version 0.8.0-6-gb68522d-internal

**Additional context**

**Comment by rmeissner** [comment]
Could not reproduce
