### ISSUE TITLE
Assign different colored app icons to internal app and Playstore app

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-android#306]
When having both internal and external releases on the same phone, the icons look the same. So it's difficult to distinguish them from each other. 

Would be great to have an "in-process" app icon for internal releases that differs in color according to the pre-defined guidelines by Safe team. 

**Blue** - Production (Store version)
**Yellow** - Internal (Crashlytics)
**Red** - Debug (devs local build only)

**Green** will not be used by android right now

**Comment by rmeissner** [comment]
This is implemented
