### ISSUE TITLE
Error when scanning QR to replace recovery phrase

### ISSUE THREAD

**Issue by Mettenim** [gnosis/safe-android#314]
**Describe the bug**
User cannot create new recovery phrase because when she scans her browser extension, it shows that its "not connected to this Safe". 

**To Reproduce**
1. Go to Replace recovery phrase
2. Click on Scan QR Code
3. Open browser extension
4. Go to Menu and select Replace recovery phrase
5. Scan QR code with phone
6. An error bar appears "The browser extension is not connected to this Safe."  Even though the browser extension was newly created and just connected through a transaction.  

**Expected behavior**
After scanning the QR code, a new recovery phrase flow should be initiated. 

**Screenshots**
![img_0080](https://user-images.githubusercontent.com/39806845/49594630-979e6f00-f976-11e8-9bd3-080647ad538a.jpg)

**Smartphone (please complete the following information):**
 - Device: Moto G
 - Android Version: 7.1.1
 - App Version version 1.0.1-rinkeby

**Comment by Mettenim** [comment]
Safe address: 0x063aa1e87fDdA989B7433579eDdde1B4788766d6

**Comment by Mettenim** [comment]
Here's the QR Code from the browser extension:
![image](https://user-images.githubusercontent.com/39806845/49643532-404fdb80-fa16-11e8-93c0-02ef671732a1.png)

**Comment by tschubotz** [comment]
This is probably caused by gnosis/safe-browser-extension#98
