### ISSUE TITLE
Improve error messages when Safe cannot be restored

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-android#332]
Currently we don't give much information about why the Safe could not be restored.

We should provide more meaningful messages so that the user is aware of possible next steps to take.

#329 is an example where issues have been reported with network error messages.

**Comment by elgatovital** [comment]
Ticket is obsolete in my opinion. Currently following errors are being distinguished when entering mnemonic: 
- SafeInfoError
- WrongMnemonic - wrong mnemonic for safe
- InvalidMnemonic - invalid recovery phrase
- RecoverDataError
