### ISSUE TITLE
Paying gas with WETH fails

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-android#337]
Description:
When trying to make a transaction whilst having WETH set for fee payment, the browser extension won't let the user confirm the tx.

Pre-Condition: Having WETH set for fee payment

1. Go to Gnosis Safe Android 1.2.0 App (Mainnet)
2. Choose a token to send 
3. Start the transaction
4. Check browser notification
5. Observe

Expected behaviour:
The transaction can be confirmed with the browser extension.

Actual behaviour:
The browser extension tells the user to retry sending the transaction confirmation, when it was already sent.

Platform:
- Device: Moto G6
- Android Version: Android 8.0.0
- App Version: 1.2.0

Additional context:
Transactions with other Tokens and WETH for fee payments haven't been tried yet, and for so we know it only happens when sending DAI, ETH and WETH.

Capture:
https://drive.google.com/open?id=1BveJrFjZYp4zZLmOrVLWcro7T63GnTSY

**Comment by damiandragobetzky** [comment]
Update: Now the confirmation is not even sent to approval by extension.

**Comment by tschubotz** [comment]
@damiandragobetzky Thanks for reporting. Which Chrome extension version are you using?

**Comment by damiandragobetzky** [comment]
@tschubotz we are using v1.3.3, which I think it's the latest. We also tested it with others extensions disabled.
