### ISSUE TITLE
Deposit impossible to confirm

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/safe-android#343]
**Description**
There are different types of issues when it comes to confirming a deposit at DX Mgn Pool Interface.

**Steps to reproduce the behavior:
Pre-condition:** Having the Gnosis Safe browser extension (rinkeby) activated in the computer with a Safe synchronised.
1. Go to https://dx-mgn-pool.staging.gnosisdev.com/
2. Make a deposit in any pooling 
3. Confirm with extension
4. Enter App confirmation request
5. Try to confirm transaction
6. Observe

**Expected behavior:**
The deposit is correctly confirmed 

**Actual behavior:**
Three different errors occur:
-Confirmation stage closes but extension doesn't recognize any movement whatsoever, nor the deposit succeeds (1)
-An error message appears and user is unable to confirm (2)
-Confirmation stage requests extension confirmation (3)

**Smartphone:**
 - Device: Nexus 5X
 - Android Version: 8.1.0
 - Chrome version:  73.0.3683.86
- App Version: 0.0.1-RC16
 - Contracts version: ^0.1.3-RC4

**Additional context**
These issues occur randomly, albeit user follows the same steps. 

**Captures:** 
1
https://drive.google.com/open?id=1cOazrkI5u9hOit8X9yZJJTOSFQnKBFvy
2
https://drive.google.com/open?id=1xx1TbuI30oUxtltIPx-2qDcmHDOTOUmm
3
https://drive.google.com/open?id=1acULRGygFbL9ZFmMuxY6pYjK507B8X8c

**Comment by MicaelaPesado** [comment]
It's still happenning in the APP VERSION: 0.0.1-RC18, CONTRACTS VERSION: ^0.2.0-RC1-rinkeby

**Comment by rmeissner** [comment]
Could not reproduce
