### ISSUE TITLE
Unable to register fingerprints for safe access

### ISSUE THREAD

**Issue by RyRy79261** [gnosis/safe-android#376]
**Describe the bug**
When trying to enable fingerprints in the general settings on android, the dialog starts for a few milliseconds then crashes, enabling fingerprints is not possible, with an `Unknown Error` popping up.

**To Reproduce**
1. Go to Settings on Android 9
2. Fingerprint toggle to enable

**Expected behavior**
Finger print registration should occur.

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - Android Version: Android 9
 - App Version 1.4.1

**Additional context**
https://github.com/gnosis/safe-android/issues/251

**Comment by elgatovital** [comment]
unable to reproduce

**Comment by RyRy79261** [comment]
@elgatovital Please advise how to set up fingerprints given the scanning fingerprint UI flashes for less than a second before going back to the general settings, with the notification of Unknown Error at the bottom.

**Comment by rmeissner** [comment]
This seems to be a device specific error. We will switch to the biometric dialog in the future (but I am not sure if that will solve your issue).

@elgatovital for documentation purpose: this is the error https://fabric.io/gnosis/android/apps/pm.gnosis.heimdall/issues/5cee9dd3f8b88c296339a7e7
Also it might be related to https://stackoverflow.com/questions/44886119/key-permanently-invalidated-exception-after-adding-removing-fingerprint

@RyRy79261 out of curiosity, in the app settings is the fingerprint displayed as enabled?

**Comment by RyRy79261** [comment]
@rmeissner 

Unfortunately I'm not able to re enable the finger prints, I checked the apps permissions and it has biometric access, so I thats what lead me to think its the change from how fingerprint changed to biometrics in the latest update. 

Will keep an eye out for updates :)
