### ISSUE TITLE
Safe creation is stuck on waiting for funds

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-android#387]
**Describe the bug**
Safe creation is stuck on _waiting for funds_ screen even if Safe was already deployed by the backend.

**To Reproduce**
1. Create new safe
2. Close the app
3. Send the amount required to create the safe (e.g. if 1Eth, send 1.5Eth)
4. Wait for the backend to deploy the Safe.
5. Open the app, it will be stuck as it's waiting for 1Eth, but currently it only has 0.5Eth.

**Expected behavior**
Safe is deployed, so app should go to next screen.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi9 SE
 - Android Version: Android 9
 - App Version 1.4.1

**Comment by rmeissner** [comment]
This happens because the backend is now also listening for the funding and auto creates the Safe. This leaves the app in a state where it assumes that no safe is deployed yet.

@DmitryBespalov does this pose an issue for iOS too?

@Uxio0 can we enable Safe creation pushes as a workaround?

**Comment by DmitryBespalov** [comment]
@rmeissner @Uxio0 iOS handles this case as expected.

**Comment by Uxio0** [comment]
@rmeissner Yes, I'm on that
@DmitryBespalov Can we enable the push notification for iOs too?
