### ISSUE TITLE
Update to 1.5.0 cleared all my Safes

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#389]
**Describe the bug**
After updating from 1.4.1 to 1.5.0 I did not have any Safes anymore on my phone.

**To Reproduce**
1. Install 1.4.1 from https://github.com/gnosis/safe-android/releases
2. Recover a Safe that I had before (https://safe-relay.rinkeby.gnosis.pm/api/v1/safes/0x673017a599c89A4cFf647c4f7846c9efC7BcA2e4/)
3. Create a 2nd Safe (https://safe-relay.rinkeby.gnosis.pm/api/v1/safes/0xD25E0e3d362aBA299AC78fc281a0dF4f751926c5/)
4. Update the app to 1.5.0 via https://github.com/gnosis/safe-android/releases
5. Open the app

👉 😭 No Safes anymore, I'm on the screen where I get prompted to Create a new Safe or to recover my Safe.

**Expected behavior**
All my Safes are still there.

**Smartphone (please complete the following information):**
 - Device: Huawai P20 lite
 - Android Version: 8.0.0
 - App Version. 1.4.1-rinkeby and 1.5.0 rinkeby

**Comment by rmeissner** [comment]
fixed with #390, unit tests will follow
