### ISSUE TITLE
Transactions with the browser extension connected doesn't work

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-android#392]
**Transactions with the browser extension connected doesn't work**

**To Reproduce**
1. Go to Safe Android 1.5.0 on a mobile device.
2. Connect a Safe with the browser extension.
3. Try to make any transaction.
4. Observe.

**Expected behavior**
The user can confirm the transaction with both the app and the browser extension.

**Actual behavior**
The user can confirm the transaction with the browser extension, but the safe app doesn't recognice it, so the user can't confirm the transaction with the app and the app keep asking for the browser confirmation. 

**Screenshots**
https://drive.google.com/open?id=1wkQwp85yRjpcmE0eCIpyvBNO2oEQzIcP

**Smartphone:**
 - Device: Moto g6 Play
 - Android Version: 
 - App Version: 1.5.0 (Rinkeby)

**Comment by rmeissner** [comment]
This doesn't look like an error on the app side, but like an error on the chrome extension. Do you see any output on the console for the popup?

**Comment by rmeissner** [comment]
Nvm it is a client side bug @elgatovital we need to register the newly created accounts with the push service. On each start we need to sync all the accounts owned by the client with the notification service

**Comment by rmeissner** [comment]
It is not enough to authenticate them, we also need to pair them

**Comment by MicaelaPesado** [comment]
In the latest release it works fine.
