### ISSUE TITLE
Unlocking the app, or signing transactions with fingerprint fails

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/safe-android#397]
**Describe the bug**
When trying to sign a transaction or enter to the app using the fingerprint instead of the password, a message is shown asking to introduce the password.

**To Reproduce**
Steps to reproduce the unlocking issue:
1. Go to the app on the mobile. 
2. Try to unlock it, using your fingerprint.
3. Observe

**Actual behavior**
"Too many tries. Switching to password" message is displayed, and the user is unabled to try entering the fingerprint again, user can only enter the password.

Steps to reproduce the signing issue:
1. Being at the send transaction screen
2. Tap on Submit transaction
3. Place your finger on the sensor
4. Observe.

**Actual behavior**
An error ocurred. Please, try again!  message is displayed, and the user is unabled to try entering the fingerprint again, user can only enter the password.

**Expected behavior**
The app is successfully unlocked or the transaction is correctly signed.

**Smartphone:**
 - Device: Moto g 6 play
 - Android Version: Android 8.0.0
 - App Version: 1.5.0

**Comment by rmeissner** [comment]
This error is shown if the scanning failed too often. This state will persist for a while (this is enforced by the operation system). 

So this is expected if scanning failed multiple times before

**Comment by rmeissner** [comment]
On a note I realised, that this occurs if you had the unlock screen open while clicking on the notification to review a transaction
