### ISSUE TITLE
Token Payment: Recover Safe

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#413]
In the process of recovering a Safe it should be possible to change the payment token for this Safe.

See epic.

### ToDos:
- [ ] Adjust recover Safe flow to allow changing token via token payment selection screen with tx estimation (#411)

**Comment by elgatovital** [comment]
no back button for review step (leave as it is right now)
use toolbar from main safe page (current state)
adjust funding layout

**Comment by elgatovital** [comment]
showing fees instead of balances during payment selection: https://app.zenhub.com/workspaces/gnosis-safe-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/508
