### ISSUE TITLE
Error: replace recovery phrase transaction is sent to a MultiSend address instead of the safe.

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#438]
**Describe the bug**
The application is trying to send the "Replace browser extension" transaction to a MultiSend contract's address instead of the safe address.

**To Reproduce**
It looks like the device is not owner of that safe anymore, so when 
the browser extension is being replaced, the algorithm is trying to 
remove the invalid owner and replace browser extension. At this point
it is already wrong.

**Expected behavior**
If the device is not owner of the safe anymore, it should say so with an error.

**Screenshots**
![2019-08-08 14 09 17](https://user-images.githubusercontent.com/284056/62708672-24149c00-b9f4-11e9-9479-21ba7cb8fa9b.jpg)

**Smartphone (please complete the following information):**
 - Android Version: rooted phone, lineage os 15.1 (android 8.1)
 - App Version: v1.6.1

**Comment by rmeissner** [comment]
As mentioned above, the expected behaviour would be that we already display an error on the screen before that the user can only perform this transaction if he is and owner, or that he should try to remove and recover the Safe.

**Comment by rmeissner** [comment]
@tschubotz should this just be a snackbar/ toast or do you want to have something more comprehensive?

**Comment by rmeissner** [comment]
Note: please check other flows that make use of the configration change logic (that created the owner replacement transaction) if something like this could happen elsewhere too

**Comment by tschubotz** [comment]
I think a snackbar/toast would be sufficient at this point.
