### ISSUE TITLE
WalletConnect: Gnosis safe rejecting TX without value key

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#454]
We got a report in WalletConnect telegram channel, that Gnosis Safe Android app rejects transactions without value parameter
![IMAGE 2019-09-05 13:43:30](https://user-images.githubusercontent.com/2284385/64338942-26621a00-cfe3-11e9-8ed3-6c8dba1a7c31.jpg)
.

**Comment by rmeissner** [comment]
This is not a Gnosis Safe issue, but an issue of the kotlin sdk (https://github.com/WalletConnect/kotlin-walletconnect-lib/blob/master/lib/src/main/kotlin/org/walletconnect/impls/MoshiPayloadAdapter.kt). Please move the issue there.
