### ISSUE TITLE
Fix Authenticator pairing

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#485]
Android client: Adjust SafeCreation push message by including owners

*Problem description*
Case when the pairing between the Safe app and the Authenticator is done but the setup is wrong. It happens when the mobile Safe replaces the Authenticator using the same Authenticator.
Notes: The Authenticator users an HDwallet for his owners (different for each Safe), using a different index everytime it is paired with a new Safe.
Context:
- We have an Authenticator with a Safe connected using for example the owner in the position where the index=2
Steps:
1 - The user removes that Safe from the Authenticator
2 - The user gets ready to replace his Authenticator with itself. The Authenticator shows a qr-code that contains a new owner (index=3)
3 - The mobile app scans the qr-code and gets the owner:
        a - The pairing with the new owner (the one in the index=3) is done
        b - A tx for replacing the old owner with the one in the index=3 is triggered (not mined yet)
        c - a Safe creation notification is sent to the Authicator with the Safe address.
4 - The Authenticator receives the notification.
        a - It checks the owners of that Safe (the tx for replacing the owner was not mined yet, so it gets the old owners)
        b - It searches if one of the owners matches any address in the indexes from 0 to 2 that where used prevously in the Authenticator. Here index=2 matches with one of the owners the extension got, so it uses that one. (If we were using a new Safe, no index would match with the owners and index=3 would be used as the owner, so it would work)
5 - The tx for replacing the owner is now mined. Now index=3 is the owner of the Safe but the Authenticator thinks it is index=2.
Here we have a case where the Authenticator will no be able to sign txs because it uses the wrong owner.
This can be fixed by clicking resync in the mobile,. The process would start from the point 4 again and the Authenticator would get now the updated owners and replace his owner internally fixing the situation, but this is not an elegant solution and is not clear at all for the user.
Solution:
Update the safeCreation notification (step 3.c) adding the new owner of the Authenticator that will be used (index=3, that was shown in the qr-code). This would be an optional parameter only when the safeCreation was sent after scaning the qr-code. (Different than the resync case).

**Comment by DmitryBespalov** [comment]
The new format of the notification:

```
{
    "type": "safeCreation",
    "safe": "0xabc...SAFE_ADDRESS",
    "owners": ["OWNER_1", "OWNER_2", "OWNER_3"] // this field will be omitted by old app versions
}
```

**Comment by rmeissner** [comment]
See https://github.com/gnosis/safe-relay-service/blob/develop/safe_relay_service/relay/services/notification_service.py#L54

@Uxio0 the addresses are checksummed, right?

**Comment by Uxio0** [comment]
> @Uxio0 the addresses are checksummed, right?

Yes

**Comment by DmitryBespalov** [comment]
@Uxio0 @rmeissner @elgatovital edited the format to use comma-separated list of addresses instead of JSON array because Firebase supports only string values and not arrays or objects.

**Comment by Uxio0** [comment]
Ok, I did the same for the relay

**Comment by rmeissner** [comment]
@germartinez @DmitryBespalov to avoid unnecessary requests I will only add the owners that are being pushed
