### ISSUE TITLE
Multiple transaction at the same time fail because of wrong nonce

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#510]
**Describe the bug**
If I send two transaction to sign, they show up correctly in the Safe, but when, signing the 1st one works, but when I sign the second one it shows an error.

It’s easy to reproduce here, just try to deposit DAI and WETH for example:
https://pr273--dexreact.review.gnosisdev.com/deposit

**Expected behavior**
Both transaction should be using the correct nonce.

**Additional context**
This is likely the nonce issue because both transactions estimated at the same time, and we don’t queue the transaction submissions

**Open questions**
- If the nonce changes should all existing signatures be deleted, or should we not update the nonce if we already have signature?
- When should the nonce be relaoded (on screen entry, returning from background), can the user trigger this reloading?

**Comment by DmitryBespalov** [comment]
@rmeissner this should be not a bug, because we deliberately did not support the multiple txes since the beginning (we delayed this). Now the time has come 😄

**Comment by rmeissner** [comment]
To the user it behaves like a bug. If it looks like a bug, swims like a bug, and quacks like a bug, then it probably is a bug. :stuck_out_tongue:
