### ISSUE TITLE
Cannot scan inverted QR codes

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-android#514]
**Describe the bug**
Some websites use inverted QR codes (e.g. uniswap). These qr codes are currently not recognized.

**To Reproduce**
1. Go to https://uniswap.exchange/
2. Click on connect and select wallet connect
3. Try to scan QR code with Safe app
4. Nothing happens

**Expected behavior**
QR code should be scanned and wallet connect connected

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - Android Version: Android 10
 - App Version 1.10.0

**Additional context**
Can be solved by adjusting the QR code scanning:
```
class QRCodeDecoder {
    private val reader = QRCodeReader()

    private fun LuminanceSource.decode() =
        reader.decode(BinaryBitmap(HybridBinarizer(this))).text

    fun decode(data: ByteArray, width: Int, height: Int): String {
        val centerX = width / 2
        val centerY = height / 2

        var size = width.coerceAtMost(height)
        size = (size.toDouble() * ReticleView.FRAME_SCALE).toInt()

        val halfSize = size / 2

        val left = centerX - halfSize
        val top = centerY - halfSize

        val source = PlanarYUVLuminanceSource(data, width, height, left, top, size, size, false)
        // Check normal and inverted image
        return nullOnThrow { source.decode() } ?: source.invert().decode()
    }
}
```

**Comment by elgatovital** [comment]
1. inverted qr codes can be scanned
2. we don't have wallet connect integration yet

**Comment by elgatovital** [comment]
recommend to close this ticket

**Comment by rmeissner** [comment]
this is a Safe v1 bug, right? so it is probably not fixed ... and it should also not have the tags "trivial" etc. I will put "won't fix" on it and close it ... as we will not fix it in v1.
