### ISSUE TITLE
Contract upgrade info disappears after making a tx

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#532]
**Describe the bug**
Contract upgrade info disappears after making a tx

**To Reproduce**
I have a Safe v1.0.0
1. Open app
2. I see the upgrade dialog prompting me to update
3. Make a tx (I send 5 OWL)
4. After completing the tx, the update dialog is gone.
I would only reappear after switching to another safe and back.

**Expected behavior**
The dialog persist as long as I haven't upgrade.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 10
 - App Version: 1.11.0

**Comment by rmeissner** [comment]
This is expected, else it would show up while you do the upgrade tx. Proper way would probably to check if the pading tx is a upgrade tx, but would not touch this right now.
