### ISSUE TITLE
gs_multi_send RPC method incorrect type for operation parameter

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-android#540]
**Describe the bug**
If you try to call `gs_multi_send` RPC method with integer as `operation` param it will throw an error. The [specification](https://github.com/gnosis/contract-proxy-kit/issues/2#issuecomment-562524459) says it should be an integer

**To Reproduce**
Call the method with the following request:
```
{
  "jsonrpc": "2.0",
  "id": 1583939731362,
  "method": "gs_multi_send",
  "params": [
    {
      "operation": 0,
      "to": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa",
      "value": "0",
      "data": "0x095ea7b30000000000000000000000006d7f0754ffeb405d23c51ce938289d4835be3b14000000000000000000000000000000000000000000000001158e460913d00000"
    },
    {
      "operation": 0,
      "to": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14",
      "value": "0",
      "data": "0xa0712d68000000000000000000000000000000000000000000000001158e460913d00000"
    }
  ]
}
```

**Expected behavior**
Request goes through and doesn't throw an error

**Comment by rmeissner** [comment]
This specification was done after the implementation and does not apply to android, this will not be changed for now

**Comment by mikheevm** [comment]
what can we do to remove the difference then? should iOS fix that? It makes `contract-proxy-kit` unusable with the safe for one of the platforms depends what type you choose to pass 😄

**Comment by rmeissner** [comment]
@DmitryBespalov @jpalvarezl @elgatovital please check this and decide if we want to fix it or not. If you decided on a format someone please add it somehow to the https://github.com/gnosis/safe-docs/tree/master/docs or if we decide that we do not want to fix this comment on the cpk issue.

**Comment by mikheevm** [comment]
I checked walletconnect's provider object and seems like it doesn't have any info about the OS of a connected wallet, so it's impossible to detect which wallet is connected. Would be great if this gets fixed.

**Comment by DmitryBespalov** [comment]
> This specification was done after the implementation and does not apply to android

@rmeissner This does not make sense as there was time and this was checked and communicated properly.

> this will not be changed for now

This is another topic whether to do it now, we'll handle that

**Comment by rmeissner** [comment]
> @rmeissner This does not make sense as there was time and this was checked and communicated properly.

that was end of last year and at that point it was already released. The example provided to test Android actually used a string, so yes there was a miscommunication but the specs linked were written after implementation therefore they do not apply. If we want to decide on valid specs we need to document them somewhere (which should not be in an issue of a repo that uses this call).

**Comment by rmeissner** [comment]
This issue has low priority but should be fixed (either on ios or android side). Also documentation for this should be added to https://github.com/gnosis/safe-docs for this.
