### ISSUE TITLE
Add Safes, remove Safes and switching between them

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#549]
https://github.com/gnosis/safe/issues/285

**Comment by elgatovital** [comment]
Room for persistence

@Entity(tableName = "safes")
data class Safe(

@PrimaryKey
@ColumnInfo(name="address")
 val address: Solidity.Address,

 @ColumnInfo(name="local_name")
 val localName: String
)

active safe:
Prefs.activeSafe: Solidity.Address

**Comment by elgatovital** [comment]
Adding safe (reuse bottom sheet dialog)
  enter address from clipboard
  scan qr code
  enter ens

 validate safe address

**Comment by elgatovital** [comment]
List of safes
