### ISSUE TITLE
Internal release

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#550]
https://github.com/gnosis/safe/issues/300

**Comment by elgatovital** [comment]
- Create Firebase Project (safe-firebase-staging)
- Configure app distribution
- Uncomment & adjust app distribution upload script

**Comment by biafra23** [comment]
@tschubotz Which buildType of the app is which distribution channel?

Production mainnet 
- Via Firebase app distribution, updated manually  
 -> buildType: **release**
Product Rinkeby
- Via Firebase app distribution, updated manually 
 -> buildType: **rinkeby**
Staging Rinkeby  
- Via Firebase app distribution, updated with every commit (?) 
 -> buildType: **internal**

**Comment by tschubotz** [comment]
> @tschubotz Which **buildType** of the app is which distribution channel?

I'm not sure I understand the question. What exactly is **buildType**? Or what do the different **buildTypes** imply under the hood?

From my end, I would like to have access to:
- 1 version for mainnet that uses our mainnet production services
- 1 version for rinkeby that uses our rinkeby production services
- 1 version for rinkeby that uses our rinkeby staging services

The first 2 for internal (and possibly external) distribution for beta testing. And the 3rd version so we can test features that require a backend endpoint that might only be available on staging, not on production, yet.
