### ISSUE TITLE
Accept terms and privacy policy

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#551]
https://github.com/gnosis/safe/issues/292

**Comment by elgatovital** [comment]
- Upon opening the app, the user has to accept Terms or Use and Privacy policy
- User can view Terms and Privacy policy (https://gnosis-safe.io/privacy/ and https://gnosis-safe.io/terms)
  - Both are not hardcoded text, but links that open a browser window (exactly how we do it in the current app)

**Comment by elgatovital** [comment]
Assumption: 
 - store whether terms & conditions were agreed to in preferences 
 - Check on every app start
 - No Thanks => close app

Bottomsheet dialog

**Comment by rmeissner** [comment]
Sure that No thanks should close the app? Normally we only close the dialog

**Comment by jpalvarezl** [comment]
"No thanks" simply dismisses the dialog. Here is what Tobi expects as behaviour:

https://github.com/gnosis/safe/issues/292#issuecomment-620671372
