### ISSUE TITLE
View ETH and ERC20 token balance

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#553]
- User can see their ETH balance, ETH is always on top
- User can see the balance of all ERC20 tokens with balance > 0, tokens are ordered by their names, ascending
- User sees fiat value in USD per asset
- ~User can select the reference fiat currency from a list somewhere in the app~
  - Selecting the fiat currency will be part of a separate epic. (#304)

**Comment by elgatovital** [comment]
screens
- coins: https://zpl.io/aXv8opl
- collectibles: https://zpl.io/2ZNK0xJ

**Comment by rmeissner** [comment]
Note: Collectibles are not part of this issue

**Comment by elgatovital** [comment]
Add Balances fragment (coins) which contains only list of balances

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/a51a3885-ec43-433b-b2bc-b8363e2cfa60)
