### ISSUE TITLE
Safe persistency layer

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#557]
- Use room for persistency
   see https://github.com/gnosis/safe-android/issues/549 for db schema suggestion
- Use shared preferences for active safe
- Define DB, DAO'
- Add migration tests
- Add basic safe repository 
  - validate safe info
  - provide list of safes
  - provide currently selected safe
 
Ideally we can have this merged and published to not have to iterate for clean up for this PR: https://github.com/gnosis/svalinn-kotlin/pull/43

**Comment by jpalvarezl** [comment]
@elgatovital I need some clarification, regarding the migration tests. It seems like in order to have a migration we need to have modified the database schema somehow and as this is the first iteration, there is really no way to do a migration as far as I understand. Am I missing something?
