### ISSUE TITLE
App Settings

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#566]
- User can see the app version.
- ~User can see and select reference fiat currency for the entire app~
  - This will be part of a separate epic
- User can see the network version (Mainnet, Rinkeby)
- User can view Terms (Link to https://gnosis-safe.io/terms/)
- User can view Privacy Policy (Link to https://gnosis-safe.io/privacy/)
- User can view used licenses (Link to https://gnosis-safe.io/licenses/)
- Terms, PP and licenses are not hardcoded, but links that open a browser window (exactly how we do it in the current app)
- User can get in touch with us (Email, Discord, Twitter)
  - As a company we decided to moved to Discord, so let's take this opportunity.
  - Help center: https://help.gnosis-safe.io
  - Email: safe@gnosis.io
  - Discord: https://discord.gg/FPMRAwK
  - Twitter: https://twitter.com/gnosisSafe
  - Feature suggestion: https://safe.cnflx.io/
- User can see other app settings:
  - ENS resolver address
  - RPC endpoint url
  - Backend services urls (safe-relay, safe-tranasction)
  - something else?

**Comment by elgatovital** [comment]
- Assumption: backend url's will be view only and not changeable
- App settigns fragment 
- Get in touch opens different fragment
- privacy, terms, licenses opens external browser

**Comment by jpalvarezl** [comment]
[NEW] Service URLs are to be copied into the clipboard on tap. Epic was updated.
