### ISSUE TITLE
View transaction details

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#568]
### Transaction details:
- User sees the following details:
  - Sender (address & identicon, tapping copies the address to clipboard)
  - Recipient (address & identicon, tapping copies the address to clipboard)
  - ETH value
  - Data (Show only number of bytes by default, user can view and copy full data if desired)
  - Submission date
  - Execution date
  - Type of operation (call or delegatecall)
  - Transaction hash (User can copy it)
  - Status (See section below)
  - ~Network fee~ (Leave this one out since there could be different types and we don't need this complexity right now, cf. [Slack thread](https://gnosisinc.slack.com/archives/G9GEEHY79/p1585744219049200))
- User can open the tx on etherscan.
- If a transaction is an outgoing tx show:
  - Which of the owners confirmed/rejected

### Transaction decoding:
- Decode the following transactions by showing details:
  - ERC20 token transfers
  - Safe settings changes (addOwner, removeOwner, swapOwner, changeMastercopy)

#### Transaction status
https://docs.google.com/document/d/1oV3hdlBvbs5VB-j-4mZVWOZRekdFNBWIv92W4uRapto/edit#

**Comment by elgatovital** [comment]
see web client for confirmation list. Ask them for specification

**Comment by elgatovital** [comment]
What's missing:

- NFT details (action part for NFT's)
- Small layout adjustments
- Logo for ERC20 (not loaded, not part of the layout)
- Placeholder when data can not be loaded

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -98
