### ISSUE TITLE
Enable Dark Mode in App Settings: Appearance

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#570]
# High-level overview of the feature
- In the app settings, the user can select
  - Auto <- That's the default. It just uses what the operating systems is set to
  - Light 
  - Dark

**Comment by rmeissner** [comment]
Where is it mentioned that this is part of the app settings? @tschubotz do we have a phase1 epic for this?

**Comment by tschubotz** [comment]
Not sure I understand you question @rmeissner. The Epic is already linked to this ticket.
Here's the link again: https://github.com/gnosis/safe/issues/308
It's the 8th or 9th highest prio ticket currently in the "specs for review" column.

**Comment by rmeissner** [comment]
Ahh I don't see zenhub info on mobile and the epic is missing the phase1 label for me

**Comment by rmeissner** [comment]
Also maybe referencing this with the app settings issue might be helpful (I wouldn't necessarily add it to the app references issue, but maybe just mentioning it that they are linked on github)

**Comment by tschubotz** [comment]
yes it's missing the `phase 1` label since it's not really a must have and we didn't discuss this for phase 1 yet. But it seems like there is some excitement around this and I know that lots of us are using dark mode ourselves, so if the efforts is not extraordinarily big, I would tackle this rather sooner than later :)

I just mentioned the app settings epic in the dark mode epic so they are linked.

**Comment by rmeissner** [comment]
Also I am not sure if the effort differs if we say the app should be able to use different settings from the device settings. That is something that @jpalvarezl @elgatovital @biafra23 need to comment :)

**Comment by tschubotz** [comment]
> Also I am not sure if the effort differs if we say the app should be able to use different settings from the device settings. That is something that @jpalvarezl @elgatovital @biafra23 need to comment :)

That would be good to know, yes :)

**Comment by biafra23** [comment]
We can use         
`AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_YES)`
and
`AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_NO)`
to override system setting.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 -1686
