### ISSUE TITLE
Confirmation list for tx details

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#573]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/c75c32fb-99ec-4af0-934e-c82c11ad6bdd)

**Comment by biafra23** [comment]
Discussion on slack: https://gnosisinc.slack.com/archives/C63LQTGNB/p1588837780117500

**Comment by elgatovital** [comment]
https://gnosisinc.slack.com/archives/C63LQTGNB/p1588837780117500

**Comment by jpalvarezl** [comment]
@rmeissner @tschubotz So rejected transactions as far as we've discussed, are transactions with value, data set to 0 that have the same nonce as the transaction that is being attempted to be cancelled. How would this be reflected on the list, say we have a transaction coming up ahead that is meant to cancel something that is shown as pending?

**Comment by tschubotz** [comment]
This ticket is about the confirmation list but your question is about the transaction list, correct?

So are you asking how this should be displayed on the transaction list? When there is already a transaction pending ( i.e. it's being executed according to https://github.com/gnosis/safe/wiki/Safe-transaction-states) but at the same time there is a competing cancel tx coming in?

**Comment by rmeissner** [comment]
As far as I understood iOS is using the data that is returned in the tx list. So only if the list is refreshed would the confirmation change. @DmitryBespalov correct me if I am wrong :D else I would go for pull to refresh for now as we do not expect that these change often and you would need to check if executed (since for executed tx it makes no sense to poll).

**Comment by tschubotz** [comment]
I agree to Richard. Let's not add some kind of polling yet.
I would use the data from the list that we have.
However I think there should be the option to "pull to refresh" on the tx details as we discussed in https://github.com/gnosis/safe/wiki/Network-requests-and-no-internet-connection

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -93
