### ISSUE TITLE
Tx details screen: basic ui

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#574]
screen: https://zpl.io/bPj0NQD
Layout except confirmation/signature list & status header
Navigation to advanced is excluded
All addresses lead to etherscan

Bundle arg: safe tx hash
Load tx data using safe tx hash on entering

**Comment by elgatovital** [comment]
TODO: add link to tx service

**Comment by jpalvarezl** [comment]
> TODO: add link to tx service

https://safe-transaction.rinkeby.gnosis.io/

endpoint:
/safes/{address}/transactions/

**Comment by elgatovital** [comment]
use new client gateway. @jpalvarezl please post endpoint description here
