### ISSUE TITLE
Visual feedback on coverage for the repo

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#577]
Add codecov to the repo

**Comment by rmeissner** [comment]
It seems that currently only the :app module is measured in codecov (but not sure). We probably need to include all module somehow (this should already be the case for svalinn, so maybe we can see how it is done there)

**Comment by biafra23** [comment]
Maybe add badge in the readme?

**Comment by jpalvarezl** [comment]
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Integrating-Codecov-with-a-GitHub-project-(Coverage-tool)
