### ISSUE TITLE
Cleanup: Remove Fabric, adjust distribution

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#578]
Fabric is deprecated and will be available until May 4, 2020
This won't affect app as everything will be forwarded to firebase.

- Fabric sdk should be removed from project dependencies
- Adjust distribution via firebase app distribution

**Comment by jpalvarezl** [comment]
@elgatovital Can we close this? This appears to be done, as far as I can remember.

**Comment by tschubotz** [comment]
> @elgatovital Can we close this? This appears to be done, as far as I can remember.

@elgatovital ping

**Comment by elgatovital** [comment]
yes,  this would be relevant only for the legacy app. But we don't have it in store -> problem solved
