### ISSUE TITLE
Documentation of internal setup for App

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#583]
We need a document compiling the links describing the process for deploying/running the apps for our internal team. Links to the different `google-services.json` files corresponding to their build types and any other basic resource need for being able to run the project locally and in the build machine.

The document should be placed along with the rest of the project documentation in this folder: https://github.com/gnosis/safe-android/tree/master/docs

**Comment by biafra23** [comment]
See: https://github.com/gnosis/safe-android/pull/579
