### ISSUE TITLE
View collectibles

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#589]
- We support ERC721 tokens only for now.
- User can switch between coins and collectibles.
- User sees overview of their list of collectibles, grouped by type, similar to https://gnosis-safe.io/app/#/
  - The web interface pulls that from OpenSea's API
- Meta data (image and name) is pulled from OpenSea as well

# Misc
- OpenSea API: https://docs.opensea.io/reference

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 ( 10)
Separate issues are created for the problems ( no critical)
