### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#590]
**Note from Tobi: Below is an outdated version of the epic.**

- User gets notified when:
  - ~There is a new transaction waiting for confirmations.~ (Let's not do this one and the following one since we only want to send those if the mobile app is an owner or authorized)
  - ~An owner confirmed or rejected a transaction.~
  - An outgoing transaction was submitted to Ethereum
  - An outgoing transaction failed or succeeded.
  - ETH, ERC20 or ERC721 tokens were received.
- From the above list, users can specify which notification types to receive and which ones not.
  - This setting should be app-wide, i.e. the same setting is used for all Safes.
- Clicking a notification would open the transaction details of that tx
  - In case there are multiple Safes the app switches to the correct Safe automatically.
- User should be asked to enable push notifications after successfully adding their first Safe
- When a user removes a Safe from their device, it should not receive pushes for this Safe anymore.

# Texts

- `safe_name` should be the name that the user set for their Safe. If there is no name set, please display `Safe 0xab` as `safe_name` 
- For token transfer info: Cut of decimals at maximal 6 digits after decimal separator. 
- For NFTs, if there is a `name` use that one, if not then just write `ERC721 token`
- If the notification is not about a transfer, leave out that line of the notification :)
- Each notification should open the tx detail screen for that specific tx. The app should switch to the correct Safe, repectively.
- The first line of all notifications should be bold if possible.

### ~There is a new transaction waiting for confirmations.~

~~safe_name: New transaction proposed.
Transfer 0.123456 ETH to 0xab ... cdef~~

### ~An owner confirmed or rejected a transaction.~

~~safe_name: Transaction confirmed by owner
Transfer 9876.123456 GNO to 0xab ... cdef~~

~~safe_name: Transaction rejected by owner
Transfer Magic Sage~~

### An outgoing transaction was submitted to Ethereum

```
safe_name: Transaction submitted to Ethereum
Transfer ERC721 token 
```

### An outgoing transaction failed or succeeded.

```
safe_name: Transaction succeeded
Transfer 123 USDC to 0xab ... cdef
```

```
safe_name: Transaction failed
Transfer 1 ETH to 0xab ... cdef
```

### ETH, ERC20 or ERC721 tokens were received

- Please send incoming notifications only for non-scam tokens (i.e. tokens in our curated token list).

```
safe_name: Received 0.123456 ETH from 0xab ... cdef
```

```
safe_name: Received 9876.123456 GNO from 0xab ... cdef
```

```
safe_name: Received ERC721 token from 0xab ... cdef
```

### Related issues
- https://github.com/gnosis/safe-notification-service/issues/70

**Comment by tschubotz** [comment]
Does this one contain the tracking part of the epic? If not, I believe there needs to be another subtask for this.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114

the amount for ERC20 and ERC721 should not be displayed according to Epic
and only safe_name: Transaction succeeded and safe_name: Transaction failed should be displayed
Another from the description should be ignored ( confirmation, other messages)
