### ISSUE TITLE
Public Store release

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#591]
- App is release on AppStore/ Play Store
- The apps are updated manually

See #300 for other app versions

**Comment by jpalvarezl** [comment]
https://drive.google.com/drive/u/0/folders/1h_lQvTLLqMVdDE7mYQ2eAnQXNMXUpnmS

**Comment by elgatovital** [comment]
TODO:

- playstore entry
- playstore icons
- release notes 
- app rating
- app category

**Comment by liliya-soroka** [comment]
the version 1.12.1 - 115 was released
