### ISSUE TITLE
Safe Settings: basic ui

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#593]
<img src="https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/c934de37-0b8b-4660-8b42-f56684bbd7ed" width="300" />

show data
no modificaitons
addresses lead to etherscan

**Comment by jpalvarezl** [comment]
https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x1de8f9874A5b60C94304888f8B42dB21f06813e6/

Is an example of the usage of the endpoint for this task.

The issue: https://github.com/gnosis/safe-transaction-service/issues/89

**Comment by elgatovital** [comment]
remove confirmation: https://zpl.io/beEpowN

**Comment by jpalvarezl** [comment]
`Advanced` screen is not part of this task.

**Comment by jpalvarezl** [comment]
Time box ENS to 2 hours, optionally include.

**Comment by liliya-soroka** [comment]
Reopened:
1. Edit the safe name is lost 
Current result: There is no possibility to edit safe name
Expected result: see design , there is the option to edit safe name

app version 1.12.1-54

**Comment by jpalvarezl** [comment]
Local name editing will be implemented in task: https://github.com/gnosis/safe-android/issues/728

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-59
Sprint 7 - Safe settings test run in TestRails
