### ISSUE TITLE
Safe Settings: Advanced screen

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#594]

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/0a3ea531-b27a-448e-8f16-46890ea33847)

**Comment by jpalvarezl** [comment]
Sasha provided the mock for when a fallback handler is not set: https://zpl.io/aMJvzgK

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-59
Sprint 7 - Safe settings test run in TestRails
