### ISSUE TITLE
Add Timber log trees per build type

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#597]
Different environments might need different log levels and reporting of errors:

DEBUG -> log level high
RELEASE -> log level minimal and maybe sending error logs to crashlytics?

**Comment by jpalvarezl** [comment]
@biafra23 Hey, is this done? I think timber is working correctly already, isn't it?

**Comment by jpalvarezl** [comment]
If that is the case, let's close this.

**Comment by biafra23** [comment]
It is not done.

**Comment by liliya-soroka** [comment]
@elgatovital , @biafra23 , is the testing required for the task?
If yes, could you add info on how it can be checked, please?

**Comment by liliya-soroka** [comment]
closed, no QA required.
The firebase will be checked time to time during the regression testing
