### ISSUE TITLE
Error not cleared after corrected when adding a safe

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#598]
### Expected behavior
After entering a wrong ENS name (or QR code scan) the user should be able to correct the name and it should be accepted, if it is correct.

### Actual behavior
After correcting the ENS name (or scanning QR code) the correct adress is not accepted.

### Steps to reproduce the behavior
Not sure this is a known bug (Steps to reproduce):
- Add safe by ENS name
- Enter valid ENS name (For example: safe.test)
- Hit Ok to select address
- Hit next
- Hit next without entering a name
- Observe correct error message (Invalid name)
- Enter valid name (for example Fnord)
- Hit checkmark to submit name
#### Observed behaviour: ####
- Correct name is not accepted
#### Expected behaviour: ####
- Correct name should be accepted

### Additional information

- Device: Nexus 5x and Pixel 3a
- Android OS version: 8.0 and 10.0
- Safe app version: Build from current master

**Comment by jpalvarezl** [comment]
Appears to have been fixed. Could not reproduce.
