### ISSUE TITLE
Balance token logo icon background

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#606]
Balances tab in the app presents the values for all the available tokens. Each token has a logo image. 

The logo image should have a circular background. The logo should be clipped within this circle.

The colour of the background circle should be transparent for light mode and #FFFFFF in dark mode.

**Comment by biafra23** [comment]
@jpalvarezl Isn't that the case? What do we need to do here?

**Comment by biafra23** [comment]
This is implemented in the recently merged PR

**Comment by liliya-soroka** [comment]
@biafra23 and @posthnikova .
Is it something new " The colour of the background circle should be transparent for light mode and #FFFFFF in dark mode."
I don't see the #FFFFFF in dark mode ad background circle on the design - https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ec28e9138a1a0335ac44003

**Comment by posthnikova** [comment]
@liliya-soroka It's there. Without background:

![image](https://user-images.githubusercontent.com/45787536/102782616-f2f2fc80-4399-11eb-81db-b68b1f35c1d1.png)

With background:

![image](https://user-images.githubusercontent.com/45787536/102782636-fbe3ce00-4399-11eb-9792-159cac665f2b.png)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0  -1745
