### ISSUE TITLE
Optmize test coverage to cover only intended files

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#608]
### Expected behavior
According to our OKRs, test coverage is supposed to cover the following:
- Only logic code needs to be covered 100%
- Android: view models, repository, manager, services, ...
- Generated code is not required (should be tested elsewhere normally)

### Actual behavior
- Code coverage covers all code in all enabled modules

**Comment by rmeissner** [comment]
The okr doesn't say that only logic code should be measured. It says that logic code should have 100% test coverage. This doesn't meant that you shouldn't be aware of the test coverage of other parts of the app. 

If you use the test config from the legacy app generated code is already excluded.

**Comment by biafra23** [comment]
I changed the description regarding logic code coverage

**Comment by rmeissner** [comment]
Could you add an example of generated code that is included?

**Comment by biafra23** [comment]
Our code coverage setup is a bit confusing.

At the moment we have to different jacoco setups. One with version 0.7.9 and one with version 0.8.5. The configation for 0.8.5 is taken from `buildsystem/coverage_report.gradle`

`createDebugCoverageReport`  -> 0.7.9
`createDebugTestCoverage` -> 0.8.5

I will try to disable v0.7.9. as it just adds confusion and it is unclear how upgrade the version of configure it.

**Comment by liliya-soroka** [comment]
closed, not qa required
