### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#612]
When switching the **device** to dark mode, the app should go dark. We need to apply the right colors for Dark Mode according to Zeplin layouts https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5ec28df08989ee476e7d1446

Technical info:
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by jpalvarezl** [comment]
Do you mean the controls for switching themes?

**Comment by jpalvarezl** [comment]
The colours for dark mode should be defined and only switching at the OS level is required to work after this task.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 - 1686
