### ISSUE TITLE
App Settings: Fiat currency

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#613]
- Get list of supported currencies from backend
- Show currency selection screen
- Persist selected currency & use it for balances updates

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/57661b09-8796-4a39-9a35-8cf1c736fbfb)
screen: https://zpl.io/VKZzjwq

**Comment by jpalvarezl** [comment]
This hasn't been speced yet. I would create this issue later when there is more info on the subject.
