### ISSUE TITLE
Splash screen: Do not show "get started" on every start

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#614]
![image](https://user-images.githubusercontent.com/17750984/82635507-a2979e80-9c00-11ea-831c-79ef66f0e493.png)

**Comment by biafra23** [comment]
What is the condition to (not) show the button? 
Whether there is a safe already or whether the terms have been agreed to?

**Comment by elgatovital** [comment]
yes, if user has agreed to the terms he can proceed to balances screen. Otherwise Get started will be shown. Closing Terms dialog without agreeing will keep user on this Get started screen. See epic for details.

**Comment by elgatovital** [comment]
duplicate
