### ISSUE TITLE
Add safe: check duplicates right away and not after clicking on Next

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#615]
When entering already persisted safe via ENS input dialog or clipboard immediately check whether it is a duplicate.
![image](https://user-images.githubusercontent.com/17750984/82635716-1df95000-9c01-11ea-9d86-d7db4c81596a.png)
![image](https://user-images.githubusercontent.com/17750984/82635721-25205e00-9c01-11ea-9acb-22ad8a2cfd59.png)

**Comment by jpalvarezl** [comment]
Duplicate of https://github.com/gnosis/safe-android/issues/645
