### ISSUE TITLE
Add safe: State persisted when flow interrupted and started again

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#616]
**To Reproduce**
1. Click add safe
2. Enter invalid or duplicate safe
3. Click back
4. Click add safe again
5. Observe that error hint is still visible

**Expected behavior**
New add safe flow should not display remnant of the past

**Screenshots**
![image](https://user-images.githubusercontent.com/17750984/82636012-e50dab00-9c01-11ea-9760-ba18047ae5b4.png)

**Comment by jpalvarezl** [comment]
Could not reproduce. Appears to have been fixed.
