### ISSUE TITLE
Add Safe: Use layouts from Zeplin

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#618]
- Adjust toolbar & layouts according to Zeplin

see Load Safe: https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?seid=5ea9683f752e63bc004d032c

**Comment by jpalvarezl** [comment]
There is no android mockup for this. The destination in the link in the description was either moved or the URL is no longer valid.

**Comment by jpalvarezl** [comment]
I would separate the theme adjusting for the `AddSafe` and `AddSafeName` fragments from the ENS stuff.

**Comment by elgatovital** [comment]
Please check "Load Safe" section in Zeplin
ENS stuff: https://github.com/gnosis/safe-android/issues/621

**Comment by jpalvarezl** [comment]
Button should have disabled colour as long as there is nothing set in the address input text field or if validation fails. 

Validation should happen on address change, not when pressing next.

**Comment by jpalvarezl** [comment]
This issue is outdated and was reported as a bug for which the fix has been merged.
