### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#619]
Screens: 
https://zpl.io/2GJ0163
https://zpl.io/2G0Nnzm

**Comment by biafra23** [comment]
When exactly is the button supposed to show up? Is there an epic, this ticket belongs to?

**Comment by jpalvarezl** [comment]
The SplashScreen is always shown.

Once the user accepts the terms the `Get Started` button is no longer shown and the app starts normally. 

Add artificial delay of 500 milliseconds.

**Comment by jpalvarezl** [comment]
Dismissing the dialog for terms and conditions leaves the user in the splash screen

**Comment by elgatovital** [comment]
https://github.com/gnosis/safe-android/issues/614
