### ISSUE TITLE
[Android]Add Safe: Adjust ENS Input according to Zeplin

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#621]
ENS Input as a separate screen

Design: 
https://app.zeplin.io/project/5e9efc30726e106958cc43de/dashboard?sid=5ea803ae22315c2586ffe2be
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb04120ce51721ee13d2ad3
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb041200f5092194eef5c7c

**Comment by jpalvarezl** [comment]
- Create ENSFragment/viewModel (full screen)
- Adjust the layout for this fragment
- Extend navigation graph to include this destination
- Correct text values for title and button
- Correct error string values

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1- 70
Prod - rinkeby
