### ISSUE TITLE
ETH icon doesn't show up

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#631]
**Describe the bug**
ETH icon doesn't show up for 1 Safe but shows for others

**To Reproduce**
1. I added 1 Safe
2. I added the Safe with address `0x9D2407C6b6c1C307AB54Adb01627Ba0845e3Cddf`
3. The ETH icon shows up for Safe 1 but not for the second Safe
4. I added a 3rd Safe to check and there the icon looks good again

**Expected behavior**
ETH icon shows.

**Screenshots**
![signal-attachment-2020-05-28-135907](https://user-images.githubusercontent.com/1380529/83139354-84dca480-a0ec-11ea-8fb2-07d8d961c7e0.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 10
 - App Version: 1.12.1-xxx-internal

**Comment by jpalvarezl** [comment]
This has been either addressed or fixed. I could not reproduce it.
