### ISSUE TITLE
[Android]App settings: Hide some options from app settings for app

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#633]
The issue relates to the Epic (https://github.com/gnosis/safe/issues/291 )
Some options will not be available for the user in the v1 

**To Reproduce**
1. Open app settings

Current result: There are Fiat currency and Appearance
**Expected behavior**
Fiat currency and Appearance should be hidden as it will not be included in the v1 of the app

2. Go to the Advance settings

**Current result** 
 There is Relay service end point
**Expected behavior**
Please, remove Relay service end-point if it's not used in the app

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1.27-.... internal

**Comment by jpalvarezl** [comment]
comment out the layout items

**Comment by liliya-soroka** [comment]
Verified: 1.12.1- 32
