### ISSUE TITLE
[Android]Bottom Bar- No safes: Transactions tab is not clickable

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#636]
**Describe the bug**
Nothing happens when the transaction tab is clicked in the case when no safe in the app

**To Reproduce**
1. Open the app when no loaded safe
2. Click Transaction 

**Current result** Nothing happens

**Expected behavior**
According to the design - https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb929c14c23207639d1607e
Get started ... test and load Safe Multisig button should be displayed and the transaction tab should be active

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1.-27-g....- internal

**Comment by jpalvarezl** [comment]
This issue has been solved while implementing the transaction list fragment empty state.
