### ISSUE TITLE
[Android]Enter_Safe_Address screen view is different from the expected design 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#637]
**Describe the bug**
Enter_Safe_Address screen view is different from the expected design. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. Click "Load safe multisig" button

**Current result**
Enter_Safe_Address screen view is different from the expected design 

**Expected behaviour**
The page should have almost the same view as on the design:

- [x] Header view - change the header view and background to the same as on the App settings

- [x] Don't use back text for the back link in the header - arrow should be used instead

- [x] Next link should have grey color if the action is not available

- [x] wrong font, size for the header title

- [x] Wrong text in the fields - should be the same as on the design : Enter Safe address

- [x] Enter your Safe Multisig..... text has wrong font, size and it should be in bold

- [x] Don't have a Safe?.... text has wrong font, size and it should be in bold.

- [x] Icon near the link is missed 

**Screenshots**
see the attached screenshot with details 
![image](https://user-images.githubusercontent.com/338622/84024428-90548900-a992-11ea-9e97-bd5e04af034b.png)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1-27-g9...-internal

**Comment by liliya-soroka** [comment]
Reopened:
the page still has a few issues

- [ ] Enter Safe address instead of Enter Safe Address
- [ ] the wrong colour for Next, ...and Enter Safe address text - according to zepling the same color should be used for Next, ... icon and Enter Safe address text: medium_grey
#b2b5b2
- [ ] the frame of the "enter safe.." fields should have #whitesmoke #e8e7e6 colour 
- [ ]Update text fonts on the page 
 Page title Load Safe Multisig - Roboto-Regular
Enter your Safe Multisig address - Roboto-Bold
Enter Safe address - Roboto-Medium
Don't have a safe..... - Roboto-Medium
- [ ] Is it possible to change page background color to the same as on the design snow_white
#ffffff ? The colour of the line between header and body should be changed to the same as on the design ( with gradient)


![image](https://user-images.githubusercontent.com/338622/84657303-c22e9800-af1c-11ea-86fe-4611af435102.png)

**Comment by jpalvarezl** [comment]
> * [ ]  the frame of the "enter safe.." fields should have #whitesmoke #e8e7e6 colour
> * [ ]Update text fonts on the page
>   Page title Load Safe Multisig - Roboto-Regular
>   Enter your Safe Multisig address - Roboto-Bold
>   Enter Safe address - Roboto-Medium
>   Don't have a safe..... - Roboto-Medium

I don't think I would be able to easily make the frame and the hint a different colour as you are suggesting. Well, not at least, having this as a bug rather than a feature request, as that would require a custom view.

**Comment by liliya-soroka** [comment]
verified in 1.12.1-33
