### ISSUE TITLE
Use ... for the long Safe names in the header

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#639]
**Describe the bug**
The very long Safe name looks bad and blocks address viewing partly

**To Reproduce**
1. Add very long name for the safe
2. Go to the Balance and look at the header

**Expected behavior**
I suggest to use ... as in ios app version to keep safe name displaying in one line only. It will not block address 

**Screenshots**
![image](https://user-images.githubusercontent.com/338622/84056861-7da47900-a9bf-11ea-9912-421f5d771d63.png)
![image](https://user-images.githubusercontent.com/338622/84056884-872de100-a9bf-11ea-9784-ef79b8515880.png)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1.27-g...

**Additional context**

**Comment by biafra23** [comment]
@posthnikova Is 16dp a good margin between end of safe name and the icon? As in this example screenshot:

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/68768ba2-a817-42e6-8a59-88d88ef82321)

**Comment by liliya-soroka** [comment]
The issue is fixed .Verified in 1.12.1-28
