### ISSUE TITLE
[Android]Load Safe Multisig: Add name screen - does not meet the design

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#640]
**Describe the bug**
Add name screen - does not meet the design

**To Reproduce**
1. Click Load Safe Multisig
2. Add valid address
3. Open add safe name screen

**Expected behavior**
The page should have the same view as on the design:

- [x] Header background 

- [x] arrow instead of Back link

- [x] text under address should be in bold

- [x] V icon should be in the same line as the first line with address

- [x] V icon on design has a 

- [x] NEXT link - all letters should be upper-case

- [x] Load Safe Multisig should be left aligned

**Screenshots**

![image](https://user-images.githubusercontent.com/338622/84122490-2cd56480-aa41-11ea-88de-7af4f83310ad.png)

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1-27-g...

**Additional context**

**Comment by liliya-soroka** [comment]
The page has the same issues as Enter Dafe address page:

1. Page background: 
snow_white #ffffff colour should be used instead of grey.
Please take into account that according to design the app pages will have two types of background:
-snow_white #ffffff for such cases as Enter Safe name, Enter ENS, Get in touch , transaction details , fiat and etc
- white #f7f5f5 fo such page as transactions list, assets.....

2. Header title should has Roboto-Regular ( not board)

3. Next, Enter name prompt and grey part of the safe address should have the same colour : medium_grey #b2b5b2

4. The frame of the Enter Name field should have whitesmoke
#e8e7e6 colour 

5. I suggest to keep the green frame when the user is starting to type and the name is valid @posthnikova 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/073ecdf9-7794-4d42-babd-55b8708db271)

Device: Huawei P30
Android Version: 10
App Version 1.12.1-32-g...

**Comment by posthnikova** [comment]
> I suggest to keep the green frame when the user is starting to type and the name is valid

@liliya-soroka This is standard behaviour of outlined text field (https://material.io/components/text-fields#outlined-text-field), I don't have objections

**Comment by jpalvarezl** [comment]
As I wrote in the the other issue, having the frame and the hint colour different is not an easy task. It is by no means a bug on our side, it would a be a feature request.

**Comment by liliya-soroka** [comment]
@jpalvarezl , I still see these issues in the 1.12.1-32 app version:

1. Page background:
snow_white #ffffff colour should be used instead of grey.
Please take into account that according to design the app pages will have two types of background:
-snow_white #ffffff for such cases as Enter Safe name, Enter ENS, Get in touch , transaction details , fiat and etc
-white #f7f5f5 fo such page as transactions list, assets.....

2. Header title should has Roboto-Regular ( not bold)

3. Next, Enter name prompt and grey part of the safe address should have the same colour : medium_grey #b2b5b2

Could you check if it's implemented, please?

**Comment by jpalvarezl** [comment]
It is still in dev review. You have one of the issues in "QA in progress" so I didn't touch that yet, but I moved back to in dev review the other. Hopefully today we will have it merged an you can have a look. Sorry for the confusion.

**Comment by liliya-soroka** [comment]
verified in 1.12.1 -33
