### ISSUE TITLE
[Android]Enter Safe Address menu view 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#643]
Questions:
1. Is the title on design is correct for the menu? Could we leave implemented title?
2.  The order of the items in the menu should be changed to the order of the items on the design, right?

### Expected behavior
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ea803ae22315c2586ffe2be
1. Keep title as implemented 
2. Order should be according to the designs, from most used to less used

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7bd08021-55aa-4d0c-9872-07208f8ec525)

### Steps to reproduce the behavior
1. Open Enter address dialog

### Additional information

- Device: Huawei p30
- Android OS version: 10
- Safe app version: 1.12.1-27

**Comment by posthnikova** [comment]
@liliya-soroka
1. The title 'Choose input method' sounds better, let's keep it
2. Order should be according to the designs, from most used to less used

**Comment by liliya-soroka** [comment]
verified.
app version 1.12.1-35
