### ISSUE TITLE
[Android] Load safe page: Address field should contain Identicon  and the whole entered address should be displayed

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#647]
**Describe the bug**
After the address is entered ( any method of entering) there is no address ldenticon and the address is not seen completely 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b7176a26-c1e9-4b43-b19f-7366b4fa6cdd)

**To Reproduce**
1. Go to Load Safe Multisig page
2. Enter the address ( any type of entering : QR code, paste or ENs name)

**Expected behavior**

- [x] show address Identicon
- [x] show the whole address in two lines
- [x] Hide text about new safe if the entered address is valid and the user can go to the next step

**Smartphone (please complete the following information):**
 - Device: Huawei p30
 - Android Version: 10
 - App Version 1.12.1.-28

**Additional context**

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/2510ca71-cb72-429d-834b-e6f348886116)

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/52e81f0a-0552-4c68-8957-9662173e4577)

**Comment by liliya-soroka** [comment]
Reopened:
Current result: The address is not seen completely
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a40d4d49-dd2f-4b10-abaf-d53400c3dcd1)
Expected result: The full address should be seen

app version 1.12.1-63
device : Huawei p30
os version 10

**Comment by jpalvarezl** [comment]
@liliya-soroka I removed all the margin at the end of the address. This doesn't guarantee that the address won't ellipsize on very narrow screens. I made it so that the margins for the "..." icon are symmetrical.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-64
staging, rinkeby
