### ISSUE TITLE
Create firebase app distribution for production (mainnet & rinkeby)

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#648]
### Expected behavior

We want to be able to distribute `io.gnosis.safe` and `io.gnosis.safe.rinkeby` via firebae app distribution. As we do currently for the `io.gnosis.safe.internal` app. 

- Please also check that the google-services.json files work for all 3 apps: internal, production & rinkeby
- we need to make sure that subscribers are notified about new releases. ATM only internal-beta users are notified about new internal releases. Those users who subscribed via the subscription link are not notified

**Comment by elgatovital** [comment]
how to notify users about future updates if they are not part of the internal-beta email list? Can firebase do this?

**Comment by biafra23** [comment]
I found a way to create an invite link, that adds people to the internal-beta group. When they subscribe to this link, they also get future updates. This is the new link: https://appdistribution.firebase.dev/i/df26107cbe76ba89

**Comment by biafra23** [comment]
These will be the invite links for 

Mainnet:
https://appdistribution.firebase.dev/i/401cf2ea8afd6ed8

Rinkeby:
https://appdistribution.firebase.dev/i/8ecc0367c2001086

These links will also add people to teh groups: `mainnet-release` and `rinkeby-release` respectively
