### ISSUE TITLE
[Android] The last added safe is not seen if the list of added safes is very long 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#653]
**Describe the bug**
Many safes fullscreen is not implemented. If there are a lot of safes in the " switch safe" list  the safes at the end of the list are not seen

**To Reproduce**
1. Add more than 10 safes 
2. Open switch safes

** Actual result** 
1. The last added safe is not seen in the list 
2. Many safes fullscreen  view is not implemented
**Expected behavior**
All added safes should be seen in the switch safes list 
Implement many safes fullscreen page
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ea8040e1aa32c247eb02b60

**Screenshots**
![image](https://user-images.githubusercontent.com/338622/84641616-f34e9e80-af03-11ea-88a5-f6e24272b728.png)

**Smartphone (please complete the following information):**
 - Device: Huawei p30
 - Android Version: 10
 - App Version 1.12.1-28

**Additional context**

**Comment by jpalvarezl** [comment]
I am not exactly sure what this issue is about. Does the list not scroll further if there are too many safe? By the looks of the mock, that seems like a full screen list. In which case we need to define a hard limit as to how many is "too many" safes to decide if this requires a full screen list or a pop up bottom sheet dialog.

**Comment by jpalvarezl** [comment]
Just as a reminder, depending on the screen size, too many safe could be as many as 5. This is very screen dependant.

**Comment by biafra23** [comment]
@elgatovital When you enter more than 8 safes, you cannot scroll up the bottom sheet enough to see the last safe.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-45
