### ISSUE TITLE
[Android]Invalid endpoints are displayed on Advanced app settings page 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#657]
**Describe the bug**
If you copy and past endpoint URLs from the app settings->advanced page you will have 404 not found and Not found in the browser for the URLs:
https://rinkeby.infura.io/v3/
https://safe-transaction.staging.gnosisdev.com/api/

**To Reproduce**
1. Go to App settings-> Advanced
2. Copy enpoints URLs
3. Past in browser

**Expected behavior**
The app settings -> advanced should contain valid endpoints URLs

**Smartphone (please complete the following information):**
 - Device: Huawei P30
 - Android Version: 10
 - App Version 1.12.1-32

**Additional context**

**Comment by jpalvarezl** [comment]
The infura URL will not work on a browser. The other one can be fixed.

**Comment by liliya-soroka** [comment]
verified version 1.12.1-34
