### ISSUE TITLE
Binding domain Transaction objects to their ViewHolders

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#663]
**Describe the solution you'd like**
We have already in place the layouts and the logic for allowing a multiple `ViewHolder` `RecyclerView.Adapter`. This task assumes that the direction of the transaction `Incoming/Outgoing` and its status `{Pending, AwaitingConfirmation, AwaitingExecution, Cancelled, Successful, Failed}` is known. Also, the correct domain `Transaction` type is supplied to the bind method `Transfer, Custom, SettingsChange`.

Bind the fields of the classes to their respective view.

`TransactionsViewModel` should map from all the subclasses of `Transaction` to all the subclasses of `TransactionView`

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 54
