### ISSUE TITLE
No default icon for token without icon on the Assets->Coins page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#669]
**Describe the bug**
There is no default icon for the tokens without own icon

**To Reproduce**
1. Load 0x1230B3d59858296A31053C1b8562Ecf89A2f888b safe in the app
2. Go to the assets->Coins
3. look at the Aqer and  Maker tokens icons

**Expected behavior**
The default icon should be used if the custom token doesn't have own icon 
Example from design : https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5e9efc5faa10e47bec5072f5 - MGN token on the screen contains default icon 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cd8810fc-f8df-4c85-930d-2e9f62fc0726)

**Smartphone (please complete the following information):**
 - Device: Huawei p30
 - Android Version: 10
 - App Version 1.12.1-33

**Comment by jpalvarezl** [comment]
Hi @posthnikova , a quick question regarding the placeholder asset for coins. It appears to have a white circle as background included as part of the asset. Is that on purpose, or should it be stripped away?

**Comment by posthnikova** [comment]
The color of background is 'Illustrations background' and the color of objects is 'Low emphasis text'. If there are additional objects you can strip them. 

![image](https://user-images.githubusercontent.com/45787536/85001173-a19c5300-b153-11ea-87a2-464458239b61.png)

**Comment by liliya-soroka** [comment]
verified
app version 1.12.1- 35
