### ISSUE TITLE
Have a proper formatter for dates

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#673]
Duplicate of: #705

We currently have `String.formatBackendDate()` which depends on certain features in the backend response. 

We should have a proper formatter based on DataTimeFormatter

**Comment by elgatovital** [comment]
Parse date as Instance and use DateTimeFormatter to create string of the date

**Comment by elgatovital** [comment]
Have LocalDateTime or Instance in DTO's instead of String for date types

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-77
