### ISSUE TITLE
Add TransactionView subclasses for headers

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#679]
- [x] bind string value (used as title)
- [x] add string values to strings.xml

**Notes for QA:**
This ticket covers the headers in the tx list only. The two headers QUEUE and HISTORY should be shown right above 
Note: the transactions are not yet rendered correctly

Example: 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/c4609a9f-872d-46c0-97a7-10cf7abf9026)

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-45
