### ISSUE TITLE
Transaction list empty state

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#684]
TransactionsViewModel.load:

check if active safe is null

**Comment by jpalvarezl** [comment]
We should implement the empty state in accordance to the design:

https://zpl.io/a35ne9N

**Comment by jpalvarezl** [comment]
@liliya-soroka Just FYI, the test cases with thought about were the following (not sure if we covered everything): 
- Fresh install of the app
- Add safe with TXs should refresh the list
- Removing safe, then no safe is selected, should show empty state
- Removing safe and switching to newly selected safe should show the new list

There is still no error handling in this screen, so sometimes you can run into the situation that something breaks underneath and you get displayed a blank screen. This should change after we've resolved the ticket for it. I am just waiting for feedback from Sasha or Tobi.

**Comment by liliya-soroka** [comment]
according to design the screen transactions list (no safe) should be used  with Load safe button in the case if there is no safe in the wallet https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb929c14c23207639d1607e

https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb2b9fbcea0c078fd77277c  should be used if the safe is added but the safe doesn't contain any transaction

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-46
