### ISSUE TITLE
[Android] Cover all cases for TransferFrom ( ERC20, ERC721)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#688]
Bug description
Not all cases are covered. The incoming transaction is displayed even when the safe is "from" or "sender"
Steps To Reproduce
1. Safe X was approved to send tokens from Address Y
2. Safe X create custom transaction using TransferFrom Address Y to address Z

Expected Result
Check the doc to cover all cases (https://docs.google.com/document/d/1vhTu5NbB-6m8nE3cqTS3bRONigPO3NA5YkJqNTA6AOk/edit?usp=sharing)
Screenshots

Device & App version

Device/OS: Google Pixel 4 /10
App version: 1.12.1-45
Additional info
(Optional)

**Comment by jpalvarezl** [comment]
Classification does not happen in the app anymore. I would guess this is probably fixed by the gateway. If it resurfaces it's probably a gateway bug.
