### ISSUE TITLE
[Android] Wrong format is used for amount on Balance page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#689]
**Describe the bug**
A clear and concise description of what the bug is.3 number with rounding up are displayed after decimal symbols 
**To Reproduce**
1. Go to balance page for 0x1230B3d59858296A31053C1b8562Ecf89A2f888b safe
2. look at ETH and Tokens amounts

**Expected behavior**
Please, make sure that the amount is implemented according to https://github.com/gnosis/safe/wiki/How-to-format-amounts

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - Android Version: 10
 - App Version 1.12.1-42

**Comment by elgatovital** [comment]
create separate formatters for coins & fiat due to different formatting rules

**Comment by elgatovital** [comment]
clarify if we need to follow https://github.com/gnosis/safe/wiki/How-to-format-amounts strictly or if we need to use localized decimal separators

**Comment by jpalvarezl** [comment]
We should also update the `NotificationManager` to use the formatter that will be implemented in this task #853

**Comment by liliya-soroka** [comment]
Reopened:
Not covered rules:
1) From 10,000,000 No Decimals until **99,999,999**
Then Use 10.001M until 999.999M
safe: 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d43c587d-3e3a-47a4-a31c-5e7b78ba5617)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 ( 10)
