### ISSUE TITLE
[Android] Wrong amount in the outgoing transaction for ERC721 tokens ( CryptoKitties #650)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#690]
**Bug description**
The amount of outgoing transaction = -650 CK instead of 1 CK
**Steps To Reproduce**
1. Load Safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. The safe has CryptoKitties #650 with amount 1 CK
**Expected Result**
The correct amount should be displayed on UI
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/31090c00-db76-4960-93a0-464e75f11d00)
**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - Android Version: 10
 - App Version 1.12.1-42

**Additional context**

**Comment by jpalvarezl** [comment]
Fixed by the gateway integration.
