### ISSUE TITLE
Handle errors & reloads

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#697]
Notify user about internet connection & data loading related issues

see API errors handling doc: https://docs.google.com/spreadsheets/d/1U_cM0Tg3WecJ8XTcoP2VK1ZiCXytAIlm0Y0kdorp4J4/edit#gid=0

network requests & no internet connection: https://github.com/gnosis/safe/wiki/Errors%2C-Network-requests-and-no-internet-connection

notification example screen: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ebbb3f2036ca578104c1a81

slack discussion: https://gnosisinc.slack.com/archives/C63LQTGNB/p1592296491004400

**Comment by elgatovital** [comment]
Split into no internet error & other errors

**Comment by elgatovital** [comment]
error state for coins: https://zpl.io/VDJA5P3

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 105
