### ISSUE TITLE
[Android] Awaiting executing status is missing in transactions list Queue

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#707]
**Describe the bug**
There is no Awaiting executing status in the Queue when the transaction is approved by all users but was not executed

**To Reproduce**
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Check transaction with nonce 113 in the Queue

**Expected behavior**
The status Awaiting executing should be used if the transaction is approved by the required number of owners but is not executed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/00b3301d-fe52-4968-808a-486d3e092d3b)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1-47

**Additional context**

**Comment by biafra23** [comment]
This should be fixed in the newest internal build.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1- 52

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-52
