### ISSUE TITLE
isSafeValid using blockchain for verification

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#708]
**Is your feature request related to a problem? Please describe.**
The iOS app consults the transaction service to determine whether a safe is valid whereas the Android app uses a `getStorageAt` call on the safe and checks for an accepted master copy address.

**Describe the solution you'd like**
We should unify the verification process with iOS using the `/safes/{address}/` endpoint to retrieve said verification. If the response is anything but a 200 HTTP code, the safe is to be considered invalid.

**Describe alternatives you've considered**
As valid as the current method in the Android app is, we should still have a unified behaviour so that apps behave consistently across platforms.

**Comment by liliya-soroka** [comment]
To verify the issue the load safe flow should be retested

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0(17)
