### ISSUE TITLE
[iOS/Android] Crash-free reports require Google Analytics

### ISSUE THREAD

**Issue by sche** [gnosis/safe-android#709]
While integrating Crashlytics I noticed this:

![Screenshot 2020-07-08 at 12.13.32.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/48d05f45-07a7-4f05-aaa4-dd74215d613d)

It seems like we will need to integrate Google Analytics if we want to track the percentage of crash-free users.

**Comment by sche** [comment]
Added it by mistake to the Android repo. I will leave it here as it is for both platforms

**Comment by biafra23** [comment]
@sche Is this still open? Where do I find this message?

**Comment by DmitryBespalov** [comment]
too old
