### ISSUE TITLE
[Android] Settings transaction doesn't have title in Queue section

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#712]
**Describe the bug**
Settings transaction doesn't have title in Queue section

**To Reproduce**
1. Add or remove an owner in the safe where a few approves are required
2. Check transaction view in the Queue

**Expected behavior**
The settings transaction should have title depends on the function name

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b025dd70-48c1-4723-8b7e-2ec8ae061342)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version: dev version 0.4.2 -alpha-debug

**Additional context**

**Comment by biafra23** [comment]
See 0x1C8b9B78e3085866521FE206fa4c1a67F49f153A for an example.

**Comment by biafra23** [comment]
This is, what is missing in TransactionViewHolderFactory.kt to fix this bug:
 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/0ea9e87a-b210-48ba-bce9-858d84d1b0aa)

**Comment by biafra23** [comment]
For a fix see branch `bug/716-712`

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-76
