### ISSUE TITLE
[Android]Multisig reject transaction displays as incoming and nonce is missing in original transaction in Queue

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#714]
**Describe the bug**
When the one of the owners rejects transaction the incoming transaction appears in the transactions list in Queue

**To Reproduce**
1. Create transaction in web app in the safe with a few owners and a few confirmations
2. One of the owners rejects the transaction
3. Open transactions list in the mobile app for the same safe

**Expected behavior**
Multisig reject transaction should be displayed as outgoing

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f7a1ac0c-2de4-4ea1-85a4-18ccca96d375)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 0.4.2 - alpha -debug

**Additional context**

**Comment by biafra23** [comment]
https://safe-team.staging.gnosisdev.com/app/#/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/transactions has several unconfirmed txs which do not have a nonce in the android apps queued section.

See also: https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/all-transactions/?limit=100

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-76
