### ISSUE TITLE
[Android] Green colour is lost in number of confirmations when the tx is approved but not executed

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#715]
**Describe the bug**
Green color is lost in number of confirmations when the tx is approved but not executed
Color of Number of confirmations should not depend on the transaction type

**To Reproduce**
1. Create transaction
2. Approve the transaction by the required number of owners but don't execute the transaction
3. Check transactions list in the mobile app for the same safe

**Expected behavior**
Design https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5eb1234bf944bdb12a3fd89c

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2a9eefab-9e40-478c-a9d3-f746034b4e6f)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 0.4.2 - alpha -debug

**Additional context**

**Comment by biafra23** [comment]
I am not sure how to reproduce this. But there is a related bug:

Queued custom tx and change mastercopy show the "n out of m" confirmations test in the wrong grey, when threshold its not met.

![Screenshot_20200710-102735 Kopie.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/668c260d-f912-4b09-ba88-72ad6c2e0ed5)

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-75
