### ISSUE TITLE
[Android]Nonce is lost in the custom tx in Queue ( Update mastercopy in web app)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#716]
**Describe the bug**
The custom transaction created using Update Safe with new contract version doesn't have nonce in Queue section

**To Reproduce**
Precondition:
safe with a few confirmations

1. Update safe with old master copy ( contract interaction  to= safe , ABI = mastercopy, mastercopy address= 0xb6029EA3B2c51D09a50B53CA8012FeEB05bDa35A)
2. Go to the web app -> settings for the updated safe
3. Click update safe with new contract version
4. Check transactions list -> Queue

**Expected behavior**
The nonce should be displayed if the custom transaction has it

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7a1c71e4-21ca-4216-94c9-b8938be0e6cb)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 0.4.2-alpha-debug

**Additional context**

**Comment by biafra23** [comment]
The fix: 

```
nonce.text = viewTransfer.nonce
```
needs to be added to all *QueuedViewHolder classes in TransactionViewHolderFactory.kt

**Comment by biafra23** [comment]
For a fix see branch `bug/716-712`

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-76
