### ISSUE TITLE
[Android]DefaultFallbackHandler title is used even for unknow fallback handlers

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#719]
**Describe the bug**
DefaultFallbackHandler title is used even for unknow fallback handlers

**To Reproduce**
1. Change FallBack Handler to any address ( I used one of the owner's address)
2. Check created transaction

**Expected behavior**
"Unknown" should be used if it does not default fallback handler
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/374142d0-bd96-4c9a-a44f-0111dd23b835)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 0.4.2 - alpha-debug

**Additional context**

**Comment by biafra23** [comment]
The default fallback handler address is 0xd5D82B6aDDc9027B22dCA772Aa68D5d74cdBdF44 and it is called DEFAULT_FALLBACK_HANDLER in the android app.

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 -1239
