### ISSUE TITLE
[Android]Settings transactions don't have a nonce in Queue

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#720]
**Describe the bug**
Settings transactions don't have a nonce in Queue

**To Reproduce**
1. Create settings transaction that required confirmation
2. Check Queue in the mobile app

**Expected behavior**
If the transaction has a nonce it should be displayed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/933f30ab-a347-4d74-8795-a37c31b7afc4)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 0.4.2 - alpha-debug

**Additional context**

**Comment by biafra23** [comment]
Should be solved by #768

**Comment by liliya-soroka** [comment]
verified
app version 1.12.1-75
