### ISSUE TITLE
[Android]Wrong amount formatting for ERC20 (the number of decimals are not taken into account)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#726]
**Describe the bug**
The number of symbols after decimals are not taken into account  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to liltestsafe
2. Check the transaction with the nonce 117

**Expected behavior**
The number of symbols after decimals are not taken into account for the ERC20

**Screenshots**
Android :
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/544fc85f-b945-4415-962e-4abeff698a8a)

Expected result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1a44764d-9bfb-4bb5-bba3-c4efa99c0c67)

**Smartphone (please complete the following information):**
 - Device: pixel 4
 - Android Version: 10
 - App Version 1.12.1- 53

**Additional context**

**Comment by liliya-soroka** [comment]
Reopened for prod rinkeby

Prod Rinkeby 1.12.1-70

**Comment by elgatovital** [comment]
prod backend is not deployed yet - this is a backend problem. I have opened an issue for this, but it was closed https://github.com/gnosis/safe-transaction-service/issues/122 We need updated and deployed prod service for this feature to work @rmeissner @Uxio0 @liliya-soroka

**Comment by Uxio0** [comment]
@elgatovital That was not an issue for deploying a new version of the service, it was an issue talking about a missing feature that was not deployed yet. I was not aware that this was required now. I won't deploy a new version of the service on Friday but I will do it on Monday, does that work for you? 🙂

**Comment by elgatovital** [comment]
@Uxio0 yes, thank you

**Comment by liliya-soroka** [comment]
The back-en update did not helped
The issue still exist
1.12.1-72 9(576)

**Comment by biafra23** [comment]
@liliya-soroka I am sorry! I didn't mean to put this in "Ready for QA".

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-86
