### ISSUE TITLE
Safe Settings: Edit safe local name

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#728]
**Describe the solution you'd like**
The local name field in the Safe Settings screen should be clickable and lead to the safe name setting screen (same as when adding a safe).

Upon back navigation, the field should display updated.

**Comment by liliya-soroka** [comment]
closed as duplicate of https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/750

App version 1.12.1 -72 (576)
