### ISSUE TITLE
[Android] Confirm safe removing dialog - local device language is used for cancel link

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#730]
**Describe the bug**
The local device language is used instead of English in the confirm dialogue for Cancel option

**To Reproduce**
1. Change local device language to diff from the English
2. Open safe settings
3. Click Remove safe

**Expected behavior**
The English language should be used in the gnosis mobile app all over the app

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b93b5b0f-5395-46fb-a41b-a8e68d8de37e)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1-59

**Additional context**

**Comment by rmeissner** [comment]
This is something we should probably define as a general assumption and not only for this case. (this is probably because the android resource was used which is available in most languages)

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 -1174rc
