### ISSUE TITLE
[Android] Safe settings-> Advanced: Module name is missing

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#733]
**Describe the bug**
Enabled modules don't have names or unknown as a name

**To Reproduce**
1. Load liltestsafe.eth safe
2. Open safe settings-> Advanced

**Expected behavior**
Requirements: 
addresses of enabled modules
"Unknown" or module name

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a9399f5a-f777-4bf7-8d1a-600a5899b254)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1-59

**Additional context**

**Comment by jpalvarezl** [comment]
There is currently no way for us to retrieve a name for this. I asked iOS and replicated their behavirour as I thought they had already passed the QA. 
 
@liliya-soroka there is really no way, to the best of my knowledge, to solve this yet. I would personally close this issue, but if you have a clue on how to act on this, we could try to fix it.

**Comment by rmeissner** [comment]
I would also make this a Minor, as @jpalvarezl mentioned we did not define a source for the names yet

**Comment by DmitryBespalov** [comment]
@jpalvarezl @rmeissner after looking at different safes and their modules, I'd put "Unknown" for any address that we see. (OK'd with Tobi)

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0-1862
