### ISSUE TITLE
Snackbar should be on top of bottom bar

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#742]
- Device:
- Android OS version:

**Comment by tschubotz** [comment]
Is this a bug or which Epic is this related to?

**Comment by tschubotz** [comment]
This sounds like a bug, right? I'll mark it as such. Let me know if objections. @elgatovital @jpalvarezl

**Comment by jpalvarezl** [comment]
@tschubotz 
> Is this a bug or which Epic is this related to?

This was found by Richard back in the Kyoto sprint I believe. It blocks the bottom navigation bar for as long as the snackbar is displayed, AFAIK.

**Comment by liliya-soroka** [comment]
Verified
The bottom navigation bar is not blocked with snackbar
app version 1.12.1 - 98
