### ISSUE TITLE
Wrong balances

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#747]
**Describe the bug**
The balances on the assets tab are wrong

**To Reproduce**
1. Clean install 
2. Add `0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6`

Now I see:
- 1.383 ETH
- 650.608 dAI
- 295.148 SAI

**Expected behavior**
Balances like here: https://gnosis-safe.io/app/#/safes/0xA063Cb7CFd8E57c30c788A0572CBbf2129ae56B6/balances

**Screenshots**
I'm not allowed to take screenshots

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 10
 - App Version: 1.12.1-65-gf499f6f1 (mainnet)

**Comment by tschubotz** [comment]
The same is reproducible with the Rinkeby build and e.g. `0xaE3c91c89153DEaC332Ab7BBd167164978638c30` - balances are completely wrong

**Comment by liliya-soroka** [comment]
Verified
Prod Rinkeby and Mainnet: app version 1.12.1-70
