### ISSUE TITLE
Transactions tab is empty

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#748]
**Describe the bug**
After loading a Safe, I don't see any transactions in the list

**To Reproduce**
1. Clean install
2. Load `0xaE3c91c89153DEaC332Ab7BBd167164978638c30`
3. Go to tx tab
-> Empty

**Expected behavior**
See transactions

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: Android 10
 - App Version: 1.12.1-65-gf...-rinkeby

**Additional context**
- The same happens to be on the mainnet build as well with any Safe I add.

**Comment by liliya-soroka** [comment]
Reopened:
still doesn't work for prod rinkeby and prod mainnet apps
app version 1.12.1-67

**Comment by liliya-soroka** [comment]
Verified
Prod Rinkeby and Mainnet 
app version 1.12.1-70
