### ISSUE TITLE
[Android] Spaces are not escaped in the Edit safe name and name can be left empty

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#757]
**Describe the bug**
Spaces are not escaped in the Edit safe name. 

**To Reproduce**
1. Go to Safe settings
2. Edit name
3. Enter spaces + letter at the end or save empty name
4. Save changes

**Expected behavior**
The spaces should be escaped as in the load safe flow and it should not be possible to leave the name empty

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1-71

**Additional context**

**Comment by biafra23** [comment]
@liliya-soroka 
I cannot reproduce the error, that the user can save the safe, if the name is empty. The NEXT button is only enabled if the name contains non whitspaces. Is it possible to safe the name without using the NEXT button?

**Comment by liliya-soroka** [comment]
Verified
app version 2.1.0 -1160
