### ISSUE TITLE
[Android] Safe address: diff types of errors are used for wrong safe address on the load safe page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#760]
**Describe the bug**
Snack bar and the red error message is used for the wrong address

**To Reproduce**
1st situation:
1. Go load safe page
2. Past owner address from clipboard
Actual result: Safe not found red error appears under the field and the field is empty
Expected result: the pasted data should be displayed in the safe address field

2nd situation:
1. Go load safe page
2. Past from clipboard, any text ( not ethereum address)

**Actual result:** Snack bar with the Invalid etherium address notification appears

**Expected result:**  The red error message " The address is malformed. Please provide an Ethereum address" should be displayed with the pasted wrong information 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4, Huawei p30
 - Android Version: 10
 - App Version 1.12.1-72 (576)

**Additional context**

**Comment by elgatovital** [comment]
> Expected result: The red error message " The address is malformed. Please provide an Ethereum address" should be displayed with the pasted wrong information
You potentially could paste huge chunks of text. Should it be then ellipsized or should we stretch the input field? 
What about blockie? Currently, we generate it only for eth addresses. It is unclear what to do with random text. How is this use-case handled on iOS? @DmitryBespalov 
On android we show snackbar with an error message and leave the input field empty for every input, which is not an ethereum address. I would prefer to just adjust the error message of the snackbar and not to display random text in the input field.
@tschubotz @liliya-soroka

**Comment by liliya-soroka** [comment]
Verified
app version 2.6.0 -1534rc
The errors have the same view : under the enter field in red color
