### ISSUE TITLE
[Android] ERC721: the amount has wrong view with wrong symbol ( outgoing 1835 ERC20, incoming +1NFT)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#764]
**Describe the bug**
the amount has wrong view with wrong symbol ( outgoing 1835 ERC20, incoming +1NFT) instead of 1 erc721 symbol
CK and other know ERC721 were used for testing
**To Reproduce**
1. Go to '0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open transactions list
3. see 158 transaction ( it was known CK)

**Expected behavior**
The correct amount and ERC721 symbol should be displayed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/61948ad9-53eb-4500-a360-793e1c161e37)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version Prod Rinkeby 1.12.1.-72 (576)

**Additional context**

**Comment by liliya-soroka** [comment]
id is used instead of 1 for CriptoKitty  without title
Executed tx:  -1264 CK
Canceled, panding, sometime after executing : -1835 ERC20

App version 1.12.1-72 (576) after back-end update

**Comment by tschubotz** [comment]
Just marked this a `major` per https://gnosisinc.slack.com/archives/C63LQTGNB/p1595842153003400?thread_ts=1595839871.487800&cid=C63LQTGNB

**Comment by tschubotz** [comment]
This expected to be resolved by the new client gateway on Android.

**Comment by jpalvarezl** [comment]
I think this issue can be closed. I believed it's solved.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-86
