### ISSUE TITLE
After switching tabs (balances to settings back to balances) all data is gone

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#772]
Extracted from #624 

**Describe the bug**
After switching tabs (balances to settings back to balances) all data is gone

**To Reproduce**
1. Tab on "transactions"
2. Tab on Assets
3. See error

**Expected behavior**
TBD

**Comment by elgatovital** [comment]
as agreed in https://docs.google.com/document/d/12bRFzVZKcr4thB10VpHQUTjDk_ftNCV-aofAvn0P5v0/edit we reload all data when tab is opened
