### ISSUE TITLE
Use same signing key for app distribution & playstore

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#775]
Using same signing key will enable testers to get updates from playstore.
Keep in mind: we might want to switch to app bundles at some point to support dynamic features. In this case we need to use two keys: upload key & signing key (used by google to sign apk's generated from app bundle)

- [x] Create / Update keystores
- [x] Adjust buildkite pipelines

Dependencies:
playstore app project has to be created in order to configure upload & signing keys

**Comment by liliya-soroka** [comment]
@tschubotz , just to confirm the expected result we agreed on:
The users with beta version will need to uninstall beta version and install the google play public release 2.0.0 version .
It will not be possible to update beta version to the public release version without uninstalling

**Comment by tschubotz** [comment]
That's correct.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -98
