### ISSUE TITLE
Migrate tx list to the gateway

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#776]
- [x] Add new endpoint
- [x] Adjust models
- [x] Adjust tests
- [ ] ~Remove tx service~

**Comment by biafra23** [comment]
We cannot remove the old tx service (yet), because we still need it for balances

**Comment by liliya-soroka** [comment]
The list of the issues related to the migration to the client gateway and transaction list :
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/782

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-82
