### ISSUE TITLE
Handling gracefully new polymorphic types

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#787]
**Describe the bug**
When the gateway deployed changes for `Creation` type of transaction for the transaction list endpoint, the app throws and loses a page of data at the end of it. 

**To Reproduce**
Use a build of the app that doesn't handle `Creation` transaction types. Load the list and notice that paging shows an error state at the end of the list.

**Expected behavior**
The app should not throw or at least catch any JSON parsing exception. This situation should either be handled by a default type for each concretisation. Or instead of throwing we should simply log.

**Comment by tschubotz** [comment]
@jpalvarezl @elgatovital Do I understand correctly that this one is also about the creation tx? Does it lead to a crash in the app currentrly? If so, I would mark this as `critical`  if not, I would go for `minor` bug prio or what do you think? I'm having some trouble assessing the prio :)

**Comment by jpalvarezl** [comment]
@tschubotz no crashes, but this will cause the UI to not display any data. I think `Minor` for this one is spot on, this will only come up when we have new TX types coming from the gateway (as in Custom, Transfer, Settings change or Creation). I would maybe re-assess it to higher priority after the public release.

**Comment by liliya-soroka** [comment]
Verified, no error at the end of the list in the prod apps
app version 1.12.1-110
