### ISSUE TITLE
Disable Kotlin Synthetics

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#789]
We decided to go with ViewwBindings instead of Kotlin synthetics. Some classes still use synthetics.

Synthetics can be disabled via 

```
androidExtensions {
    features = ["parcelize"]
}
```

in app/build.gradle. In doing so, the build will break for several files still using synthetics. Those need to be migrated to ViewBindings. 

```
e: app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
e: app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameFragment.kt
e: app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
e: app/src/main/java/io/gnosis/safe/utils/DialogBuilders.kt
```

**Comment by biafra23** [comment]
No sure, this can be QAed. Maybe by checking that the changed parts didn't break:

- Deleting a safe shows the same confirmation Dialog as before
- Adding a safe show the same bottom sheet and it still works

**Comment by liliya-soroka** [comment]
Verified
app version 2.1.0 -1172
