### ISSUE TITLE
Provide build for QA that allows to intercept TLS traffic with MITM proxy

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#801]
ATM we apparently prevent TLS sniffing. @liliya-soroka needs a build for testing, that allows this.

**Comment by biafra23** [comment]
APK has been send to @Liliya for review

**Comment by biafra23** [comment]
c2bf06c2540fd0dc3779fdf79b88f24e080cc0f0 contains the changes to dsisable SSL pinning for future reference

**Comment by liliya-soroka** [comment]
Verified
app version 703
