### ISSUE TITLE
asEthereumAddressChecksumString might be too expensive to run on the main thread

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#805]
1. Do we need to checksum ellipsized displays of safe addresses?
2. Should we cache the result after we calculated it once?

**Comment by jpalvarezl** [comment]
> `char in '0'..'9' -> char`

We should also try not to create new instances of arrays on every iteration of the enclosing loop. 

Good catch 👍 , this could really mess up the rendering for recycler views.

**Comment by DmitryBespalov** [comment]
@elgatovital @biafra23 please update the status
