### ISSUE TITLE
[Android] Navigation bar is scrollable on tx details

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#806]
**Describe the bug**
The navigation bar is hidden when the tx details page is scrolled down

**To Reproduce**
1. Go to tx details page with a lot of information on the page
2. Scroll down

**Expected behavior**
The navigation bar should not be scrollable 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c5d7b264-aa35-40a2-84f2-2dd7ac0dd9a0)

**Smartphone (please complete the following information):**
 - Device: pixel 4
 - Android Version: 10
 - App Version 1.12.1- 93

**Additional context**

**Comment by elgatovital** [comment]
it's a common thing on android to have a scrollable toolbar for screens with long content. I suggest leave it as is @tschubotz @posthnikova

**Comment by posthnikova** [comment]
@elgatovital The guidelines allow the nav bar to disappear https://material.io/components/app-bars-top#behavior. Let's keep it.

**Comment by tschubotz** [comment]
I'm fine with this either way, happy to let you decide.

**Comment by liliya-soroka** [comment]
@posthnikova and @tschubotz , may I close the issue as won't fix?
My personal opinion:  As a user, I don't like that I need to scroll up from the transaction detail page to use the navigation bar. It's good that I can swap to come back to the transactions list but without swapping I need to scroll the transaction details twice ( down and up) to come back to the transactions list. Especially taking into account that the top bar is not scrollable on transactions details, balance and etc.

**Comment by posthnikova** [comment]
@liliya-soroka I generally prefer fixed nav bar but material guidelines allow the nav bar to scroll. Let's fix it later.

**Comment by tschubotz** [comment]
Agree with Sasha, but lets close this issue as won't fix 👍

**Comment by liliya-soroka** [comment]
closed as won't fix
