### ISSUE TITLE
[Android]TX details: Typo: "Canceled" instead if "Cancelled" 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#819]
**Describe the bug**
Typo: "Canceled" instead if "Cancelled" 

**To Reproduce**
1. Go to 0x938bae50a210b80EA233112800Cd5Bc2e7644300 safe
2. Open cancelled tx

**Expected behavior**
two ll should be in the cancelled state name in confirm block 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3cf6ce0a-615b-46ec-b3e4-100893104bf4)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1 - 93

**Additional context**

**Comment by biafra23** [comment]
How do we know "Cancelled" is the correct spelling?

Miriam Webster on this Subject: "... both canceled and cancelled are acceptable for the past tense..." 

Source: https://www.merriam-webster.com/words-at-play/canceled-or-cancelled

**Comment by liliya-soroka** [comment]
I offer to keep Cancelled as we are using it in other places in the android app , ios app and web app

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
