### ISSUE TITLE
[Android] Pull to refresh doesn't work on the tx details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#820]
**Describe the bug**
The transaction details page is not updated on pull to refresh.
The icon that there is pull to refresh is displayed but the content is not updated

**To Reproduce**
1. Create transaction but don't execute it
2. Open transaction details on android device
3. Execute transaction on web
4. Pull to refresh the transaction details page when the notification about success tx is received on android ( I checked after the notification was received and in 5 min after the status was updated on web and ios app

**Expected behavior**
There should be pull to refresh on the transaction details page for content updating

**Smartphone (please complete the following information):**
 - Device: pixel 4
 - Android Version: 10
 - App Version 1.12.1-93

**Additional context**

**Comment by jpalvarezl** [comment]
The gateway associated issue is https://github.com/gnosis/safe-client-gateway/issues/124 . Once this is closed this can be tested again.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 93
