### ISSUE TITLE
[Android]The transactions stuck in the incorrect state on UI for 10 min or till the new tx is created

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#821]
Should be fixed by client gateway with issue: https://github.com/gnosis/safe-client-gateway/issues/124

**Describe the bug**
2 issues with states:
1. The both original and rejection transactions stuck in cancelled state for more than  1 min ( it may be longer than 1 min) till the new transaction is created
2. Cancelled rejection transaction has awaiting executing state on transaction details for 10 min. At the same time the transaction has state cancelled in transactions list

I am searching for the exact steps. It seems that the issue appears if the rejection transaction had been opened in awaiting confirmation state before the original tx was executed and the state is cashed for 10 min. Restart the app and opening the safe transaction on another device doesn't help in details refreshing

**To Reproduce**( searching for steps)
Issue 1
1. Update transactions list when both txs in cancelled state ( quickly after original tx execution)
2. Pull to refresh tx list 
Current result: Both transactions have cancelled state for a long time ( more than 1 min)

Issue 2 with cancelled tx state on the transaction details
1. Create transaction ( a few confirmations should be required)
2. One owner rejects tx 
3. Open rejection tx in the mobile app
4. Confirm and execute the original transaction
5. Refresh transaction list 
6. Open cancelled rejection tx
Current result: rejection tx has awaiting confirmation state on transaction details
**Expected behavior**

**Video links**
https://drive.google.com/file/d/1C4JXX3kMyrNgN_0CoJtK3pstuP5VD7jW/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1 -93
- Safe : 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
- Nonce 187

**Comment by liliya-soroka** [comment]
@tschubotz , I think the first point is not critical but the second is confusing for me as an user

**Comment by tschubotz** [comment]
So transaction list and transaction details are not in sync? That's odd yes. 10 minutes is also a weird delay time. I think we should investigate, yes.

**Comment by biafra23** [comment]
@rmeissner What is the Link to the ticket in the client gateway project?

**Comment by jpalvarezl** [comment]
This will be fixed here https://github.com/gnosis/safe-client-gateway/issues/124

After talking to @rmeissner the apps shouldn't change we will fix this in the gateway. This is an edge case, as our interfaces don't allow issuing multiple TXs with the same nonce (with the exception of cancellation transactions, of course).

**Comment by liliya-soroka** [comment]
The issue should be retested as soon as https://github.com/gnosis/safe-client-gateway/issues/129 client-gateway task is done - not included into the public release
@tschubotz , I will change the issue priority from Major to minor and the issue will be kept in Ready for QA till the client-gateway task is implemented

**Comment by tschubotz** [comment]
sounds good to me 👌

**Comment by rmeissner** [comment]
As @jpalvarezl wrote the issue will be fixed with gnosis/safe-client-gateway#124 (not 129)

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
