### ISSUE TITLE
[Android] Send app for scanning pop-up appears during prod mainnet app installation/updating

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#826]
**Describe the bug**
Send app for scanning pop-up appears during prod mainnet app installation/updating
There is no such issue for rinkeby prod app

**To Reproduce**
1. Install prod mainnet app

**Expected behavior**
There  should not be any confusing scanning /security popups on app install

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b0397f3a-8433-4472-8421-644104b4a9b0)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a384e1d7-a82b-4c41-9ccf-b7edd54ef4e4)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1 - 94

**Additional context**

**Comment by tschubotz** [comment]
I set this to minor as it won't be a problem for the store release (right @elgatovital ?) 

Still, even for the beta app, it's quite annoying that this popup appears. Does this have to do with signing keys? @biafra23 @elgatovital @jpalvarezl

**Comment by elgatovital** [comment]
Yes, this happens because we changed our upload key. We need to publish our new app at Google Play Store and then if the problem still persists we will submit an appeal to the Play Protect
https://support.google.com/googleplay/android-developer/contact/protectappeals

**Comment by elgatovital** [comment]
should be resolved now

**Comment by liliya-soroka** [comment]
verified
app version 2.0.0 (17)
