### ISSUE TITLE
TX list shows empty error screen on reload (if there is an error)

### ISSUE THREAD

**Issue by biafra23** [gnosis/safe-android#828]
**Describe the bug**
When the user already loaded a tx list and then swipes to reload and  his device doent have internet the already shown data should not be repleaced by the error state "Data cannot be loaded"
 
**To Reproduce**
1. Go to tx list
2. Put phone into airplane mode
3. Swipe down to reload list
4. "Data cannot be loaded" is shown instead of the already shown data

**Expected behavior**
The already shown data should not be repleaced by the empty erro scren

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
