### ISSUE TITLE
[Android]Crash when the tx details is opened ( searching for the steps)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#830]
**Describe the bug**
The app is crashed when transaction details page is opened ( I scrolled transactions list before tx details opening??)
Firebase error -https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/a9b74ced91055fd3553839da3c744f10?time=last-seven-days&sessionId=

**To Reproduce**
1. Go txs list
2. Scroll it
3. Open transaction details ( wait for a sec)

**Expected behavior**
The app should not be crashed

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1 - 94 . Release candidate 819
- Prod, mainnet
- Safe 0x8675B754342754A30A2AeF474D114d8460bca19b

**Additional context**

**Comment by biafra23** [comment]
@liliya-soroka Unfortunately it is not that easy to reproduce. Do you remember which safe was active, when this occured?

**Comment by biafra23** [comment]
828 is also affected
830 is not

**Comment by biafra23** [comment]
843 is affected. I needed several retries to expose the bug. 
It is easier to reproduce in general after restarting the app.

**Comment by biafra23** [comment]
This happens because the binding from the TransactionListFragment is set to null, when onDestroyView() is called and after that binding is accessed in Line 54 of TransactionListFragment.
