### ISSUE TITLE
[Android]Transactions list is not updated for 10 min if it was updated with pull to refresh before changes from back-end: txs from Queue is not moved to History

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#835]
**Describe the bug**
1. Already executed txs are displayed as awaiting confirmation and awaiting executing for 10 min on transaction list after it was actually executed ( executed state confirmed on web and ios) if the transactions list was opened when txs had statuses awaiting confirmation/awaiting execution
2. Queue section with created tx doesn't appear when the new tx is created if the transaction list was updated with pull to refresh right before tx creation 
Reproduced both on staging and prod 
staging safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
prod safe 0x8675B754342754A30A2AeF474D114d8460bca19b

**To Reproduce**
1. Go to the safe in android app and on web
2. Create tx that requires confirmation from a few owners
3. Check mobile app to make sure that tx appears in Queue
4. Reject tx as owner 
5. Pull to refresh txs list in mobile app
Current result: rejection tx doesn't appear for 10 min ( was reproduced on prod)

6. Wait till both transactions are displayed in the Queue in mobile app
7. Confirm original tx without executing it
8. Pull to Refresh txs list in mobile app
Current result: The states are updated correctly

9. Execute original tx on web
10 Pull to refresh txs list

Current result: The original and rejection tx states are not updated for 10 min and not moved to History section

**Expected behavior**
The txs list should be updated on pull to refresh

**Smartphone (please complete the following information):**
 - Device: Pixel 4, Huawei P30
 - Android Version: 10.1
 - App Version 1.12.1-98 
- client gateway version 1.0.0 build 168

**Additional context**

**Comment by jpalvarezl** [comment]
I tried reproducing this bug with no success in staging/rinkeby. The cancellation transaction was shown (basically step 5 didn't go as according to the description of this issue.) 

The states appear to be updated correctly for me. I think yesterday @rmeissner was updating some webhook tokens that could have had an impact on this. I opened an issue in the client gateway to keep track of this anyway (https://github.com/gnosis/safe-client-gateway/issues/131) 

@liliya-soroka If you find at some point of the day you have spare time, maybe give it another try. I personally could not reproduce the error :(

**Comment by jpalvarezl** [comment]
I have just tried to reproduce this bug in prod/rinkeby with no success. The Image below was taken right after submitting the cancellation transaction in web and pulling down to refresh in the app: 

<img width="384" alt="Screenshot 2020-08-28 at 09 16 07" src="https://user-images.githubusercontent.com/11056031/91532786-1e476c80-e90f-11ea-9d13-c1554ec45bc2.png">

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
