### ISSUE TITLE
Error handling: The error doesn't appears after safe switching on safe settings page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#838]
**Describe the bug**
There is no error message after safe switching on safe settings page. At the same time the error appears if the safe switch was done on Balance or transactions list pages

**To Reproduce**
Steps to reproduce the behaviour:
1. There are a few safes in the app
2. Turn internet connection off
3. Go to the safe settings page 
Current result: the error is displayed

4. Switch safe
Current result: No error message related to the data loading for the selected safe

**Expected behavior**
The error should be displayed

**Smartphone (please complete the following information):**
 - Device: [Pixel 4, Huawei P30
 - Android Version: 10.1
 - App Version 1.12.1-98
- Staging , Rinkeby

**Additional context**

**Comment by biafra23** [comment]
There is a branch that adds a lot of logging to debug this. `bug/lots_of_logging`. It seems the `SafeSettingsViewModel` doesnt get the activeSafeFlow updates although it subscribes to the flow via: `safeRepository.activeSafeFlow().collect`

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 - 1595
