### ISSUE TITLE
New format for errors

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#842]
Spec: https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1109

**Comment by liliya-soroka** [comment]
The task is closed as only one bug is left :
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1120
app version :  2.7.0 -1634rc
