### ISSUE TITLE
Push notification: Two notification about incoming tx instead of one ( ERTC20 incoming tx)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#843]
**Describe the bug**
The user receives 2 notification about incoming tx instead of 1

**To Reproduce**
1. Send incoming tx to the safe in the app instaled on android device
2. wait for a few sec after the first notification is received
3. Click on both notifications ( one by one) => Both notifications lead to the same safe in the prod mainnet app

**Expected behavior**
One notification per one tx

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 1.12.1 -105
- Prod mainnet

**Additional context**

**Comment by liliya-soroka** [comment]
As the issue may be important for the release,@tschubotz , would you prioritize it as soon as possible, please?

**Comment by tschubotz** [comment]
Could be a backend issue also

**Comment by elgatovital** [comment]
not a client issue

**Comment by rmeissner** [comment]
Also happening on iOS (see gnosis/safe-ios#488) which indicates a backend issue

**Comment by liliya-soroka** [comment]
Waiting for the fix from back-end

**Comment by liliya-soroka** [comment]
Verified on staging
The update for the prod will be required on Mondy

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
