### ISSUE TITLE
Fetch collectibles data that is aggregated already by the groups from the client gateway

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#844]
Client gateway issue: https://github.com/gnosis/safe-client-gateway/issues/132

**Comment by elgatovital** [comment]
I would close this one. Data is aggregated on the client side now and collectables are not a priority for client gw at the moment. @liliya-soroka @jpalvarezl

**Comment by liliya-soroka** [comment]
closed till the migration to client-gateway is done for collectables
