### ISSUE TITLE
Collectible details page

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#846]
- Note: remove "dappcon" uri from the designs
- Use data from the list screen
- NO pull to refresh
- Click on the link for address opens etherscan
- Click on the address copies it to clipboard
- Image is aspect fit
- ID can be long and multiline

Screen tracking

assets_collectibles_details

**Comment by liliya-soroka** [comment]
waiting for collectibles_details event on prod mainnet in firebase
separate issue for copy to clipboard was created
app version 2.0.0 (13)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0(17)
