### ISSUE TITLE
Creation transaction in the list of transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#847]

**Comment by liliya-soroka** [comment]
Why was it closed without QA?

**Comment by liliya-soroka** [comment]
Reopened:
the txs list is not loaded fully if the creation tx doesn't have mastercopy or factory

Prod mainnet safes for testing:
0xFd0f138c1ca4741Ad6D4DecCb352Eb5c1E29D351
0xCC04c8EFF1C7049f948C12DD5286a56114228657

app version 1.12.1 -123

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (14)
