### ISSUE TITLE
Details screen for creation transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#848]
- Data is taken from the list item
- NO pull to refresh
- "Implementation/Master copy" and "Factory" address may be not available

**Comment by rmeissner** [comment]
this depends on https://github.com/gnosis/safe-android/issues/588 right?

**Comment by liliya-soroka** [comment]
@biafra23 , Do we have separate task for the creation tx that should be tested ?

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 123 
The case with no mastercopy and factory will be retested with task https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/847
