### ISSUE TITLE
Push Notification: Balance page is opened instead of txs list after click on notification about incoming tx if the app was closed completely

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#850]
**Describe the bug**
Push Notification: Balance page is opened instead of txs list after click on notification about incoming tx if the app was closed completely

**To Reproduce**
1. Add one safe to the app
2. Close the app completely ( remove from the recently opened list)
3. Send incoming tx to the safe
4. As soon as notification is received open notifications list 
5. Click on the notification to open the app
Current result: App is opened on Balance page instead of transactions list

**Expected behavior**
The transactions list or transaction details ( if possible) page should be used for app opening from the notification

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 1.12.1 -105

**Additional context**

**Comment by tschubotz** [comment]
Is the correct Safe opened? If not, I would say this should be major.
If the correct Safe is opened but on the tx list, I'd say this is minor.

**Comment by liliya-soroka** [comment]
Incorrect safe is opened

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1-110
