### ISSUE TITLE
Track user properties for all events.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-android#854]
**Describe the bug**
We have the user property `num_safes`. This seems to be set only when Safes are added / deleted (cf. [Slack](https://gnosisinc.slack.com/archives/C63LQTGNB/p1598604914314600?thread_ts=1598528873.294700&cid=C63LQTGNB). 

However the intention of the user property was to have it tracked always, so it can also be figured out when a user does never add a Safe.

**To Reproduce**

I used BigQuery to figure this out (cf. [Slack](https://gnosisinc.slack.com/archives/C63LQTGNB/p1598604045314000?thread_ts=1598528873.294700&cid=C63LQTGNB), [Wiki](https://github.com/gnosis/safe/wiki/How-to-check-tracking-events-with-BigQuery)

```SQL
SELECT event_name, count(*)
FROM `safe-firebase-mainnet.analytics_243403902.events_*` 
where platform = 'ANDROID'
  and app_info.version like '1.12.1-98-gf%'
  and not EXISTS(SELECT key FROM UNNEST(user_properties) WHERE key='num_safes')
group by 1
order by 1 asc
```

**Expected behavior**

`num_safes` is tracked with any event.
All user props should be tracked with any event actually.

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -115

**Comment by liliya-soroka** [comment]
Reopened.
We have expected that the all user_props are tracked with all events.
app version 1.12.1 -115

**Comment by liliya-soroka** [comment]
@DmitryBespalov , the same issue is actual for the ios app.
According the stand up discussion ( week ago) the expected result should be discussed one more time

**Comment by DmitryBespalov** [comment]
@tschubotz I'm confused, as user properties are attributes that you would use to describe segments of the user base. Do I understand that what you actually mean is that every event should have **event** parameters, including num_safes?

**Comment by tschubotz** [comment]
I thought that event params should be specific to events and user attributes are something that is specific to the user. They can be used for segmentation yes. So for instance a segment could be "users with no Safe" or "users with more than 2 Safes". Hence I think `num_safes` should be user a property.

**Comment by DmitryBespalov** [comment]
Refinement meeting: the debug view doesn't show the user properties right away. The values of the user properties are added retroactively. If the user changes the property within the same session and goes back to the initial value, then that change is not tracked.

**Comment by tschubotz** [comment]
After implementing #1045 it seems to work now:

```
SELECT event_name, app_info.version, count(*)
FROM `safe-firebase-mainnet.analytics_243403902.events_*`
where platform = 'ANDROID'
  and app_info.version like '2.6.0%'
  and not EXISTS(SELECT key FROM UNNEST(user_properties) WHERE key='num_safes')
  and event_name not in ('screen_launch', 'user_engagement', 'firebase_campaign', 'session_start', 'first_open', 'screen_view', 'screen_launch_terms')
group by 1,2
order by 3 desc
```

For some of the early events (screen_launch) and some of the firebase default events (user_engagement), it's still missing sometimes, but I don't care about those too much.
So let's see how this behaves after the release of 2.6.0. But I would close this one for now.
