### ISSUE TITLE
Transactions list is not updated after moving from transaction details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#855]
**Describe the bug**
Transactions list is not updated after moving from the transaction details page. In some cases, it's really confusing.
Case:
1. The app is located in the background on the user's device
2. Send a few outgoing txs without app reopening
3. Click on the latest received notification
4. Click notification 
5. Go back from the transaction details for the latest executed tx

Current result: The transactions list is no up to date and the user is confusing why he can not see just checked transaction in the list 
Expected result: I think that the txs list should be updated after going back from the tx details

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 1.12.1 - 107

**Comment by tschubotz** [comment]
Does this happen to all notifications which open the tx details? I yes I think this is major, if not I think it should be minor.

**Comment by liliya-soroka** [comment]
The issue still actual.
Pull to refresh required to update transactions list after coming back from the transaction details page.
Current result: The transactions list page is blinked but not updated

app version 1.12.1-110 ( staging and prod Rinkeby)

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 - 114
