### ISSUE TITLE
Opening TX List from push notification

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#858]
**Describe the bug**
Transaction list does not show the new transaction when clicking the notification. This maybe have been solved by https://github.com/gnosis/safe-android/pull/857

**Additional context**
This came from `bug bashing` session

**Comment by liliya-soroka** [comment]
Not fixed in 1.12.1-110
When the incoming tx notification has clicked the app with opened txs list is opened but it doesn't contain the tx from the notification
@tschubotz , I think it's a major issue

**Comment by liliya-soroka** [comment]
Verified
app version 1.12.1 -114
