### ISSUE TITLE
[Android] The safe settings is updated without loading icon ( it 's frozen with old data for some time)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#866]
**Describe the bug**
 The safe settings is updated without loading icon ( the old data are displayed for some time ).
When the safe is switched on safe settings page or the safe name is updated, seems that the app is displayed the old data and nothing is changed for some time, because instead of using loading icon the old data is displayed till the new is completely loaded. 

**To Reproduce**
1. Go to the safe settings for the safe 1
2. Switch safe
Current result: The selected safe 2 data are displayed in the header but the safe settings content is related to the previous safe for some time.
3. Go to edit safe name
4. change the name and click save
Current result: the old name is displayed for sometime before the new appears
5. Remove safe
Current result: the removed safe data is displayed for some time before the next active safe data is loaded

**Expected behavior**
Add loading icon and don't display old or another safe data after updating

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 1.12.1 -114
- prod staging, mainnet
**Additional context**

**Comment by tschubotz** [comment]
Marking as minor since we expect most users to have only 1 Safe for now. But should be fixed after the release for sure.

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -1374
