### ISSUE TITLE
Check for memory leaks

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#868]
After the public release we could check with https://github.com/square/leakcanary/ in debug builds

**Comment by biafra23** [comment]
Notes for QA:
Leak Canary should **not** show up in any of the following builds: 
- internal
- production mainnet
- production rinkeby

**Comment by liliya-soroka** [comment]
The issue will be verified during full regression on prod env

**Comment by biafra23** [comment]
We need a flavor `profile` and activate Leak canary for that flavor only.

**Comment by biafra23** [comment]
@liliya-soroka You can only test, that leak canary does not show up in any of your builds. If you want to see it, you can build an app with the flavor `profile` on your local machine. 

Either by selecting "profile" in the p"Build Variants" panel in Android Studio and build. 
Or on the command lin via `./gradlew assmbleProfile`

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 -1595
