### ISSUE TITLE
[Android]Loading icon is displayed under "Load safe multisig" button on transaction details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#870]
**Describe the bug**
Loading icon is displayed under "Lad safe multisig" button on transaction details page

**To Reproduce**
1. Remove all safes or reinstall app 
2. Accept T&C
3. Open transactions list

**Expected behavior**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/100c4b9b-fcf0-4cc8-aca1-e88bfbb63a0f)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 115
- env : prod and staging, mainnet and rinkeby

**Additional context**

**Comment by tschubotz** [comment]
> Steps to reproduce the behavior:
>  Remove all safes or reinstall app

Does that mean it also happens on a clean install? @liliya-soroka 
In that case I would mark this as major since it's an unnecessary UI glitch that really everyone would see. Not good for trust.

**Comment by elgatovital** [comment]
you mean tx list page and not tx details

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 -(23)
