### ISSUE TITLE
Buildkite: last tag is not loaded on buildserver -> wrong app version name

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#874]
`git describe --tags --always` not executed correctly on buildkite
Investigate and adjust `prepare_env_buildkite.sh` so that correct app version name is created during deployment.

- Device:
- Android OS version:
- Safe app version:

**Comment by biafra23** [comment]
It seems the checked out repo on the buildkite server at `/var/lib/buildkite-agent/builds/safe-ci-1/gnosis/safe-multisig` does not have the v2.0.0 tag. 

But it is a the latest commit (26d97ed4)

Why doesn't it know about the tag?

Same for: `/var/lib/buildkite-agent/builds/safe-ci-1/gnosis/safe-multisig-deployment`

**Comment by biafra23** [comment]
Adding `git fetch` to `prepar_env_buildkite.sh` should solve this.
