### ISSUE TITLE
[Android]Collectibles: no shadow above top border of the card

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#886]
**Describe the bug**
Collectibles: no shadow above top border of the card. It's a little bit complicated to see the top of the card 

**To Reproduce**
1. Go to 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open Collectibles list

**Expected behavior**
It should be done as on design - https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5e9efc63f095427a65137844

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/06923179-2cc4-4988-8e31-dff1e0db9ce8)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 2.0.0 - 10

**Additional context**

**Comment by rmeissner** [comment]
By default cards don't have a shadow on top according to material design: https://material.io/components/cards (Android uses the library by google for material design)

@posthnikova is this required?

**Comment by posthnikova** [comment]
> By default cards don't have a shadow on top according to material design

@rmeissner Not everywhere, it depends on the elevation. At 1dp the shadow on top is barely visible. Cards are 1dp so this looks correct. But still in the official UI kit you can see the shadow on top, on production it's a bit different. 

![image](https://user-images.githubusercontent.com/45787536/92890007-04ca1880-f417-11ea-93f5-0fe909ff79a0.png)

Tab bar and Nav bar are elevated more therefore the shadows should be more visible.

**Comment by rmeissner** [comment]
Yes the different elevations should be supported by the Android sdk (can be probably applied with `app:elevation="4dp"`)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 ( 16)
