### ISSUE TITLE
Prepare Release Process

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#887]
- [x] Discuss release process with team 
  - proposal is to align it with ios which would include changes listed below
- [x] Create template for a release issue and use it to create release ticket during release process
- [x] Update https://github.com/gnosis/safe-android/blob/master/docs/RELEASE.md
- [x] Adjust build pipeline to use `release` branch for publishing rc's and uploading to github
  - having explicit release branch will allow us to continue to develop features that are not part of the release

**Comment by liliya-soroka** [comment]
closed as no QA required
