### ISSUE TITLE
[Android]Collectible details: It should be possible to copy asset contract to clipboard

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#889]
**Describe the bug**
There is no possibility to copy asst address. Instead of copy the page about address in Etherscan is opened

**To Reproduce**
1. Go to safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open collectibles
3. Open details for any collectible
4. click asset address

**Expected behavior**
It should be possible to copy asset contract to clipboard

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 2.0.0 ( 10)

**Additional context**

**Comment by elgatovital** [comment]
same here (advanced safe settings)? ![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/dfee7ea8-32c4-4aa3-b3f7-b7db5716bfc8) 
Click on address -> copy to clipboard; click on link icon -> go to etherscan?

**Comment by tschubotz** [comment]
yes :)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 ( 16)
