### ISSUE TITLE
[Android] Not available should be displayed if no mastercopy

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#893]
**Describe the bug**
The mastercopy field is not displayed at all on creation tx details page if no mastercopy

**To Reproduce**
1. Open creation tx details page for safe created without mastercopy
Prod mainnet safes for testing:
0xFd0f138c1ca4741Ad6D4DecCb352Eb5c1E29D351
0xCC04c8EFF1C7049f948C12DD5286a56114228657

**Expected behavior**
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ec3e38405678a46cf890190

**Smartphone (please complete the following information):**
 - Device: [Pixel 4
 - Android Version: 10.1
 - App Version 2.0.0 ( 14)

**Additional context**

**Comment by liliya-soroka** [comment]
no need to include the fix in the 2.1.0 release - not a critical

**Comment by biafra23** [comment]
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/7db1f61e-33e6-483b-a3be-2a5d84453987)
