### ISSUE TITLE
[Android] Cancelled rejection tx has status waiting for execution on tx details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#898]
**Describe the bug**
Already cancelled rejection tx has status Execute ( n more confirmations required) in the confirmation block for more then a 1 min. Page reopening and page refreshing with. using pull to refresh don't help in status updating
Safe: 0x938bae50a210b80EA233112800Cd5Bc2e7644300
original tx nonce = 105
**To Reproduce**
1. Create outgoing tx ( at least 2 confirmations are required)
2. One of the owners rejects the original tx
3. Get required confirmations for the original tx without executing
4. Run original tx executing separately from confirmation
5. Open tx details for the rejection tx 
Current result: On the tx list the rejection tx has status Cancelled but on tx details there is Execute ( n more confirmations required) is displayed in the confirmation block instead of cancelled

6. Come back to the deatils page from the tx list a few times
7. Pull to refresh tx details page to update details
Current result: The wrong state is displayed for more than 1 min 

**Expected behavior**
The confirmation block should contain up to date information

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9027514f-e3b0-42f7-8ac1-53d5cc1de8e5)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c0533df7-97fc-4957-87a6-dfab467bd228)

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 2.0.0 ( 17)
- env. prod, rinkeby

**Additional context**

**Comment by tschubotz** [comment]
Marking this as major for 2 reasons:

- tx status is important for trust. It should be consistent.
- With cancellation txs we anyway already have inconsistent behavior with the web, so I would not build up more confusion here.

**Comment by biafra23** [comment]
Is this really an error? The rejection hasn't reached the threshold. And the confirmation has reached it and is marked as waiting for execution. 

tx list | "rejection" | confirmations
------|------------|------------
![Screenshot_20200914-185431](https://user-images.githubusercontent.com/246473/93115463-2c8dda80-f6bc-11ea-8789-164fe14ef603.png) | ![Screenshot_20200914-185450](https://user-images.githubusercontent.com/246473/93115503-3c0d2380-f6bc-11ea-8330-98f5d252c5d8.png) | ![Screenshot_20200914-185503](https://user-images.githubusercontent.com/246473/93115589-59da8880-f6bc-11ea-9924-cf9b7486fb0f.png)

**Comment by biafra23** [comment]
Maybe this was a client gateway bug that has been fixed in the meantime? @liliya-soroka Can you still reproduce this bug?

**Comment by liliya-soroka** [comment]
@tschubotz and @biafra23 , I can not reproduce the issue now. I suggest to lower priority and assign it back to me to research for exact steps

**Comment by liliya-soroka** [comment]
can not reproduce

**Comment by liliya-soroka** [comment]
closed as can't reproduce
