### ISSUE TITLE
DataDecoding: UI for arrays and nested arrays

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-android#904]
Display arrays of values and nested arrays of values

To be refined:
- Indentation of the nested arrays; arrays are collapsible
- limit the nesting levels to 10

Designs 
- web: https://zpl.io/amplpRQ
- app: [zpl://screen?pid=5e9efc30726e106958cc43de&sid=5f4e3d1cef6167b00769a540](zpl://screen?pid=5e9efc30726e106958cc43de&sid=5f4e3d1cef6167b00769a540)

**Comment by liliya-soroka** [comment]
waiting for ABI from Uxio to test nested array

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 - 1277rc
