### ISSUE TITLE
[Android] Balance list is not sorted correctly

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#913]
**Describe the bug**
It's not clear how the balance list is sorted 

**To Reproduce**
1. Go to 0x84443F61efc60D10DA9F9a2398980CD5748394BB
2. Open coins page

**Expected behavior**
From requirments : User can see the balance of all ERC20 tokens with balance > 0, tokens are ordered by their names, ascending

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10.1
 - App Version 2.0.0 - 23

**Environment**
Prod, mainnet 

**Additional context**

**Comment by tschubotz** [comment]
Same like on iOS (gnosis/safe-ios#555). How are they currently sorted? Is it the sorting from the backend?
Happy to adjust the requirement (sorting by name) also.

**Comment by liliya-soroka** [comment]
Verified
closed as fixed on back-end 2.2.0 - 1174rc
