### ISSUE TITLE
Tx creation page layout adjustemnts (LS: full regression)

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#936]
MasterCopyItem has its own separator that is merged with separator on creation tx page creating a thick line: ![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/55c76df4-c231-48ee-9478-a1e6deb77415)

add xml attributes to specify visibility of the innate separator (e.g. like in AddressItem)

fragment_transaction_details_creation.xml layout readability improvement:
Use ViewSwitcher to group implementation_item & no_implementation_item. Same for factory_item. This will allow switching views by simply calling switcher.showNext(). Also, grouping elements in ViewSwitcher will make xml more readable as it will be more clear that elements belong together. 

- Device:
- Android OS version:
- Safe app version:

**Notes for QA**: This change might break the layout of tx list, tx details,  app settings, collectible details and safe settings.

**Comment by liliya-soroka** [comment]
@elgatovital , seem that the same issue on the tx details page for ERC721 - the line under Asset Contract is too thick. Could it be also fixed in the issue or it's better to create a new one?

**Comment by biafra23** [comment]
@liliya-soroka I tried to find and fix this double line bug everywhere. That means you probably have to check the whole app for errors. Sorry!

**Comment by liliya-soroka** [comment]
The issue should be carefully checked during the full regression for the release candidate 2.5.0

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0-1421rc
