### ISSUE TITLE
Entry point to import owner key in App Settings

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#946]
On the App settings screen there is an “Import owner key” row, if there is no key imported yet.

Selecting it should lead to the “Import Owner Key”

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e6aa6330-bf6e-440f-87cc-b929eb4064ac" width=300/>

On the App settings screen, there is an “Imported owner key” row, if there is a key imported.

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/d938453e-139a-4081-9a53-35ad0323d378)

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 - 1239
