### ISSUE TITLE
Import owner key screen

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#947]
- Scrolling should be available to support small screen resolutions.
- When the screen is opened the “Enter seed phrase” is focused by default.
- This field does not have any text input limitations.
- When selecting the “Next” button OR selecting “Enter” button on the keyboard, the form “submission” should happen.
  - Strip or ignore extra whitespace and punctuation symbols in the phrase. For example, words can be separated by more than one space or by new line symbol
  - Any letter case should be accepted (upper, lower, mixed)
  - Seed phrase validated according to underlying ETH/crypto library
  - Words should be lower cased
- If the input is valid, the next screen “Import Owner Key” should be presented.
- If the input is not valid, the error state should be displayed.

![image](https://user-images.githubusercontent.com/2284385/94420115-f8b6b880-0183-11eb-90b3-f359d220854b.png)

**ERROR STATE**
- In error state text input should be highlighted, and the “Seed phrase is not valid” message should be displayed.
- Typing in the text field should return it back to the “normal” state immediately.

![image](https://user-images.githubusercontent.com/2284385/94420194-18e67780-0184-11eb-8ad3-0e5d0e3a0e07.png)

Edit:
**Tracking**
Check seed phrase [screen names](https://github.com/gnosis/safe/wiki/Overview-screen-tracking)

Edit2:
**Designs**
https://zpl.io/Vkd0Xpg
https://zpl.io/amo0Md6

**Comment by elgatovital** [comment]
@biafra23 move it to https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/953

**Comment by biafra23** [comment]
This code validates the seed phrase ATM the result is unmodified parameter : 
```
val bip39: Bip39 = Bip39Generator(AndroidWordListProvider(this))
bip39.validateMnemonic("creek banner employ mix teach sunny sure mutual pole mom either lion")
```

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 - 1324
