### ISSUE TITLE
"Awaiting your confirmation" state in transactions list screen

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#949]
Transactions that can be signed by an imported key should be displayed as “Awaiting your confirmation” if it doesn't have enough signatures.

Show “Awaiting execution” always if there are enough signatures so a user can not sign.

<img src="https://images.zenhubusercontent.com/5dea66701abe006b54a3a941/84b2ac00-c4f1-448d-b228-99a8be36e46f" width=300/>

**Dependency on the Client Gateway** to get list of signers that did not sign yet the transaction

**Comment by liliya-soroka** [comment]
Verified
app version 2.43.0 -1326
