### ISSUE TITLE
Remove owner key: confirmation dialog

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#951]
Selecting the “remove” icon should display a confirmation.

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/7f1e95fc-2e72-4056-abf8-18c14a8ab711)

On confirming:
- the key should be removed from secure storage.
- The key address should be removed from the app storage.

**Comment by liliya-soroka** [comment]
verified
app version 2.3.0 - 1293
