### ISSUE TITLE
Display confirm Button

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#954]
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/3f2849b6-9986-47df-84d1-e3b2ca3cd5cd" width=300/>

Confirm button should be displayed, if the transaction is in “Awaiting your confirmation” state (the imported key is among safe owners, but not among confirmations)

The confirm button should be stick to the bottom tab bar.

### Selecting “Confirm” should
- Display a confirmation request
![Screenshot 2020-09-28 at 12.09.58.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8a418e2e-d8f6-4963-95aa-98b5843331b9)
- When user confirmed the pop-up, app makes networking request to the backend to submit the confirmation (see below)
- The activity indicator should be displayed:
  - the confirmation button is blocked, and pull to refresh activity indicator is present.
- When successful, the transaction details data updates the screen, so that "Confirm" button is hidden and a notification should be displayed 
![Screenshot 2020-09-28 at 12.12.26.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/49a9aaf8-77d7-4632-a100-62c11bc36311)

**Comment by elgatovital** [comment]
Blocked by https://github.com/gnosis/safe-client-gateway/issues/162

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 - 1329rc
