### ISSUE TITLE
Clean up SSL pinning

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#955]
- Check that correct hashes are used
  - In the configuration, the "gnosis.pm" or "gnosisdev.pm(?)" are not used anymore
  - The 4 out of 5 SSL hashes are outdated
- Test the pinning

**Comment by liliya-soroka** [comment]
The message “Please check whether the time is correctly set ” is displayed on UI
app version 2.4.0-1332rc

**Comment by elgatovital** [comment]
this issue is not part of RC

**Comment by liliya-soroka** [comment]
Reopened:
app version  2.4. 0- 1337
Steps to reproduce
1. Set up a connection to the proxy on a mobile device
2. Run mitmdump -s error_response.py  in the terminal on the pc
3. Start the app
4. Open any page that requires request: balance, collectibles, tx list , safe settings, switch safe
Current result: “Please check whether the time is correctly set ” is displayed
Screenshot: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0ed47244-fbb4-4fca-a2f1-12ff96defe84)
Staging, rinkeby
Huawei P30

**Comment by elgatovital** [comment]
What are the details of the error response you are sending? Also this issue is not related to ssl pinning and should be handled in a separate ticket. If there would be something wrong with pins, you won't get any results at all on all pages. And here only error response is handled wrongly (also in release candidate version, which doesn't have this cleanup)

**Comment by liliya-soroka** [comment]
The new issue is created - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1036
In the new steps I did not use the command to send own response, instead of it minmproxy command is used.
