### ISSUE TITLE
Safe TxHash validation

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#957]
### Additional information
- https://github.com/gnosis/safe-contracts/blob/94f9b9083790495f67b661bfa93b06dcba2d3949/contracts/GnosisSafe.sol#L403
- https://docs.gnosis.io/safe/docs/contracts_signatures/ (ECDSA signature)
- https://docs.gnosis.io/safe/docs/contracts_tx_execution/#transaction-hash (Transaction hash)

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0-debug with turned off pinning
