### ISSUE TITLE
Submitting the transaction confirmation

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#958]
- The app uses /safes/{address}/transactions/ endpoint of the transaction service to submit  the confirmation
- After getting a successful response, the app will request updated tx details using the gateway service.
  - The screen should be updated with the latest tx info: awaiting execution or awaiting confirmations.
- In case of error, the app hides the loading indicator and displays the actual (latest) state with “Confirm” button, and a snackbar with the error message.
  - In V1 we will always show a “Failed to sign” message for all 422 errors.
  - Error message codes (TBD)
    - Networking error
    - Signing the tx when the key is already not an owner
    - Signing already executed tx
    - What else? (Unexpected error)

- In case of the transaction details request failure, the app displays “Data can not be loaded” placeholder and a standard snackbar with an error message.

### Additional information
- https://github.com/gnosis/safe-contracts/blob/94f9b9083790495f67b661bfa93b06dcba2d3949/contracts/GnosisSafe.sol#L403
- https://docs.gnosis.io/safe/docs/contracts_signatures/ (ECDSA signature)
- https://docs.gnosis.io/safe/docs/contracts_tx_execution/#transaction-hash (Transaction hash)

**Comment by elgatovital** [comment]
Blocked by https://github.com/gnosis/safe-client-gateway/issues/162

**Comment by jpalvarezl** [comment]
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5f7447bf583784456fd188f1

https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5f7447c17a3d6a33302fd47a

https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5f7447c46973a665771cd69c

**Comment by liliya-soroka** [comment]
Verified with one note:
The next requirement will be covered later
"Error message codes (TBD)
Networking error
Signing the tx when the key is already not an owner
Signing already executed tx
What else? (Unexpected error)"
app version: 2.4.0-1332rc
