### ISSUE TITLE
[Android] Custom tx has + instead of - in tx list and on tx details page

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#959]
Bug description
The + amount is displayed in custom tx instead of - in txs list and tx details
Steps To Reproduce
1. Safe = 0xD2b3D480Db9Fb08Ea55c349C0299b81892F31544 ( prod mainnet)
2. Check tx with nonce = 553 and 552 in transactions list and on the transaction details page
Expected Result
the amount should contain "- "as the custom tx transfers funds out. It should be taken into account in the transaction list and in the header on the transaction details
Screenshots

Device & App version

Device/OS: Huawei P30/ 10.1
App version: 2.1.0 - 1172
Environment
Prod , mainnet
Additional info
(Optional)

**Comment by tschubotz** [comment]
Just assigned `major` since I think + or - is important to get right for trust reasons.

I think this should not blocking the release though. But it might be related to the client gateway.

**Comment by biafra23** [comment]
@liliya-soroka Do you have an example of this on rinkeby? Testing something on a release build is always a bit cumbersome on Android. Or can you tell me, how you created these transactions?

**Comment by biafra23** [comment]
A failed version of this is on 0x2134Bb3DE97813678daC21575E7A77a95079FC51 Nonce 22 on Rinkeby

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -1374
