### ISSUE TITLE
Extract harcoded strings to strings.xml

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#964]
Strings used to display information should never be hardcoded. Use the Android resource framework to separate the localized aspects of the app.

Identified violations:

SafeRepository
```
const val DEFAULT_FALLBACK_HANDLER_DISPLAY_STRING = "DefaultFallbackHandler"
const val SAFE_MASTER_COPY_UNKNOWN_DISPLAY_STRING = "Unknown"
```

**Comment by liliya-soroka** [comment]
Verfieid
app version 2.6.0 -1534rc
