### ISSUE TITLE
[Android] Crash from prod: NotificationRepository.java line 153

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#966]
**Describe the bug**
Crash from prod in firebase :
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/e44f2eeb74ab1c239d18b5f74bb53287?time=last-seven-days&sessionEventKey=5F71E2F60184000110662CB4C6778FC7_1455927257245351559

**To Reproduce**
???
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/188ec5f2-a8d8-487b-bc18-c7de3d1edc63)
1 user was affected, 1 crash 
**Expected behavior**
No crash 

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android Version: 8.1.0
 - App Version 2.0.0 ( 882)

**Environment**
Prod mainnet
**Additional context**

**Comment by elgatovital** [comment]
Fixed starting from 2.1.0

**Comment by liliya-soroka** [comment]
Deep regression with sending app to background and more cases for T&C are required for the 2.3.0 RC

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 - 1278rc
