### ISSUE TITLE
[Android] Crashes on Terms & Conditions (ActivityThread.java line 4195) 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#970]
**Describe the bug**
The app is crashed after calling from background with opened T&C ( one more send to background before it required)
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/1540c48a0e8188eb53486507839c3a7d?time=last-seven-days&sessionEventKey=5F74886A02D200013D9079EA7C0DB696_1456721774167076019
**To Reproduce**
1. Install the app
2. Launch app
3. Click Get started
4. Selec No thanks and send the app to the background 
5. wait for some time ( 1 min) and call the app from the background using the click on the app icon
Current result: The app is opened with opened "Terms and conditions"dialog. The strange thing that the dialog should be closed in step 
6. Send the app to the background with open Terms and Conditiona dialog
7. wait for some time
8. Call the app from the background
Current result: The app is crashed 
**Expected behavior**
After the step 5 the app should be opened with closed T&C dialog and the app should not crash 

**Smartphone (please complete the following information):**
 - Device: Pixel 4, Samsung A70
 - Android Version: [10
 - App Version 2.2.0 -1206

**Environment**
Prod mainnet

**Comment by biafra23** [comment]
I can reproduce the crash by opening the app and just putting it in the background for a while. It usually crashes, when it was in the background for a minute.

**Comment by biafra23** [comment]
This could be a way to fix it.

**Comment by biafra23** [comment]
When the app is restarted (after it was in background) the event SplashViewModel.ShowTerms is received again. That's why the bottom sheet is reopened on app start. Apparently this event is sticky. It probably shouldn't be. 
The following is a workaournd in SplashActivity to prevent the crash:

```
                is SplashViewModel.ShowTerms -> {
                    termsBottomSheetDialog.apply {
                        onAgreeClickListener = {
                            viewModel.handleAgreeClicked()
                        }
                    }
                    if (!termsBottomSheetDialog.isAdded) {
                        termsBottomSheetDialog.show(supportFragmentManager, TermsBottomSheetDialog::class.simpleName)
                    }
                }
```

**Comment by jpalvarezl** [comment]
Absolutely, agree. I would suggest coming up with an implementation of `BaseViewModel` that doesn't cache the last emitted event.

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 - 1278rc
