### ISSUE TITLE
[Android] Crash: QRCodeScanActivity.java line 77 io.gnosis.safe.qrscanner.QRCodeScanActivity$Companion.startForResult ( researching for the steps)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-android#971]
**Describe the bug**
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/e5ce9d75d48b9d8bc2a34c14d4bd1df2?time=last-seven-days&sessionEventKey=5F7AA6AC0316000122AEB6A0F8708344_1458515071215076269

**To Reproduce**
1. in progress of researching

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Galaxy Note10
 - Android Version: 10
 - App Version 2.1.0 (1058)

**Environment**
Prod , mainnet
**Additional context**

**Comment by DmitryBespalov** [comment]
Might be caused by a change in screen orientation while using the camera

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -1487
