### ISSUE TITLE
Securely pass seed phrase to owner key generation screen

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-android#979]
**Is your feature request related to a problem? Please describe.**
Currently, we are using navigation parameters for passing the input seed phrase to the owner key generation screen. It is unclear whether this is done with intents, in which case the passage of information is not secure. 

**Describe the solution you'd like**
Sharing the viewModel between the `ImportOwnerKeyFragment` and `OwnerSelectionFragment`

**Additional context**
https://github.com/gnosis/safe-android/pull/973#discussion_r499597448
https://stackoverflow.com/questions/49759331/security-of-critical-data-passing-between-activities-via-intent-extras

**Comment by elgatovital** [comment]
confirm that passing data btw fragments is secure enough and close

**Comment by DmitryBespalov** [comment]
@rmeissner @elgatovital can you please review this and close/update?
