### ISSUE TITLE
Entry point to multisend action from tx details

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#983]
https://zpl.io/25Le43J
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/e15fa2f7-7e3b-4682-85e9-6024812f00bc)

- Display `Multisend (<number of actions> actions)`
- When clicked navigate to multisend actions list
- Number of actions = number of valueDecoded elements

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 -1278rc
