### ISSUE TITLE
Show data element with undecoded data in non-multisend action details

### ISSUE THREAD

**Issue by elgatovital** [gnosis/safe-android#985]
Show Data element with undecoded data at the top of the screen in the "Action details" screen.
  -  Use `txData.hexData` for the data
  - Show upper divider if transfer element is present
  - Show lower divider if additional decoded parameters are available.

The reason to add this section is that the parameters sometimes are not available because `dataDecoded` is null.

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 - 1276rc
